### ISSUE TITLE
CLIENT REPLY is not supported

### ISSUE THREAD

**Issue by itamarhaber** [redis/redis-py#1059]
OFF and SKIP may be tricky if we rely on replies

**Comment by laixintao** [comment]
Hi @itamarhaber @andymccurdy I want to give it a try implement this.

How about adding an option to `Redis()`, using like this:
```
r = Redis(client_reply=False)
x = r.set("foo", "bar")  # x will always be None
```

So if you want `CLIENT REPLY OFF`, you can create a new `Client()` instrance,  all connections from pool will set `CLIENT REPLY OFF` in `on_connection`.

Also add a method for `Client` like:
```
with client.without_reply:
    x = client.set("foo", "bar")  # x will be None
    y = client.get("foo")  # y will be None
```
This will trigger a `CLIENT REPLY SKIP` for every command in `with`.

What do you think?

**Comment by guybe7** [comment]
@andymccurdy ping about that
