### ISSUE TITLE
Incorrect error message `MasterNotFoundError: No master found for 'pre'` when timeout.

### ISSUE THREAD

**Issue by eromoe** [redis/redis-py#1125]
**Version**: 2.10.6
**Platform**: 3.6 on win 10

**Description**: 

if `socket_timeout=0.1` : 

```
sentinel = Sentinel([("192.168.0.10", 26379),("192.168.0.11", 26379),("192.168.0.12", 26379)], password='xxxxxx', socket_timeout=0.1)
sentinel.discover_master('pre')

```
got error:
```
C:\Anaconda3\lib\site-packages\redis\sentinel.py in discover_master(self, service_name)
    221                     sentinel, self.sentinels[0])
    222                 return state['ip'], state['port']
--> 223         raise MasterNotFoundError("No master found for %r" % (service_name,))
    224
    225     def filter_slaves(self, slaves):

MasterNotFoundError: No master found for 'pre'
```

But remove socket_timeout : 

```
sentinel = Sentinel([("192.168.0.10", 26379),("192.168.0.11", 26379),("192.168.0.12", 26379)], password='xxxxxx')
sentinel.discover_master('pre')

```
got `('192.168.0.12', 6316)`

This misleading message waste me lot of time .

**Comment by kishvanchee** [comment]
**Version:** 3.3.11
**Platform:** Ubuntu 18.04

The error still exists. I had to connect to an azure VM and it kept giving me this error. I increased the `socket_timeout=0.5` and it worked for me.

**Comment by svagner** [comment]
+1 the same problem

**Comment by sathish9094** [comment]
Getting the same error when i try to configure with airflow celery

  AIRFLOW__CELERY__BROKER_URL="sentinel://$SENTINEL_HOST:$SENTINEL_PORT"
  AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS={'master_name':"mymaster"}

**Comment by andymccurdy** [comment]
Setting `socket_timeout` configures the socket to raise a timeout after `socket_timeout` seconds have elapsed. Setting this value too low for your environment will cause every command to a Redis or Sentinel server to timeout.

In this particular case, the redis-py Sentinel code catches the `TimeoutError` and tries the next Sentinel server. If none of the Sentinel servers respond, the `MasterNotFoundError` is raised.

**Comment by sathish9094** [comment]
> Getting the same error when i try to configure with airflow celery
> 
> AIRFLOW__CELERY__BROKER_URL="sentinel://$SENTINEL_HOST:$SENTINEL_PORT"
> AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS={'master_name':"mymaster"}

Resolved!

**Comment by woshishipeiyu** [comment]
try this:
    sentinel = Sentinel([
        ('xxx.xxx.xxx.xxx', 26379),
    ],
        sentinel_kwargs={"password": "xxxxxx"}
    )

**Comment by Cimmanuel** [comment]
> > Getting the same error when i try to configure with airflow celery
> > AIRFLOW__CELERY__BROKER_URL="sentinel://$SENTINEL_HOST:$SENTINEL_PORT"
> > AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS={'master_name':"mymaster"}
> 
> Resolved!

How did you solve this please?

**Comment by sathish9094** [comment]
**Below environment variables are defined.**

REDIS_PASSWORD=xyz
SENTINEL_HOST_NAME=10.1.3.124
SENTINEL_PORT=26379
REDIS_DATABASE=0
SENTINEL_MASTER_NAME=mymaster
AIRFLOW__CELERY__BROKER_URL+="sentinel://:$REDIS_PASSWORD@${!SENTINEL_HOST_NAME}:$SENTINEL_PORT/$REDIS_DATABASE;"
AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__MASTER_NAME="$SENTINEL_MASTER_NAME"

**Comment by chayim** [comment]
Closing.
