### ISSUE TITLE
Issue: when disabling IO-Threads the following command throws an exception ( Error while reading from socket: connection reset by peer or connection closed by server)

### ISSUE THREAD

**Issue by 4aalon** [redis/redis-py#1422]
Hello guys, I currently upgraded the redis-py package to a newer version ( 3.5.3 ) of the package (previously I used version 3.0.1). And now an issue that didn't happen before with an older version of the package started to occur: 
(I use python 3.8 on Linux)
When I use a command that disables IO-Threads on runtime the command that comes after it that uses the client (for example: info command) fails in the function _read_from_socket in connection.py with the error (Connection closed by server or Error while reading from socket: connection reset by peer). This issue didn't happen with older version of the package. 
I think the reason for that is that the connections are being disconnected and are not able to be established again fast enough. If I use time.sleep command after the command that disables IO-Threads it solves the issue but I don't want to use hard-coded sleeps.
Can anybody explain please how to solve it? or why it started to happen when I started to use the new version of redis-py ? (Maybe some default configurations have changed).

**Comment by andymccurdy** [comment]
Can you provide more details on what "disabling IO Threads on runtime" means?

**Comment by 4aalon** [comment]
I use this feature:
https://www.infoworld.com/article/3541356/redis-6-arrives-with-multithreading-for-faster-io.html 
and when I disable this feature on runtime and afterwards  I use a command that uses the server it fails and only sleeps solve the problem. It didn't happen in older version of the package.

**Comment by andymccurdy** [comment]
There was a bug prior to version 3.1.0 that would inadvertently retry some commands: #1022. My guess is that your configuration with 3.0.1 hit this behavior.

**Comment by 4aalon** [comment]
Is there a way yo recreate this exact behavior with the new version of the package?

**Comment by andymccurdy** [comment]
No, the bug was fixed and now users are required to handle errors when they occur.
