### ISSUE TITLE
How to resolve "authentication required" issue for a shared queue with multiple consumers

### ISSUE THREAD

**Issue by fans3210** [redis/redis-py#1424]
I'm setting up a kubernetes cluster with redis image. No password is provided. Two containers running the worker process are consuming the same queue using a while loop with a sleeping time of 0.1 seconds.
However, I'm facing the 'authentication required' error when trying to pop item from the queue when another worker processs is also connected. I tried to set the 'health_check_interval' to be 1 second but still unable to avoid this exception.

My current solution is to running a while loop pinging command before the actual pop queue command is executed. This is to make sure there would be no such error when running the pop command to get items from the queue like below:
  ```
  ping = False
    while ping == False:
        try:
            ping = r.ping()
        except Exception as e:
            print('ping err: ', e)
        print(str('Redis Alive:'+str(ping)))
        time.sleep(1)
```
The logs are:
> pre-py ping err:  Authentication required.
> pre-py Redis Alive:False
> pre-py Redis Alive:True
> pre-py ping finished

I'm wondering, is there any recommended way to handle this problem? Thanks

**Comment by andymccurdy** [comment]
To my knowledge, the only reason you'd be seeing an error regarding "authentication" is if your Redis server has a password set or has ACL turned on. I also don't understand why you'd sometimes get authentication errors and sometimes things would work. If this is actually an authentication issue, it seems like connections would always work or always fail.

Does your server have the `maxclients` setting enabled? If so, you might check how many clients are connected when you receive one of these errors.

Can you share the stack trace with the authentication error?

**Comment by fans3210** [comment]
@andymccurdy . I'm using redis official docker image without further config. The maxclients is 10000. I didn't see such issue today. I will try to print the stack trace once this issue happens again. Thanks
