### ISSUE TITLE
pubsub.listen() raises list out of index error sometimes

### ISSUE THREAD

**Issue by davit555** [redis/redis-py#1490]
**Version**: redis==3.5.3

**Platform**: CentOS Linux release 7.9.2009 (Core)

**Description**: Sometimes when receiving empty responses from the server, client throws List out of index error. Here is the trace
  `['Traceback (most recent call last):\n', ' File "/opt/proj/proj_source/lib/redis_client/redis_client_connetor.py", line 131, in redis_listener_worker\n for result in self.redis_pubsub.listen():\n', ' File "/usr/lib64/pypy2.7-v7.3.1/site-packages/redis/client.py", line 3605, in listen\n response = self.handle_message(self.parse_response(block=True))\n', ' File "/usr/lib64/pypy2.7-v7.3.1/site-packages/redis/client.py", line 3635, in handle_message\n message_type = nativestr(response[0])\n', 'IndexError: string index out of range\n']}}`

**Comment by Moshe-Bergwerk** [comment]
seeing this happen also with 3.5.3 when `health_check_interval` is enabled, and `parse_response()` returns None because of this:

```
        if conn.health_check_interval and \
                response == self.health_check_response:
            # ignore the health check message as user might not expect it
            return None
```

**Comment by davit555** [comment]
Guys any thoughts about the fix?
