### ISSUE TITLE
Connections leak in flask + celery application

### ISSUE THREAD

**Issue by ronlut** [redis/redis-py#1495]
**Version**: redis-py: 3.5.3; redis: 6.2.1
celery: 5.1.0 (kombu: 5.1.0)

**Platform**: python 3.8.8 on macos/ubuntu

**Description**: 
I'm experiencing a very strange problem with redis connections staying open for each request.
I am not sure the problem is in the redis client, but I hope to find a new clue here.

Reproducing the problem is quite simple:

tasks.py
```
import time
from celery import Celery

app = Celery('tasks', backend='redis://', broker='redis://', task_queue_max_priority=10)


@app.task
def sleep():
    time.sleep(1)
```

web.py
```
from flask import Flask
from tasks import sleep
app = Flask(__name__)

@app.route('/')
def hello_world():
    result = sleep.apply_async()
    result.wait()
    return '', 200

if __name__ == '__main__':
    app.run(port=4444)
```

simulate.py
```
import requests
for i in range(20):
    requests.get("http://localhost:4444")
```

1. `pip install celery[redis] requests flask`
2. Start redis
`docker run -p 6379:6379 --name redis redis`
3. Run celery `celery -A tasks worker --loglevel=INFO`
4. Run web server `python web.py`
5. connect to redis
```
docker exec -it redis /bin/bash
redis-cli
info Clients
```
Note the `connected_clients` number

6. simulate requests `python simulate.py`
7. Run `info Clients` again in redis-cli. 
Note the `connected_clients` number which is now a lot higher

Help will be super appreciated.
Running flask with `threaded=False` solves the issue.
Obviously this is a simplified reproduction code. Our real environment is gunicorn, eventlet, flask, redis, celery.

**Comment by andymccurdy** [comment]
The connections aren't leaked. They're hanging around in the redis-py connection pool that gets implicitly created when you don't pass one in.

The general approach is that if an existing connection is not available when the client needs it, a new connection will be created. After the client is finished with the connection, it is returned to the pool. Connections in the pool are left connected to the Redis server so that the next client that uses the connection doesn't have to wait for it to establish the TCP connection, authenticate, etc.

**Comment by ronlut** [comment]
Probably didn't explain myself good enough, sorry.
I understand the connection pool, this is obviously fine and correct.

But, it you run 100 requests you will have more than 100 connections open.
In production we are getting to a point of tens of thousands of open
connections, with about 10-50 requests per second.
This is probably a bug in celery, opened it there as well, but if you have
a clue I will be super glad to hear to try to fix that in celery.

Link to issue in celery: https://github.com/celery/celery/issues/6819

**Comment by andymccurdy** [comment]
I would want to see what the Celery maintainers say. Separately, have you looked at limiting the number of connections via the `max_connections` argument to the `ConnectionPool`?

**Comment by ronlut** [comment]
Hey @andymccurdy, sorry for the delay.
Someone commented on my issue in celery's repo and said setting max_connections doesn't help.

After digging a bit more, celery's backend property is stored in a thread-local storage, which means it is duplicated across threads from what I understand. This explains the fact that each request (thread) is opening a new connection pool I guess.

This also happens in eventlet (I guess) because eventlet patches threading.local as well.

**Comment by mostafa** [comment]
Hey @ronlut!

Have you managed to find a solution for this? I tried many different approaches, but to no avail. It behaves the same on the Flask app.
