### ISSUE TITLE
blpop raises TimeoutError exception

### ISSUE THREAD

**Issue by tisdall** [redis/redis-py#1570]
I'm not sure how this should be handled, but perhaps it's just a documentation issue.  When I tried using BLPOP I originally had looked at the Redis docs and it said that after the provided timeout it returns "nil".  When I looked at the [redis-py docs for blpop](https://redis-py.readthedocs.io/en/stable/#redis.Redis.blpop) it doesn't really mention what exactly it does when the timeout occurs so I assumed it would return `None`.

Perhaps all that's needed is a `:raises redis.exceptions.TimeoutError: error raised when timeout reached` added to the docstring?  (same issue probably exists on other methods that take a `timeout` arg)

**Comment by tisdall** [comment]
I haven't tested to confirm, but I believe the issue was that the `socket_timeout` was set to 2min but the call to `blpop` was done with a 5min timeout.  I'm also not sure if the behaviour changes in 4.0.0.  However, it would be nice if it gave a warning or something as the socket timeout raises an exception and the other timeout returns a `None`.  Something like "WARNING: timeout used in call to blpop was lower than the socket timeout and may lead to an exception being raised" (or even preventing a timeout that's larger than the socket timeout, as I can't think of a reason for doing that except that you like it giving an Exception instead of `None`)

**Comment by chayim** [comment]
@tisdall I think we'll close it. It might be reasonable to run a timeout check on a per-command basis, validating the timeout versus the socket timeout. I'll create that issue, so that we don't lose track.

Thanks again for all of this!
