### ISSUE TITLE
exception_handler missing pubsub/run_in_thread class

### ISSUE THREAD

**Issue by vijtad** [redis/redis-py#1571]
Here is the code snippet throwing error

  r = redisClient.pubsub()
  channel = 'TiffFileFailed'
  r.subscribe(**{ channel : handle_TiffFileFailed})
  r.run_in_thread(sleep_time=0.2, exception_handler=exception_handler)

22:37:57 webserver.1 |   File "/usr/src/app/server.py", line 200, in <module>
22:37:57 webserver.1 |     subscribe()
22:37:57 webserver.1 |   File "/usr/src/app/server.py", line 114, in subscribe
22:37:57 webserver.1 |     r.run_in_thread(sleep_time=0.2, exception_handler=exception_handler)
22:37:57 webserver.1 | TypeError: run_in_thread() got an unexpected keyword argument 'exception_handler'
22:37:57 webserver.1 | [2021-09-07 22:37:57 +0000] [12] [INFO] Worker exiting (pid: 12)
22:37:57 webserver.1 | [2021-09-07 22:37:57 +0000] [10] [INFO] Shutting down: Master
22:37:57 webserver.1 | [2021-09-07 22:37:57 +0000] [10] [INFO] Reason: Worker failed to boot.

**Comment by luhn** [comment]
`exception_handler` was added in https://github.com/andymccurdy/redis-py/commit/a404ad3dee93b3b0deb90b4075fd28734d78a282 and hasn't been released yet.

**Comment by chayim** [comment]
Closing - this is available in 4.0.0 beta releases and master.
