### ISSUE TITLE
Exception classes documentation is missing

### ISSUE THREAD

**Issue by manthanchauhan** [redis/redis-py#1577]
**Version**: redis-py = 3.0.1

**Platform**: Ubuntu 18.04.5 LTS 

**Description**: For each of the exception class mentioned in exceptions.py, I want to know what can be the possible causes. My goal is to implement a reversed write behind mechanism in case the application is unable to alter a particular key due the cluster being unavailable or mis-configured.

**Comment by chayim** [comment]
@manthanchauhan Have you thought have taking a look at [rgsync](https://github.com/RedisGears/rgsync). It's built on top of [RedisGears](https://github.com/RedisGears/RedisGears) and does exactly that.
