### ISSUE TITLE
Redis-py deadlocks during garbage collection

### ISSUE THREAD

**Issue by emorozov** [redis/redis-py#1583]
Problem is pretty serious and it seems that there're lots of people affected, including almost all (!) users of Celery, because it would attempt to connect to Redis even if you simply enabled Redis backend, and this will cause mysterious hangs several times a week.

More detailed description and tracebacks are in the pull request and related Celery pull request (initially I thought that the problem is caused by Celery code):
https://github.com/andymccurdy/redis-py/pull/1578

**Comment by emorozov** [comment]
Is there a way to ping maintainers to look at this bug? It's pretty serious and affects multiple people around the world (there're numerous complaints about mysterious celery hang ups).

If my solution is not acceptable, can I get a feedback? It's strange to have such a serious bug to be completely ignored.

**Comment by chayim** [comment]
Fixed by the PR mentioned above. Closing.
