### ISSUE TITLE
It stops to receive messages in pubsub

### ISSUE THREAD

**Issue by DiDHack** [redis/redis-py#1627]
Version of redis-py: 3.5.3 and 3.9.9 (from source)
Platform: Debian 9, Python 3.7.3, redis-server 5.0.3, django 2.2

that all is on the same server.

When django (two copy with some different settings) starts it connects to the redis and subscribe:

```
from redis.retry import Retry
from redis.backoff import ConstantBackoff
from .subscriptions import status, statistics
rc = redis.Redis(settings.REDIS_HOST, settings.REDIS_PORT, settings.REDIS_BASE_IDS['db'], decode_responses=True,
                 retry_on_timeout=True, retry=Retry(ConstantBackoff(5), 5))
rp = rc.pubsub(ignore_subscribe_messages=True)
rp.subscribe(**{'status': status, 'statistics': statistics})
thread = rp.run_in_thread(sleep_time=0.01, daemon=True)
```

A some small script publishes messages to the subscribers, for example:
```
rc.publish('status', json.dumps({
        'port': '3000',
        'status': 'activate',
    }))
```

It works fine a day, two days, one week. But in any case, one of subscribers just stops to receive messages without any errors then the second also stops to receive after some time (few hours or few days). But getting/setting from/to the redis works fine in the same time. Only subscribing stops to work. 

If I try to check subscribers in redis-cli by:
```
127.0.0.1:6379> PUBSUB NUMSUB status
1) "status"
2) (integer) 2
```
So it says that the redis have 2 subscribers.

I also try to publish message from cli:
```
127.0.0.1:6379> publish status '{"port": 3000, "status": "activate"}'
(integer) 2
```
Helps only restarting of django (resubscribe). I don't understand where search the problem. Maybe the thread (rp.run_in_thread) stops. I don't get any errors in log.

**Comment by chayim** [comment]
@DiDHack can you try with a newer version of redis? This could be an issue in redis itself, and there have been a tonne of improvements to pubsub since 5.0.

**Comment by DiDHack** [comment]
I'll try

**Comment by DiDHack** [comment]
I have updated redis-server to 6.2.6, testing.

**Comment by levrik** [comment]
@DiDHack Were you able to resolve this issue? I'm basically seeing the same but only on an environment that's under higher load. On staging there are no issues at all.
