### ISSUE TITLE
Tests need to be properly limited.

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#1628]
The following tests fail, when run against redis 6. This points to a need to revisit our current test layout. Ideally tests would be skipped, or functions split such that dedicated tests would be skipped.

=================================================================== short test summary info ===================================================================
FAILED tests/test_commands.py::TestRedisCommands::test_zrange - redis.exceptions.ResponseError: syntax error
FAILED tests/test_commands.py::TestRedisCommands::test_zrangebylex - redis.exceptions.ResponseError: value is not an integer or out of range
FAILED tests/test_commands.py::TestRedisCommands::test_zrevrangebylex - redis.exceptions.ResponseError: value is not an integer or out of range
FAILED tests/test_commands.py::TestRedisCommands::test_zrangebyscore - redis.exceptions.ResponseError: syntax error
FAILED tests/test_commands.py::TestRedisCommands::test_zrevrange - redis.exceptions.ResponseError: syntax error
FAILED tests/test_commands.py::TestRedisCommands::test_zrevrangebyscore - redis.exceptions.ResponseError: syntax error
FAILED tests/test_commands.py::TestRedisCommands::test_georadius_count - redis.exceptions.ResponseError: syntax error
FAILED tests/test_commands.py::TestRedisCommands::test_georadiusmember - redis.exceptions.ResponseError: syntax error
ERROR tests/test_scripting.py::TestScripting::test_eval - redis.exceptions.ResponseError: Unknown subcommand or wrong number of arguments for 'FLUSH'. Try S...
ERROR tests/test_scripting.py::TestScripting::test_script_flush - redis.exceptions.ResponseError: Unknown subcommand or wrong number of arguments for 'FLUSH...
ERROR tests/test_scripting.py::TestScripting::test_evalsha - redis.exceptions.ResponseError: Unknown subcommand or wrong number of arguments for 'FLUSH'. Tr...
ERROR tests/test_scripting.py::TestScripting::test_evalsha_script_not_loaded - redis.exceptions.ResponseError: Unknown subcommand or wrong number of argumen...
ERROR tests/test_scripting.py::TestScripting::test_script_loading - redis.exceptions.ResponseError: Unknown subcommand or wrong number of arguments for 'FLU...
ERROR tests/test_scripting.py::TestScripting::test_script_object - redis.exceptions.ResponseError: Unknown subcommand or wrong number of arguments for 'FLUS...
ERROR tests/test_scripting.py::TestScripting::test_script_object_in_pipeline - redis.exceptions.ResponseError: Unknown subcommand or wrong number of argumen...
ERROR tests/test_scripting.py::TestScripting::test_eval_msgpack_pipeline_error_in_lua - redis.exceptions.ResponseError: Unknown subcommand or wrong number o...

**Comment by dogukanteber** [comment]
Hello @chayim. I would like to work on that. However, I have a question: Why do we need to skip these tests?
