### ISSUE TITLE
Migrate from flake8 to black

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#1644]
Currently in redis-py we rely on flake8 for lint checking. The goal in migrating to [black](https://github.com/psf/black) is to enforce opinionated, community-driven code formatting, that is PEP 8 compliant. 

- [ ] Changing our tox linter to run black locally, so that changes can be examined prior to commit
- [ ] Enabling a pre-commit check with github hooks, for the local repo, so that ideally nothing is committed that doesn't pass black.
- [ ] Changing our github action to run black checks (i.e fail when black generates changes)

**Comment by chayim** [comment]
@WisdomPill Any idea when you think you'd like to attack this?

**Comment by WisdomPill** [comment]
Hello, sorry, I did not have much free time in the past weekends, I should be able to work on it the next weekend, if there is somebody that is sure could work on it I do not mind stepping back

**Comment by chayim** [comment]
@WisdomPill all good! Let's see where you end up - I'd love you to contribute if you're up to it and have that time! If it's post next-weekend as you've said, let's revisit.  Nothing is burning.
