### ISSUE TITLE
4.0.0rc1 breaks various zrange commands on older servers

### ISSUE THREAD

**Issue by bmerry** [redis/redis-py#1669]
**Version**: redis-py 4.0.0rc1, redis 6.0.16 (or any less than 6.2).

**Platform**: Python 3.8, Ubuntu 20.04

**Description**:

Previously calling `zrevrange` or `zrange(..., desc=True)` would use ZREVRANGE on the wire. Somewhere between 4.0.0b1 and 4.0.0rc1 this changed to use `ZRANGE ... REV`, which is new syntax in Redis 6.2. When using an older server this causes a syntax error.

To reproduce:
```python
import redis
r = redis.Redis('localhost')
r.zrevrange('foo', 0, -1)
```

Other commands are also affected e.g. zrangebyscore and zrangebylex are also using ZRANGE with options on the wire which is not supported pre-6.2.

**Comment by bmerry** [comment]
@chayim looks like this was broken by #1603.

**Comment by chayim** [comment]
Thanks @bmerry for tracking this down all the way. We'll definitely get this into rc2!  @AvitalFineRedis while we're here, let's test for this case.

**Comment by bmerry** [comment]
@chayim the following is still broken in 4.0.0rc2 (but worked in 3.5.3):
```
import redis
r = redis.Redis('localhost')
r.zrange('foo', 0, -1, desc=True)
```

**Comment by chayim** [comment]
@AvitalFineRedis can you add a test with this specific case? Our 6.0.0 testing didn't seem to cover this.

@bmerry thanks again, for highlighting this.
