### ISSUE TITLE
Commands with a timeout should warn

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#1704]
For redis commands that explicitly specify a timeout - **perhaps** we should validate that the timeout specified, is shorter than the socket timeout.  This suggestion comes as a result of #1570.

**Comment by matthewhughes934** [comment]
Hi, I'd be interested in tackling this issue if possible.

I had a brief look around and had some questions about implementing this: For example for `blpop` https://github.com/redis/redis-py/blob/82bad1686177c4c543818a8bfac35c6fdfc9ddf1/redis/commands/core.py#L1752 when would be best to check the connection timeout? Would we wait until we've got the connection to use in `execute_command` or would it be sufficient to inspect the connection args before this point (though there might be a risk here in case the connection args and the actual socket's timeout can go out-of-sync in its lifetime).
