### ISSUE TITLE
Link commands to redis commands

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#1712]
Currently, the commands in redis-py (core, etc) have command definitions, and docstrings, but it would be great, if we could add links to the individual redis command documentation, on redis.io.

This is a lot of work!

**Comment by Carlosbogo** [comment]
Hi, I would like to help with this, but I haven't worked on this repository before. Should I do it for all the commands in the redis-py/redis/commands folder or are there more in other folders?

**Comment by chayim** [comment]
@Carlosbogo Thank you! That about be *amazing*!  I started changes [here](https://github.com/redis/redis-py/pull/1711) but I'd happily turn it over to you.  We'd be talking, ultimately about anything in commands/core.py, and the module directories (commands/json/commands.py, commands/search/commands.py, etc).   

If you're feeling up to it, I'd love to assign this to you. Say the word, and it's yours!

**Comment by Carlosbogo** [comment]
What are the files that still need to be changed? I don't know if I'll be able to do it for all of them but I hope I'll at least be able to help.

**Comment by chayim** [comment]
That's more than I can ask, thank you so much! I assigned it to the two of us, so that we can work on it together even.   

If you touch redis/commands/core.py and pretty much search for any function with an execute_command.py we should be good to go. One such example is acl_cat in core.py, and the resulting redis command is https://redis.io/commands/acl-cat.

Any amount of assistance is very much appreciated! 

One such example is
