### ISSUE TITLE
4.0.0 makes Memorystore unusable

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [redis/redis-py#1716]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on? 4.0.0 - 6.x

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure) GCP Python 3.9

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
When using 4.0.0 managed Redis has lower than 1/4th of throughput. We see 200% CPU usage and huge ammounts of COMMANDs being sent.
Reverting to 3.5.3 fixes the issue.

**Comment by chayim** [comment]
@AndreasBergmeier6176 Any chance you can provide some sample code, or even a dump of what happened?

**Comment by AndreasBergmeier6176** [comment]
Basically we have a connection pool, create a connection out of that, get a value by key, modify the value and write it back by key. And all that ~5k per second.

**Comment by filipecosta90** [comment]
Hi there @AndreasBergmeier6176, we've tried to mimic the issue with the following code:

```
#!/usr/bin/env python3
import pyperf
from redis import Redis, BlockingConnectionPool

# ------------------------------------------------------
# benchmark definitions
# ------------------------------------------------------


def pool_get_connection(pool):
    conn = pool.get_connection("GET")
    pool.release(conn)

def pool_get_connection_get_set(pool, key):
    conn = pool.get_connection("GET")
    conn.send_command("GET", key)
    value = conn.read_response()
    conn.send_command("SET", key, value)
    conn.read_response()
    pool.release(conn)


def redis_get_set(redis_conn, key):
    value = redis_conn.get(key)
    redis_conn.set(key, value)


# ------------------------------------------------------
# benchmark runner
# ------------------------------------------------------

runner = pyperf.Runner()
pool = BlockingConnectionPool()
redis_conn = Redis(connection_pool=pool)
key = "key"
value = "value"
redis_conn.set(key, value)

runner.bench_func("BlockingConnectionPool_get_connection()", pool_get_connection, pool)

runner.bench_func(
    "BlockingConnectionPool_get_connection()_get()_set()",
    pool_get_connection_get_set,
    pool,
    key,
)
runner.bench_func("Redis_get()_set()", redis_get_set, redis_conn, key)
```

and noticed that 3.5.3 and 4.0.0 produce the same execution time:

## 3.5.3:
```
root@hpe10:~# python3 bench.py -n 10 -o 3.5.3.json
.....................
BlockingConnectionPool_get_connection(): Mean +- std dev: 7.62 us +- 0.10 us
.....................
BlockingConnectionPool_get_connection()_get()_set(): Mean +- std dev: 52.0 us +- 1.1 us
.....................
Redis_get()_set(): Mean +- std dev: 68.3 us +- 1.6 us
```

## 4.0.0:
```
root@hpe10:~# python3 bench.py -n 10 -o 4.0.0.json
.....................
BlockingConnectionPool_get_connection(): Mean +- std dev: 7.33 us +- 0.09 us
.....................
BlockingConnectionPool_get_connection()_get()_set(): Mean +- std dev: 51.4 us +- 1.1 us
.....................
Redis_get()_set(): Mean +- std dev: 70.7 us +- 1.8 us
```

Can you provide us with your snippet of code that's doing the conn acquiring, get, set, and release? So we can test this further.

**Comment by gkorland** [comment]
@AndreasBergmeier6176 can you please retest with 4.0.1?

**Comment by AndreasBergmeier6176** [comment]
> @AndreasBergmeier6176 can you please retest with 4.0.1?

Will try to get it in this week.

**Comment by chayim** [comment]
@AndreasBergmeier6176 Light ping. Any luck?

**Comment by AndreasBergmeier6176** [comment]
> Light ping. Any luck?

Not yet. Will probably not happen this week.
