### ISSUE TITLE
Discussion: Do we embrace type hints?

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#1717]
Code completion in VSCode (possibly other IDEs) does not work in redis-py 4.0.0 for module commands within the json, ft, ts (and future module?) spaces. For those interested, apparently it does work in PyCharm.

**Comment by chayim** [comment]
This appears to be a bug specific to vscode. It looks like the python language server uses mypy stubs (or something similar) under the hood. The latest updates in [types-redis](https://pypi.org/project/types-redis/) haven't been updated for redis-py 4.x, at least with the language server version 2021.11.1.

Completion only works with commands that were already released in redis 3.5.3. This was validated by trying new commands such as **smismember**, even modifying the classes within the decidated virtualenv.  After modifying the contents of the virtualenv, it also fails to accept changes. Yet, going to definitions and the like continue to work.

This is further evident by pop text for set (as an example) having the docstring comments from redis 3.5.3 as opposed to latest. 

Leaving open, in case someone knows how to fix this, and finds it useful. Similarly, A contribution to [python/typeshed](https://github.com/rpython/typeshed) probably fixes this.

**Comment by chayim** [comment]
Tried a hand at sending [this PR](https://github.com/python/typeshed/pull/6335) to typeshed.

**Comment by chayim** [comment]
It turns out that if you add **generated stubs** to your python package, VSCode still doesn't pick those up either. So... community vote, is it worth caring about? I view this as a VSCode issue, but I feel (awful) about the developer experience.

The alternative is to start adding [type hints](https://www.python.org/dev/peps/pep-0484/) everywhere.  

To vote: :+1: for add stubs (automatically, no editiing)

**Comment by tiptenbrink** [comment]
I get no code completion on the newest version of PyCharm for the commands module.

**Comment by SantjagoCorkez** [comment]
The stubs within `typeshed` have nothing in common with type hinting. In general even the simplest python-capable editors are able to unwind class declarations so a user knows class names and their methods names and their explicitly declared argument names. The stubs provide nothing beyond this. All those class attributes and instance properties marked as `: Any`... That is the problem, not a hypothesis of `some editor wouldn't show method names for a class`.

As soon as type hints tie certain classes with the variables and/or methods args and return values the public API probllem goes.

A bad type hints stub:
```python
class A:
  CLASS_ATTR: Any
  a: Any
  b: Any

  def __init__(self, a, b):...
  def make_smth(self, c):...
```

A good type hints stub:
```python
class A:
  CLASS_ATTR: int
  a: Optional[Union[str, bytes]]
  b: bool

  def __init__(self, a: Optional[Union[str, bytes]], b: bool):...
  def make_smth(self, c: OtherClass) -> 'A':...
```

Also, some editors accept the stubs' priority in showing docstrings so moving or duplicating docstrings in stubs could be a good move.

**Comment by chayim** [comment]
The py.typed marker is missing because we're not completely there yet.  CI needs to add support for mypi testing *and*, completion of type hints. 

IMHO we can safely close this off now - and instead add issues for those.

**Comment by chayim** [comment]
Closing. We're clearly going down this path.
