### ISSUE TITLE
No module named 'redis._compat'

### ISSUE THREAD

**Issue by overbost** [redis/redis-py#1718]
Latest release cause the error described in subject.

**Version**: What redis-py and what redis version is the issue happening on?
latest version of redis-py 4.0.0

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Ubuntu 18.04 Python 3.8

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
```
ModuleNotFoundError: No module named 'redis._compat'
from redis._compat import urlparse
from flask_rq import get_worker
```

I have the same issue described here https://github.com/RedisJSON/redisjson-py/issues/67.
Solved by downgrading redis-py from 4.0.0 to 3.5.*

```
(venv) ❯ pip3 list | grep redis                                                
flask-redis        0.4.0    
hiredis            2.0.0    
redis              4.0.0
```

**Comment by chayim** [comment]
Hi @overbost thanks for pointing this out - but redis._compat was intentionally removed a year and a bit back. If your underlying dependencies aren't yet ready for redis 4.0.0, I recommend pinning yours to 3.5.3.

Unfortunately, this is a **won't fix**. It's intentional.

**Comment by overbost** [comment]
Thank you!

i switched flask_rq with flask_rq2.

flask_rq is not developed anymore and not compatible with newer version of redis_py
