### ISSUE TITLE
Custom connection class overriden by redis uri 

### ISSUE THREAD

**Issue by m-novikov** [redis/redis-py#1739]
It not possible to pass custom connection class via kwargs if redis uri starts with `rediss://` (secure connection) or `unix://`

**Version**:  3.5.3
**Platform**: pyton3.9, fedora

**Description**: 

Here are tests to reproduce. Discussion in https://github.com/aio-libs/aioredis-py/issues/1209 implies that it's intentional, but I am not sure if this is expected behavior.

```python
import pytest
from redis import connection, from_url


@pytest.mark.parametrize("proto,ConnBase", [
    ("rediss", connection.SSLConnection), 
    ("unix", connection.UnixDomainSocketConnection),
])
def test_custom_connection_class_connection_pool(proto, ConnBase):
    class MyConn(ConnBase):
        pass

    pool = connection.ConnectionPool.from_url(
        url=f"{proto}:///tmp/redis.sock", connection_class=MyConn,
    )
    conn = pool.make_connection()
    assert isinstance(conn, MyConn)


@pytest.mark.parametrize("proto,ConnBase", [
    ("rediss", connection.SSLConnection), 
    ("unix", connection.UnixDomainSocketConnection),
])
def test_from_url_custom_connection_class(proto, ConnBase):
    class MyConn(ConnBase):
        pass

    redis = from_url(
        url=f"{proto}://127.0.0.1", connection_class=MyConn,
    )
    conn = redis.connection_pool.make_connection()
    assert isinstance(conn, MyConn)
```
Related issue in aioredis-py https://github.com/aio-libs/aioredis-py/issues/1209

**Comment by adiberk** [comment]
Second this.  This is a huge issue.  If I would like to use SSL connection.  the from_url method will essentially prevent this!

**Comment by chayim** [comment]
Given what we currently have for connections - I think this makes sense.
Note, I generally think we probably should do a bit of a rethink on connections and add environments to support multiple test scenarios, but we're not there yet.

I'm going to merge this into 4.1.0rc2 - and I back-issued a tracker for environments.
