### ISSUE TITLE
Add SSL Environments for Testing

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#1767]
Sometimes we receive great Pull Requests that are SSL specific, and rather than test variable setting - it would be nice if we took a page from [jedis](https://github.com/redis/jedis) and validated the SSL implementations with true integration.

This is an outcome of #1739 and generally makes sense for the future.

**Comment by m-novikov** [comment]
@chayim could you clarify the scope of this task?

I see the following steps:
1. Generate certificates to use with redis.
2. Add additional redis entry to the `tox.ini` file with config using certificates
3. Add tests following similar pattern to the https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/tests/SSLJedisTest.java

Is this sufficient?

**Comment by chayim** [comment]
@m-novikov I think that's a great start. There are so many different combinations of SSL changes - that I'd view this as a great start. My request would be that ssl tests start in a test_ssl.py file (within the tests folder).

Over time, I would 100% plan on expanding - but you're looking at a great place to start! Want to tackle it?

**Comment by m-novikov** [comment]
Yep :) I'll try to make a draft PR within couple of weeks, then.

**Comment by chayim** [comment]
@m-novikov I've started down this path because of bug #1757 - since I won't merge this otherwise! Do you mind if I finish it off?  I'd *love* to have your help on the PR if I get that far - I'm hoping to be done early next week.  Please don't hate me!

**Comment by m-novikov** [comment]
Awesome :) Thanks
