### ISSUE TITLE
4.0 json support ?

### ISSUE THREAD

**Issue by devbrian** [redis/redis-py#1777]
**Version**: 4.0.2

**Platform**:  Windows 11

**Description**:  I want to use redis to store json objects.  I was initially looking at redisJSON, but they noted as of redis-py 4.0, this library supports json.    I have a redis server running via docker using `redislabs/rejson:latest`

```
import redis
from redis.commands.json.path import Path
from redis import exceptions
from redis.commands.json.decoders import unstring, decode_list

r = redis.Redis()
d = {"hello": "world", b"some": "value"}
r.json().set("somekey", Path.rootPath(), d)
```

I am attempting to load a json object the same way it is done in the tests for this library, however, I am met with this error -

```
TypeError: keys must be str, int, float, bool or None, not bytes
```

What am I missing?

**Comment by chayim** [comment]
Hi @devbrian I think you're going to want to pass decode_keys=True to your connection, and having initialized your redis connection with _decode_responses=True_.  Here's the [unit test](https://github.com/redis/redis-py/blob/18c6809b761bc6755349e1d7e08e74e857ec2c65/tests/test_json.py#L18) that shows that example, and it makes use of the connection defined [here](https://github.com/redis/redis-py/blob/18c6809b761bc6755349e1d7e08e74e857ec2c65/tests/conftest.py#L233).

```
r = redis.Redis(decode_responses=True)
d = {"hello": "world", b"some": "value"}
r.json().set("somekey", Path.rootPath(), d, decode_keys=True)
```
