### ISSUE TITLE
Request: Continue serving the last 3.x release from readthedocs as "3.x-line" or similar

### ISSUE THREAD

**Issue by sirosen** [redis/redis-py#1816]
I have codebases in which we're using 3.5.3 and which I want to upgrade to 4.x .
However, right now readthedocs is not serving the 3.x docs for redis-py. This makes it harder for me to evaluate what our current code is doing, how to work with it, and how to update it for 4.x .

"Obviously", anyone running 3.x versions of redis-py will want to move to 4.x, but it won't be quick and easy for everyone.
Having the 3.x docs still served for a (long) while will still be useful to me and others.

If a new branch "3.x" is created at the last 3.x tag, that would work. I've personally used the `-line` suffix in the past, as in `3.x-line`, but preferences on this vary.

Is there any interest in doing this? I don't know if it can be done via `.readthedocs.yml` config. I've only ever managed it via the admin interface for readthedocs.org .

**Comment by chayim** [comment]
Hi @sirosen I've exposed the 3.5.3 docs on readthedocs by rebuilding what was in that branch, though it will be listed a **3.5.3** rather than **v3.5.3**.

I'll close this accordingly - but please feel free to reopen.
