### ISSUE TITLE
Question: resolving hostname when retry on connection timeout

### ISSUE THREAD

**Issue by ugatenio** [redis/redis-py#1833]
I wonder if Redis client resolve again the hostname if connection timeout occurred while setting `retry_on_timeout=True`.
I'm asking since sometime the mapping between hostname to ip can be invalid since the DNS changed the mapping.

**Comment by barshaul** [comment]
Yes,
By setting retry_on_timeout=True, when timeoutError is thrown, the client disconnects its current connection and creates a new one. Upon creating a new connection, the hostname is resolved again.

To retry on other errors too, you can use the new argument `retry_on_error` and pass other error types in a list.

**Comment by ugatenio** [comment]
@barshaul thanks for the replay.
Another question - how many retries and what is the delay between each retry?

**Comment by barshaul** [comment]
If you don't pass a Retry instance using the client's 'retry' argument, it will create a default one for you. The default Retry object has 1 retries and NoBackoff() strategy.

Here's more info about the Retry / Backoff strategies: 

- Backoff base class has four backoff strategies based on https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/. see ConstantBackoff, NoBackoff, ExponentialBackoff, FullJitterBackoff.
- Retry class is constructed from a backoff strategy and a maximum number of retries

Example how to create a client with retry object:

```
from redis.backoff import ExponentialBackoff
from redis.retry import Retry
from redis.client import Redis
from redis.exceptions import (
    BusyLoadingError,
    ConnectionError,
    TimeoutError
)

retry = Retry(ExponentialBackoff(), 3) // Run 3 retries with exponential backoff strategy 
r = Redis(host='localhost', port=6379, retry=retry, retry_on_error=[BusyLoadingError, ConnectionError, TimeoutError])
r_only_timeout = Redis(host='localhost', port=6379, retry=retry, retry_on_timeout=True)
```

**Comment by ugatenio** [comment]
@barshaul Thank you!

**Comment by ugatenio** [comment]
@barshaul I tried to solution you suggested and it's not working when trying to connect to the server.
by reading the code I saw that the retry mechanism only apply at the command execution level and not when trying to connect to the server.

any suggestion?

**Comment by barshaul** [comment]
Thank you @ugatenio for catching that, you're right.
 I have created a new PR (#1895) to support retrying when connecting to the server.
