### ISSUE TITLE
socket connection method has huge latency Any help?

### ISSUE THREAD

**Issue by MXP0** [redis/redis-py#1834]
trying to make something like Alexa, but takes 25 seconds each time to register what i am saying. Did some profiling and found the reasons below as to why there taking so long (method 'connect' of '_socket.socket' objects). Any help?

801 function calls (7681 primitive calls) in 24.856 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2   21.030   10.515   21.030   10.515 {method 'connect' of '_socket.socket' objects}
      131    3.046    0.023    3.046    0.023 {built-in method _portaudio.read_stream}
        2    0.361    0.180    0.361    0.180 {built-in method _portaudio.initialize}
        3    0.347    0.116    0.347    0.116 {method 'recv_into' of '_socket.socket' objects}
        1    0.019    0.019    0.019    0.019 {built-in method _socket.getaddrinfo}
        1    0.013    0.013    0.013    0.013 {built-in method _portaudio.close}
        1    0.009    0.009    0.009    0.009 {built-in method _portaudio.open}
        1    0.007    0.007    0.007    0.007 {method 'write' of '_io.BufferedWriter' objects}
        1    0.006    0.006    0.006    0.006 {method 'read' of '_io.TextIOWrapper' objects}
        2    0.004    0.002    0.004    0.002 {built-in method _winapi.CreateProcess}
       52    0.002    0.000    0.002    0.000 {built-in method nt.stat}
        1    0.001    0.001    3.048    3.048 C:\Users\m3pot\AppData\Local\Programs\Python\Python39\lib\site-packages\speech_recognition\__init__.py:579(listen)
        2    0.001    0.000    0.001    0.000 {built-in method _winapi.WaitForSingleObject}
        5    0.001    0.000    0.001    0.000 {method 'acquire' of '_thread.lock' objects}
        3    0.001    0.000    0.001    0.000 {built-in method io.open_code}
        6    0.001    0.000    0.001    0.000 {method 'write' of '_io.TextIOWrapper' objects}
        6    0.001    0.000    0.001    0.000 {method 'flush' of '_io.TextIOWrapper' objects}
        1    0.001    0.001    0.001    0.001 {built-in method _imp.create_dynamic}
      131    0.000    0.000    3.046    0.023 C:\Users\m3pot\AppData\Local\Programs\Python\Python39\lib\site-packages\speech_recognition\__init__.py:160(read)
      131    0.000    0.000    0.000    0.000 {built-in method audioop.rms}
      131    0.000    0.000    3.046    0.023 C:\Users\m3pot\AppData\Local\Programs\Python\Python39\lib\site-packages\pyaudio.py:589(read)
       67    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap_external>:91(_path_join)
  687/657    0.000    0.000    0.000    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0.000 {built-in method _portaudio.stop_stream}
        2    0.000    0.000    0.000    0.000 {method 'sendall' of '_socket.socket' objects}
       10    0.000    0.000    0.000    0.000 C:\Users\m3pot\AppData\Local\Programs\Python\Python39\lib\urllib\request.py:436(add_handler)
     17/4    0.000    0.000    0.000    0.000 C:\Users\m3pot\AppData\Local\Programs\Python\Python39\lib\sre_parse.py:493(_parse)
        1    0.000    0.000    0.000    0.000 {built-in method _portaudio.start_stream}
        3    0.000    0.000    0.000    0.000 {built-in method marshal.loads}
       13    0.000    0.000    0.000    0.000 {built-in method _winapi.CloseHandle}
     30/4    0.000    0.000    0.000    0.000 C:\Users\m3pot\AppData\Local\Programs\Python\Python39\lib\sre_compile.py:71(_compile)
       10    0.000    0.000    0.000    0.000 {method 'join' of 'bytes' objects}
        7    0.000    0.000    0.000    0.000 {method 'read' of '_io.BufferedReader' objects}
        4    0.000    0.000    0.000    0.000 {method 'write' of '_io.BytesIO' objects}
       14    0.000    0.000    0.001    0.000 <frozen importlib._bootstrap_external>:1505(find_spec)
        1    0.000    0.000    0.000    0.000 {built-in method sys.getwindowsversion}
        1    0.000    0.000    0.000    0.000 C:\Users\m3pot\AppData\Local\Programs\Python\Python39\lib\distutils\version.py:31(Version)

**Comment by chayim** [comment]
Hi @MXP0 thanks for your bug report.

Can you share your connect code, your version of redis-py, as well as your version of redis? What's your target: a cluster, a standlone node?

**Comment by MXP0** [comment]
> Hi @MXP0 thanks for your bug report.
> 
> Can you share your connect code, your version of redis-py, as well as your version of redis? What's your target: a cluster, a standlone node?

im not really sure how i check any of that unfortunately, how do  i do that?
