### ISSUE TITLE
`redis.Redis` is no longer documented, only `redis.client.redis`

### ISSUE THREAD

**Issue by Zac-HD** [redis/redis-py#1839]
We noticed this because the docs build for Hypothesis now warns that our intersphinx link to `redis.Redis` no longer resolves.

Is this change intentional and importing from `redis.client` now best-practice?  If so, a mention in the release notes would be helpful!  If not, it would be great to document the shorter alias again 😁

**Comment by chayim** [comment]
@Zac-HD just to make sure [is this the project](https://hypothesis.readthedocs.io/en/latest/)?  redis.Redis is definitely the right thing to import, though the files have been in redis.client for ... as long as I've been involved.

It looks like by expanding documentation for 4.1.0 we inadvertently broke yours. Can you pass me a link - or something we can look at?

**Comment by Zac-HD** [comment]
That's right; [this docstring](https://github.com/HypothesisWorks/hypothesis/blob/a583d36ddea7b0f5eb0d21a07abca7d155335e3f/hypothesis-python/src/hypothesis/extra/redis.py#L22) ends up on [this page of our docs](https://hypothesis.readthedocs.io/en/latest/database.html?highlight=redis.Redis#hypothesis.extra.redis.RedisExampleDatabase) (and [here's a failing CI build](https://github.com/HypothesisWorks/hypothesis/runs/4657300352?check_suite_focus=true#step:6:1462)).

Sounds like this is just a Sphinx config thing then; changing `.. autoclass:: redis.client.Redis` to `.. autoclass:: redis.Redis` might even be sufficient?

**Comment by chayim** [comment]
@Zac-HD Perfect, thank you for the pointers. Unfortunately this would be going into master so it would appear in **latest** rather that **stable**.  I'll cross-link the PR that closes this.
