### ISSUE TITLE
Help conda After the installation is complete, run alert No module named 'redis'

### ISSUE THREAD

**Issue by xcdiv** [redis/redis-py#1840]
Help 

**Version**: 
=============================================
>>>conda install redis-py

>>>message:
## Package Plan ##
 
    - redis-py
   
The following NEW packages will be INSTALLED:

  deprecated         anaconda/cloud/conda-forge/noarch::deprecated-1.2.13-pyh6c4a22f_0
  redis-py           anaconda/cloud/conda-forge/noarch::redis-py-4.0.2-pyhd8ed1ab_0
  wrapt              anaconda/cloud/conda-forge/linux-64::wrapt-1.13.3-py39h3811e60_1

>>>conda install redis

>>>message:
The following NEW packages will be INSTALLED:

  redis              anaconda/pkgs/main/linux-64::redis-5.0.3-h7b6447c_0 

**Platform**: What platform / Python 3.9.9 centos 7)

**Description**: 
Run in python ：

import redis
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-1fa5a3a95ebb> in <module>
----> 1 import redis

ModuleNotFoundError: No module named 'redis'

**Comment by xcdiv** [comment]
Jupyter and Conda in python's multi-version default environment version calls have cross calls, which have been fixed from the configuration

**Comment by chayim** [comment]
@xcdiv I'm curious - is there a way we can build a conda package and test from our build system?  I'm happy to have us push up to conda-forge.
