### ISSUE TITLE
Can not install Redis-Py v4.1.0 in Alpine Linux 3.15

### ISSUE THREAD

**Issue by rashley-iqt** [redis/redis-py#1869]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
Redis-Py v4.1.0 and Redis 6.2.6

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python 3.9.7-r4 on Alpine Linux 3.15 in Docker

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
Error Message:
```
Attempting uninstall: packaging
    Found existing installation: packaging 20.9
ERROR: Cannot uninstall 'packaging'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

The `requirements.txt` file does not specify a version for the dependency on `packaging` and is implicitly defaulting to latest. this prevents installation in environments where packaging has been installed as part of the OS

To reproduce:
1. clone [this repo](https://github.com/IQTLabs/packet_cafe.git)
1. `git checkout renovate/redis-4.x`
1. cd into the `web` directory
1. `docker build .`

**Comment by chayim** [comment]
This change: https://github.com/redis/redis-py/commit/1fc1233ffd9e925ecfb7d9ad83a9641a03508985 should solve part of the issue.

However I've added a PR to close this as well.
