### ISSUE TITLE
[Docs] Docs for `timeseries` commands seem to be incorrect

### ISSUE THREAD

**Issue by dpipemazo** [redis/redis-py#1875]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?

4.1.0

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

Docs

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

The [documentation](https://redis-py.readthedocs.io/en/stable/redismodules.html) for the `timeseries` module commands seems to be incorrect. If one tries to follow the example:

```
import redis
r = redis.Redis()
r.timeseries().create(2, retension_msecs=5)
```

An AttributeError is thrown saying `redis` does not have attribute `timeseries`.

After looking at the source and testing a bit, it seems the below is the right way to do it

```
import redis
r = redis.Redis()
r.ts().create(2, retension_msecs=5)
```

The docs should likely be updated if this is correct. Thanks!

**Comment by chayim** [comment]
@dpipemazo you're absolutely right. Thank you very much. Merging.
