### ISSUE TITLE
Add support for GETDEL

### ISSUE THREAD

**Issue by BSVogler** [redis/redis-py#1882]
Command supported since Redis 6.2
[Redis Docs](https://redis.io/commands/getdel)

**Comment by chayim** [comment]
Hi @BSVogler Perhaps you missed [this command](https://github.com/redis/redis-py/blob/f0c0ab24e8b1a98fcc1e6bc7cc5c6ecfcd75da85/redis/commands/core.py#L1235) in the core?

Here's the [associated test](https://github.com/redis/redis-py/blob/f0c0ab24e8b1a98fcc1e6bc7cc5c6ecfcd75da85/tests/test_commands.py#L1031).

Both are available in the latest release.

**Comment by BSVogler** [comment]
Sorry I seem to have problems with my local installation.
