### ISSUE TITLE
Link in the main page is broken

### ISSUE THREAD

**Issue by dogukanteber** [redis/redis-py#1896]
In the main [page](https://redis-py.readthedocs.io/en/stable/), ``` After that, you probably want to run redis commands.``` text has a broken link. It redirects the user to this [link](https://redis-py.readthedocs.io/en/stable/redis_core_commands.html) but the resulting page has this error: ```This page does not exist yet```

**Comment by dvora-h** [comment]
Hi @dogukanteber 
Thanks for reporting this issue, i fixed it here #1897
