### ISSUE TITLE
Redis 7.0 functions support

### ISSUE THREAD

**Issue by academe-01** [redis/redis-py#1933]
Hi,
is there any plans to add support for redis functions?

https://redis.io/topics/functions-intro

**Comment by gkorland** [comment]
See: https://github.com/redis/redis-py/issues/1813

**Comment by chayim** [comment]
@academe-01 #1813 doesn't cover all of our missing commands, I'm refreshing the list as more have entered unstable. But yes - we'd like the 4.2.0 release to include FCALL, FCALL_RO and friends. Interested in working on a PR?
