### ISSUE TITLE
Add support for SUNSUBSCRIBE

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#1943]

**Comment by bellatoris** [comment]
Is there any plans to move forward with this issue?

**Comment by chayim** [comment]
@bellatoris absolutely, as part of the RESP3 work @dvora-h is working on right now.  Are you interested in helping out on that branch :D ?

**Comment by bellatoris** [comment]
Sure, please let me know that branch, I will see what I can do to help.

**Comment by dvora-h** [comment]
@bellatoris 5.0.0b4 released today and supports sharded pubsub (sync)
