### ISSUE TITLE
Mismatched commands typing

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [redis/redis-py#2012]
Pinging @dvora-h @chayim 

Not all the commands use the proper typing (e.g. `linsert`) which uses KeyT and EncodingT; KeyT for instance is a union of str, bytes, and memoryview but the current typing for something like linsert only works with str. Just creating an issue for future reference: https://github.com/aio-libs/aioredis-py/blob/19be499015a8cf32580e937cbfd711fd48489eca/aioredis/client.py#L2195-L2205

**Comment by chayim** [comment]
Thanks for the reminder @Andrew-Chen-Wang for the reminder!
