### ISSUE TITLE
graph commands explain raise TypeError again.

### ISSUE THREAD

**Issue by ChandlerBent** [redis/redis-py#2033]
redis version: redis-4.1.4

#1848

This bug should fix in #1901.

Another pr #1993 overwrite it...

So the bug still unresolved

**Comment by dvora-h** [comment]
@ChandlerBent Thank you for reporting this bug again!

**Comment by MattAlp** [comment]
I'm afraid that this is happening again. Same example as above for a different query, `redis_object_instance.execute_command` with `EXPLAIN` works fine as described in the original issue and returns a list of bytestrings.
