### ISSUE TITLE
Failing to access features from the now depricated redistimeseries

### ISSUE THREAD

**Issue by dilonne** [redis/redis-py#2049]
**Version**:  4.14

**Platform**: Python 3.8.3 on MacOS Big Sur

**Description**: According to https://github.com/RedisTimeSeries/redistimeseries-py#user-content-deprecation-notice The features from redistimeseries package have merged into the redis-py module, however we are failing to run such commands using the package version stated above. 

Steps to  reproduce the error

import redis
r = redis.Redis(host='localhost', port=6379, db=0)
r.create("test_key_name")

Result
AttributeError: 'Redis' object has no attribute 'create'

**Comment by chayim** [comment]
@dilonne Can you please try:

```
import redis
r = redis.Redis(host='localhost', port=6379, db=0)
r.ts().create("test_key_name")
```

In redis4+ these commands sit inside of a module namespace, due to potential conflicts (such as get).
