### ISSUE TITLE
AIO support in RediSearch module?

### ISSUE THREAD

**Issue by alancleary** [redis/redis-py#2053]
I opened an issue in the redisearch-py repo a while back (RediSearch/redisearch-py#92) asking if they had any plans to add support for aioredis. Since then redisearch-py has been merged with redis-py and I see now that the imminent 4.2.0 will also merge the aioredis-py library. I'm wondering if the 4.2.0 release will add aioredis support to the redisearch module and, if not, if there's a timeline for this. If there's no timeline but you're open to this feature then I'd be happy to tackle the initial implementation and make a PR (my original issue links to an implementation I made in August of 2021 that has been languishing ever since).

Thanks for providing this awesome library. I'm glad to see all the redis libraries I use being merged into one :smiley:

**Comment by chayim** [comment]
@alancleary First off - those are mighty kind words!  Looking at [client.py](https://github.com/redis/redis-py/blob/878e2f2cd961bab5bf00d9b98e4fc7d16d5acfe0/redis/client.py#L805), we've merged it in - but honestly we don't have currently have this under test.  From my standpoint that means it doesn't work - until we have proof!

@dvora-h can you take a look?

**Comment by chayim** [comment]
@alancleary As of now (redis-py >= 4.3.1) we have aioredis as part of the library. I think we can safely close this.
