### ISSUE TITLE
Unable to connect to a Redis cluster

### ISSUE THREAD

**Issue by konfortes** [redis/redis-py#2058]
**Version**: 
4.1.4

**Platform**: 
Python 3.8.10 on a Red Hat 7.3.1-13 (EKS v1.21.5-eks-bc4871b)

**Description**:
Hey, I'm trying to use `redis.cluster.RedisCluster` to connect to a Redis cluster deployed in K8s using `bitnami/redis-cluster` Helm chart. 
For some reason, I'm not able to do that (code example below) and keep getting errors of: "redis.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node"
However, I'm able to connect with the same host and port using `redis-cli`

**This is how I deploy the Redis cluster**:
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-redis bitnami/redis-cluster -n ${infra.kubernetes.namespace} --set auth.enabled=false
```

**And this is how I try to connect**:
```
from redis.cluster import RedisCluster

conn = RedisCluster(
        host="my-redis-redis-cluster",
        port=6379,
        password=os.environ["REDIS_PASSWORD"],
        socket_connect_timeout=0.3,
        socket_timeout=0.5,
        decode_responses=True,
        skip_full_coverage_check=True,
    )
```

**The Error:**
```
  File "/srv/soda/sessionmanager/rediscluster_client_factory.py", line 22, in get_rediscluster_connection_from_env
    return RedisCluster(
  File "/usr/local/lib/python3.8/dist-packages/redis/cluster.py", line 513, in __init__
    self.nodes_manager = NodesManager(
  File "/usr/local/lib/python3.8/dist-packages/redis/cluster.py", line 1134, in __init__
    self.initialize()
  File "/usr/local/lib/python3.8/dist-packages/redis/cluster.py", line 1414, in initialize
    raise RedisClusterException(
redis.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.
```

**Comment by gkorland** [comment]
@konfortes can you please share how do you connect the cluster with redis-cli?

**Comment by konfortes** [comment]
Hey @gkorland 

I'm running:
```
redis-cli -c -h my-redis-redis-cluster
```
From within the cluster - from a pod in the same namespace of the Redis deployment.

Looking at `CLUSTER NODES`+ `CLUSTER INFO`, it seems like the Redis cluster is deployed and running successfully

**Comment by konfortes** [comment]
@gkorland I just find out I was running an out of date Docker image which uses the `ssl` flag 🤦🏻
Sorry, thanks for replying!
