### ISSUE TITLE
Inconsistent TS.INFO content

### ISSUE THREAD

**Issue by JoelBender** [redis/redis-py#2064]
**Version**: 4.2.0
**Platform**: Python 3.8, Ubuntu 20.04

**Description**:

The naming mapping [here](https://github.com/redis/redis-py/blob/master/redis/commands/timeseries/info.py#L70) is inconsistent with the other names, **snake_case** vs **camelCase**, and I would prefer that the contents be the same as those in [the documentation](https://oss.redis.com/redistimeseries/master/commands/#tsinfo) that is also referenced in the code comment, so `firstTimeStamp` rather than `first_time_stamp`.  It would be a more impactful change, but better in the long run.

```python
>>> temp_info = ts.info('temp')
>>> dir(temp_info)
[..., 'first_time_stamp', 'labels', 'lastTimeStamp', 'last_time_stamp', 'max_samples_per_chunk', ...]
```

**Comment by vrubiolo** [comment]
Hi there, I came here with the same observation about `first_time_stamp`. I think it would be better if the field were to be set to `firstTimeStamp` instead.

This is `redis-py v4.3.4` running against `redis 6.2.7` on Fedora 35
