### ISSUE TITLE
Does it support asyncio for redis cluster?

### ISSUE THREAD

**Issue by kingluo** [redis/redis-py#2081]
It seems that the async version only supports a single Redis instance?

**Comment by cpvandehey** [comment]
I can see comments from back in February from folks working on it. I think they originally tried to support clusters, but Im not sure if that was reprioritized. 
https://github.com/redis/redis-py/pull/1899

**Comment by cpvandehey** [comment]
@Andrew-Chen-Wang

**Comment by Andrew-Chen-Wang** [comment]
No asyncio cluster support yet. Can't remember why I didn't implement it. I don't have the time to check it out again (tho I suppose I can give an hour right now to do it).

**Comment by chayim** [comment]
We're almost there... at least for a few modules. @utkarshgupta137 contributed [this PR](https://github.com/redis/redis-py/pull/2099)

**Comment by agronholm** [comment]
This was address with the addition of `redis.asyncio.RedisCluster` in [v4.3.0](https://github.com/redis/redis-py/releases/tag/v4.3.0), Although it's yet undocumented: https://redis.readthedocs.io/en/latest/connections.html#rediscluster-async

**Comment by chayim** [comment]
It's in 4.3.1 @agronholm but we definitely could use a hand with documentation. There was amazing work done by @utkarshgupta137 to get tests in - and they could be the basis for another improvement to our jupyter notebooks. Fancy having a crack at it?

**Comment by chayim** [comment]
Alas... had to hope though ;). Thanks anyways @agronholm

**Comment by XChikuX** [comment]
I'd like to use redis with asyncio, is this stable other than the lack of documentation?
If so, I'd be happy to contribute where possible!!

**Comment by chayim** [comment]
IMHO we should close this. asyncio works in cluster mode, and we have the associated tests. There are missing parity features (RediSearch), but those will land over time.
