### ISSUE TITLE
`socket_keepalive_options` param issue

### ISSUE THREAD

**Issue by ugatenio** [redis/redis-py#2101]
I want to configure the following:
`sock.setsockopt(socket.IPPROTO_TCP, 0x10, 1)`

I saw Redis client has such as option using `socket_keepalive_options`.
So I defined {'0x10', 1} and I got the following error:
```
File “/usr/local/lib/python3.7/site-packages/redis/connection.py”, line 608, in <lambda>           │
  lambda: self._connect(), lambda error: self.disconnect(error)                       │
 File “/usr/local/lib/python3.7/site-packages/redis/connection.py”, line 655, in _connect           │
  sock.setsockopt(socket.IPPROTO_TCP, k, v)                                 │
TypeError: an integer is required (got type str)
```

**Comment by chayim** [comment]
Hi @ugatenio can you add share your sample code here - something that performs your connection? I'd like to see exactly what you're doing, as opposed to this snippet from the library.

**Comment by ugatenio** [comment]
Thanks!
