### ISSUE TITLE
`redis.asyncio` module not properly typed

### ISSUE THREAD

**Issue by soukyomi** [redis/redis-py#2105]
**Version**: Latest (4.2.2)
**Platform**: Arch Linux
**Description**: When importing the `redis.asyncio` module, Mypy complains about the stubs not being installed. This problem does not happen when importing only the `redis` module.

> Library stubs not installed for "redis.asyncio" (or incompatible with Python 3.10)mypy(error)
Hint: "python3 -m pip install types-redis"mypy(note)
(or run "mypy --install-types" to install all missing stub packages)mypy(note)
See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-importsmypy(note)

**Comment by WisdomPill** [comment]
Hey there!

I took a first stab at `lock` in  #2137.

Next my eyes are on either `redis.client.py` or some commands in `redis.commands`

@soukyomi do you have some preference on some module?

**Comment by danielkza** [comment]
`aioredis`, from which (as I understand) the `asyncio` module was imported is typed. So it should be a matter of adopting the same stubs.

**Comment by DavisDmitry** [comment]
> `aioredis`, from which (as I understand) the `asyncio` module was imported is typed. So it should be a matter of adopting the same stubs.

Mypy requires py.typed file to understand that a module is typed. It was removed..

**Comment by bitterteriyaki** [comment]
> @bitterteriyaki did you figure out how to fix this issue? I have just the same)

It is necessary to add a `py.typed` file to indicate to Mypy that the module is typed. You can open a PR yourself or ask a maintainer to do so, since I was on a lot of personal tasks at the time, I didn't do any.
