### ISSUE TITLE
Proposal: rename `redis.asyncio` before it's too late

### ISSUE THREAD

**Issue by dimaqq** [redis/redis-py#2107]
**Version**: 4.2.0rc1

**Platform**: all

**Description**:

It feels very odd that standard library name `asyncio` is shadowed in `redis.asyncio`.
As a library user, I did not expect that.
I'm worried it will cause confusion.

I propose that this particular path is renamed before the asyncio-capable release is public.

**Comment by chayim** [comment]
Hi @dimaqq. Thank you for reporting this! The release of 4.2.0 is already public, we're up to 4.2.2.

I could see renaming this redis.async - in the future (say 5.0) but for now, I think we live with it. While it make be a bit awkward, I don't want to break backwards compatibility for those already using it.
