### ISSUE TITLE
Use minimum supported version for linting

### ISSUE THREAD

**Issue by WisdomPill** [redis/redis-py#2111]
**Version**: What redis-py and what redis version is the issue happening on? not applicable.

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure) not applicable.

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

[Here](https://github.com/redis/redis-py/blob/e5e265de87dfe7ef8cc5cad8c247d067c74fa44d/.github/workflows/integration.yaml#L27) the GitHub action for linting uses python 3.9, should not it be using python 3.6 (aka lowest supported python version)?

**Comment by chayim** [comment]
@WisdomPill the only thing this applies to is black, but you'll notice in the [tox.ini](https://github.com/redis/redis-py/blob/e5e265de87dfe7ef8cc5cad8c247d067c74fa44d/tox.ini#L347) that we rely on black's ability to limit to python36.  The other tools are all python version agnostic.

Feel free to reopen if you disagree, as always my friend.

**Comment by WisdomPill** [comment]
Well, to be sure I would use python 3.6 just because some new syntax could always slip in like the new typing system with tuple[str, str], list[int, float] or something else like match statements and so on
