### ISSUE TITLE
Cannot use Graph module with `redis.asyncio`

### ISSUE THREAD

**Issue by DurandA** [redis/redis-py#2116]
**Version**: 4.2.2

**Platform**: Python 3.8.10 on Ubuntu 20.04

**Description**: the `Graph` module does not seem to support async yet. Here is an example which throws `TypeError: 'coroutine' object is not subscriptable`:
```python
import redis.asyncio as redis

r = redis.Redis()
graph = r.graph()

query = (
    'MATCH (p:person)-[v:visited {purpose:"pleasure"}]->(c:country) '
    "RETURN p, v, c"
)

result = await graph.query(query)
```

**Comment by HorizonXP** [comment]
Same is true for some of the commands in `Search` module, like `FT.AGGREGATE`

**Comment by dvora-h** [comment]
#2273 
#2096
