### ISSUE TITLE
Make commands have a minimum supported redis version

### ISSUE THREAD

**Issue by WisdomPill** [redis/redis-py#2152]
Many commands are added since a specific version of redis, since this library supports redis from version 4 officially (?), 
some commands are available for newer version are available in the library but not in the server.

My idea is to fetch the version on the first connection used right after auth in [on_connect](https://github.com/redis/redis-py/blob/master/redis/connection.py#L701) or add a [connection_callback](https://github.com/redis/redis-py/blob/40fdb152641fcdf3be010cebe656331aa5709c2d/redis/connection.py#L637) using `INFO server`. 
After that "cache" (weird naming since we are talking about redis) the server version in a class variable in `connection_pool`.

After that add a decorator that could be used in every command or group of commands like the following `@requires_server_version(5, 0)`. 
Finally check that the `connection_pool` redis version so that the command will not even run if the command is not supported.

@chayim what do you think about this?

**Comment by chayim** [comment]
@WisdomPill So.. it's something I keep thinking about. We've solved this in test (see conftest.py) for this reason.  The issue I have is that the connection is already overloaded, and in my opinion not the fastest. I generally dislike things that make redis slower - though I totally agree with why users would want this.

Want to talk through it? When looking at other database libraries, it's the server side (as opposed to the client side) that usually fails - so by **not** doing this we would continue to be in line with those. But again - I care most about the user experience (even at the expense of internally developing the module).

**Comment by WisdomPill** [comment]
We could do something pythonic, so ask for forgiveness instead of permission.

As I see [here](https://github.com/redis/redis-py/issues/2117#issue-1211275381) the error is pretty structured, so I would say to just add minimum version in commands as a decorator and if an exception (new exception, like `CommandNotSupportedException` thrown from the inside execute_command) then the error can be very precise and say which server version is needed.

**Comment by chayim** [comment]
IMHO asking forgiveness i just trying it. I'd say if one really cares - try command commands. I.. don't think this is the right approach with a fire and forget database + language.
