### ISSUE TITLE
New getset format with expire not working (?)

### ISSUE THREAD

**Issue by Rafiot** [redis/redis-py#2154]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?

redis-py: `redis = {version = "^4.2.2", extras = ["hiredis"]} `
redis: 6.2.7

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

Kubuntu 22.04

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

Doing something like:
```
redis.set('key', 'value', get=True, nx=True, ex=300)
```
raises
```
redis.exceptions.ResponseError: syntax error
```

but 
```
redis.set('key', 'value', nx=True, ex=300)
```

works fine.

**Comment by kamyabzad** [comment]
This is a limitation in Redis 6.2.7. See [here](https://github.com/redis/redis/pull/8906).

**Comment by Rafiot** [comment]
Oh, right, thank you
