### ISSUE TITLE
Not able to import asyncio

### ISSUE THREAD

**Issue by mayurpande** [redis/redis-py#2169]
**Version**: 4.2.2

**Platform**: Python 3.8 Ubuntu 20.04

**Description**: When I try to import `asyncio` from `redis`  it doesn't let me, it is not in `__init__.py` `__all__` (in my pip package but also not in current code base in this repo)`

![asyncio](https://user-images.githubusercontent.com/6522456/167125897-e0762548-41bb-4d6e-a768-3dd5071b9303.PNG)

**Comment by thune-xiaobai** [comment]
same problem with pycharm, but no error raised when I run the script, so maybe its a pycharm issue.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/3123725/167249218-fa591efb-ef7a-492e-876e-f5babd25ef85.png">

**Comment by agronholm** [comment]
Obsolete redis stubs are to blame (the asyncio functionality was added recently). Typeshed has already been updated. I have no idea why the stubs are there and not in this project directly though.

**Comment by Lin-Your** [comment]
I have the same problem with pycharm. And, If you are using pycharm, this might be helpful.

![image](https://user-images.githubusercontent.com/57038375/167799181-77652357-5758-463e-b712-4622551c35ac.png)
The obsoleted redis stubs is located at 
`C:\Program Files\JetBrains\PyCharm 2021.2.4\plugins\python\helpers\typeshed\stubs\redis\redis`.

So I deleted this directory, and download the newest redis stubs by `pip install types-redis`, and copy the directory 
`.\venv\Lib\site-packages\redis-stubs` as 
`C:\Program Files\JetBrains\PyCharm 2021.2.4\plugins\python\helpers\typeshed\stubs\redis\redis`.

Move the file `METADATA.toml` outside.

Restart pycharm and it works.

**Comment by mayurpande** [comment]
Sorry for late reply, as @thune-xiaobai said, I was able to run it in my container fine. So is a Pycharm bug. I will try out what you have said @Lin-Your (I can also report to Pycharm).

**Comment by chayim** [comment]
> Obsolete redis stubs are to blame (the asyncio functionality was added recently). Typeshed has already been updated. I have no idea why the stubs are there and not in this project directly though.

@agronholm We've started to add typings basically everywhere.  Once we're ready - we have to add a py.typed, and then after 6 months typeshed will stop shipping theirs.  Any chance you'd like to help add typing?

**Comment by agronholm** [comment]
I'll think about it. I suggest you use [MonkeyType](https://pypi.org/project/MonkeyType/) to kickstart the process by collecting the actual used types when the test suite is run ([pytest-monkeytype](https://pypi.org/project/pytest-monkeytype/) might help there too). Then you only need to do some corrections here and there.

**Comment by didenko-yv** [comment]
> **Version**: 4.2.2
> 
> **Platform**: Python 3.8 Ubuntu 20.04
> 
> **Description**: When I try to import `asyncio` from `redis` it doesn't let me, it is not in `__init__.py` `__all__` (in my pip package but also not in current code base in this repo)`
> 
> ![asyncio](https://user-images.githubusercontent.com/6522456/167125897-e0762548-41bb-4d6e-a768-3dd5071b9303.PNG)

you can install ```types-redis``` it solves the problem
