### ISSUE TITLE
Return Type Annotation for Streams

### ISSUE THREAD

**Issue by ccrvlh** [redis/redis-py#2174]
Hi, I've been testing Stream for the first time, and have been missing the return type annotation for the commands.

So far we could make everything work with the `client.xadd` and `client.xreadgroup`. It seems that it returns a list, the first element being the topic name, and the second element a list of tuples: for each tuple the first element is the message ID, and second element the data.

This is fine and the format is not that important, can be easily parsed. However, I wonder if this format will be consistent regardless of the parameters added to `xadd` or ` xreadgroup`. It does seem to be the case with the testing we've done so far, but we haven't tried every possible combination.  Couldn't find much information on it, looking at the source the annotation is `ResponseT` which is `Any | Awaitable`, and there's no information on the docstring either, maybe there's something somewhere else that I've missed?

If there's any guideline on the return, I would be happy to contribute to this, it could be just an improved docstring, or maybe a strongly typed return annotation, or maybe just adding some notes to the Readme.

Thanks!

**Comment by JosephSBoyle** [comment]
I would also be happy to work on this. Should a potential PR be submitted to the async branch of redis.py?
