### ISSUE TITLE
[Disscussion] How to get redis-py to work asyncriously?

### ISSUE THREAD

**Issue by SnowyJaguar1034** [redis/redis-py#2176]
**Version**: Redis 4.2.2

**Platform**: Windows using Python 3.10.4 / version?

**Description**: Hi so I went to install aioredis a few days ago, for the first time, and found out that the lib had been moved to this repo however I can find no docks about using redis asyncriously. I saw something suggesting I should do
```py
from redis import asyncio as aioredis
```
but it doesn't seem to be working.

**Comment by agronholm** [comment]
You mean asynchronously? The docs on async usage are pretty awful, but they are part of the [official documentation](https://redis.readthedocs.io/en/latest/examples/asyncio_examples.html).

**Comment by chayim** [comment]
@SnowyJaguar1034 I recommend you read the documentation @agronholm has linked to - or even the unit tests!  Closing.

**Comment by didenko-yv** [comment]
If you are using pycharm, it can be error with stubs for asyncio module, you can run``` pip[pipenv] install types-redis``` and it solves the problem.

**Comment by SnowyJaguar1034** [comment]
> If you are using pycharm, it can be error with stubs for asyncio module, you can run` pip[pipenv] install types-redis` and it solves the problem.

I'm VSC so it doesn't seem to be erroring, I just can't connect to the redis server - think I'm missing required params in the Redis class creation which I think I've solved - but the missing docs for [async connection pools](https://redis.readthedocs.io/en/latest/connections.html#connectionpool-async) just flat out missing is a bit annoying. I assume the async connection takes a lot of traits from regular connection pools but I learn better from seeing examples so the fact they're missing is annoying.
