### ISSUE TITLE
Retries do no work with asyncio

### ISSUE THREAD

**Issue by elemoine** [redis/redis-py#2179]
We use `redis.asyncio.StrictRedis` and `redis.asyncio.BlockingConnectionPool`, with some specific `Retry` configuration:

```py
from redis.asyncio import BlockingConnectionPool, StrictClient
from redis.exceptions import ConnectionError, TimeoutError
from redis.asyncio.retry import Retry

errors = (ConnectionError, TimeoutError)
retry = Retry(backoff=backoff, retries=retries, supported_errors=errors)
pool = BlockingConnectionPool(retry=retry, retry_on_timeout=True)
client = StrictClient(connection_pool=pool)
```

And that doesn't work as expected! There are no retries at all on `ConnectionError` exceptions!

Here's what happens:

When executing a command, [an error handler is passed](https://github.com/redis/redis-py/blob/42b937fa1f73f3e8251eba5ec8ead2fcbaec7c50/redis/asyncio/client.py#L476-L481) to `call_with_retry`. That error handler is the [`_disconnect_raise`](https://github.com/redis/redis-py/blob/42b937fa1f73f3e8251eba5ec8ead2fcbaec7c50/redis/asyncio/client.py#L457-L465) function, which re-raises the exception if that exception is not a `TimeoutError`. Meaning that, in case of a `ConnectionError`, [`call_with_retry`](https://github.com/redis/redis-py/blob/42b937fa1f73f3e8251eba5ec8ead2fcbaec7c50/redis/asyncio/retry.py#L54) will raise and exit before having a chance to retry the operation.

**Comment by donbowman** [comment]
does this relate to https://github.com/redis/redis-py/pull/1485
?
