### ISSUE TITLE
sentinel async client

### ISSUE THREAD

**Issue by raphaelauv** [redis/redis-py#2183]
The doc do not explicit if the lib can support async for sentinel client, is this feature already present ? Thanks

**Comment by dvora-h** [comment]
@raphaelauv No, this feature is not supported for now. We are working on adding support for all the features in async mode so I hope that will be included in one of the next versions.

Also - we are always happy to get contributions if you want to do it yourself

**Comment by raphaelauv** [comment]
@dvora-h thanks for your answer.

Why did you close the issue ? You do not use them to track feature ideas ?
