### ISSUE TITLE
Missing pipeline support for async ClusterClient

### ISSUE THREAD

**Issue by karwinliu** [redis/redis-py#2186]
Version: redis-py (4.3.1) redis server (6.0)

Platform: Python 3.9 on macOS Apple silicon

Description: I don't see the support of pipeline for the async cluster client. Besides, I don't find any documentation on async version of the cluster client, so maybe it's already implemented and can be invoked in some special ways. If not, I wonder if there's already a plan to support that and if there's any workaround for the time being.

**Comment by grippy** [comment]
It has support for this already: https://github.com/Flipboard/redis-py/blob/29f97e9905637499343367888f1d66f76d9cc25c/redis/asyncio/client.py#L291-L304

https://github.com/Flipboard/redis-py/blob/29f97e9905637499343367888f1d66f76d9cc25c/redis/asyncio/client.py#L1320-L1347

Docs are here: https://redis-py.readthedocs.io/en/stable/connections.html?highlight=async#rediscluster-async

**Comment by karwinliu** [comment]
Oh I thought this is not for the clustered version, which would include mapping commands within a pipeline to different nodes/shards, etc.

**Comment by grippy** [comment]
@karwinliu You're right, I was looking at the async standalone client. Sorry, it looks like the async RedisCluster client inherits the `pipeline` method as part of the `AbstractRedisCluster` base class but its not async: https://github.com/Flipboard/redis-py/blob/29f97e9905637499343367888f1d66f76d9cc25c/redis/asyncio/cluster.py#L62-L63

**Comment by karwinliu** [comment]
No worries, would the pipeline be added soon? I think @utkarshgupta137 might already be working on it. I guess I'll just wait until it is ready

**Comment by utkarshgupta137** [comment]
> No worries, would the pipeline be added soon? I think @utkarshgupta137 might already be working on it. I guess I'll just wait until it is ready

I've got it working but I've only done basic testing. I will raise a PR once I write tests for it. If you want, you can check it out here: https://github.com/utkarshgupta137/redis-py/tree/async_cluster_pipeline

**Comment by karwinliu** [comment]
Thanks @utkarshgupta137 for all the implementations. We've started to fully evaluate the async cluster, and it's been working well so far. But we do found some issues after using it extensively, and I have just submitted the issues. Would you mind taking a look? We have applied some simple patches to fix the issue locally, but ideally this could be fixed in the package soon.
1. https://github.com/redis/redis-py/issues/2303
2. https://github.com/redis/redis-py/issues/2304
3. https://github.com/redis/redis-py/issues/2305

**Comment by utkarshgupta137** [comment]
Hey, I've already raised a PR for the first 2 issues, one of which is merged & other should be merged before the next release. For 3rd, I'll have to check if it is possible to use the same command for slots across keys.
