### ISSUE TITLE
v4.3.2 contains backwards incompatible change to `redis.lock.Lock`

### ISSUE THREAD

**Issue by sgg** [redis/redis-py#2209]
**Version**: 4.3.2

**Platform**: Python 3.9 (applicable to all)

**Description**:  PR #2137 converted [several arguments](https://github.com/redis/redis-py/pull/2137/files#diff-2fde47ac5b94240803faba932c3e886043bcf9018470ecb4a218fd6533611914R80) to `redis.lock.Lock.__init__` into keyword only arguments. This is backwards incompatible as it disallows the use of these arguments positionally. Releasing this w/ 4.3.2 also violates semver 😅

The following snippet can be used to repro. It works fine on 4.3.1 but fails on 4.3.2 w/ a `TypeError`:

```python
from redis import Redis
from redis.lock import Lock

def main():
    r = Redis("localhost:6379")
    Lock(r, "schlage", None)

if __name__ == "__main__":
    main()
```

```
redis432 ❯ python nope.py
Traceback (most recent call last):
  File "nope.py", line 9, in <module>
    main()
  File "nope.py", line 6, in main
    Lock(r, "schlage", None)
TypeError: __init__() takes 3 positional arguments but 4 were given
```

**Comment by dvora-h** [comment]
@sgg Sorry, this backward happened unintentionally and fixed in 4.3.3. Thank you for reporting this.

**Comment by sgg** [comment]
@dvora-h No worries, thanks for the fast fix. You may want to yank the 4.3.2 release on PyPI to prevent others from running into this. :)

**Comment by lelit** [comment]
PR #2137 changed also the signature of [Lock.acquire()](https://github.com/redis/redis-py/blob/master/redis/lock.py#L170) to accept only keyword arguments, so maybe that should be noted as a backward incompatibility note somewhere.

**Comment by zzzeek** [comment]
oh this is weird, here I was fixing it in dogpile.
