### ISSUE TITLE
FT create index on vectorfield issue

### ISSUE THREAD

**Issue by sr33kant** [redis/redis-py#2212]
**Version**: Pyredis 4.2.0 , redissearch :2.2.10 (Git=HEAD-3d0701f6)

**Platform**: Macos Monterey

**Description**: docker instance of redis search , ran using this command docker run -p 6399:6379 redislabs/redisearch:latest Trying to create a index with vectorfield , followed your examples . Running into invalid field type error

<img width="914" alt="Screen Shot 2022-06-02 at 10 54 52 AM" src="https://user-images.githubusercontent.com/19520536/171658276-dd33bb17-2478-471d-99a7-13ac14244e81.png">

**Comment by dvora-h** [comment]
@sr33kant Vector similarity search requires redisearch 2.4.3+ so you should run it with redislabs/redisearch:2.4.3
