### ISSUE TITLE
Logging (stdout/stderr) stops after `redis.Redis` client call 

### ISSUE THREAD

**Issue by monkut** [redis/redis-py#2222]
**Version**: redis-py 4.3.3, redis EngineVersion (elasticache) 5.0.4

**Platform**: python 3.9, docker (python:3.9-alpine), aws ecs.

**Description**: 

When I deploy my docker application using redis to ecs (fargate) the logs (stdout/stderr) stop being reported after making a call via the redis-py client.

Running docker locally I still see output , so the problem appears to be with the redis client and stdout/stderr handling with aws ecs.
Is there any code or setting in the redis client that may interfere with stdout/stderr handling?

Task logs:

> Log output stops after REDIS.set() call

![image](https://user-images.githubusercontent.com/1135529/172532386-26a8d5c2-fc3d-4f8a-a776-57882f2d75d8.png)

The following code is run as an ECS Task in ECS on AWS.

Sample Code: `rtm/runners.py`
```python
import logging
import os
import sys
from distutils.util import strtobool

import redis

DEFAULT_REDIS_HOST = "localhost"
REDIS_HOST = os.getenv("REDIS_HOST", DEFAULT_REDIS_HOST)
DEFAULT_REDIS_PORT = "6379"
REDIS_PORT = int(os.getenv("REDIS_PORT", DEFAULT_REDIS_PORT))
DEFAULT_REDIS_PASSWORD = None
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", DEFAULT_REDIS_PASSWORD)
DEFAULT_REDIS_SSL_SUPPORT = "False"
REDIS_SSL_SUPPORT = bool(strtobool(os.getenv("REDIS_SSL_SUPPORT", DEFAULT_REDIS_SSL_SUPPORT)))

DEFAULT_LOG_LEVEL = "DEBUG"
LOG_LEVEL = os.getenv("LOG_LEVEL", DEFAULT_LOG_LEVEL)
AVAILABLE_LOG_LEVELS = ("INFO", "CRITICAL", "WARNING", "ERROR", "DEBUG")
if LOG_LEVEL not in AVAILABLE_LOG_LEVELS:
    LOG_LEVEL = DEFAULT_LOG_LEVEL
log_level = getattr(logging, LOG_LEVEL)
logging.basicConfig(
    handlers=[
         logging.StreamHandler(stream=sys.stdout),
    ],
    level=log_level,
    format="%(asctime)s [%(levelname)s] (%(name)s) %(funcName)s: %(message)s",
)

logger = logging.getLogger(__name__)


def logger_output_check():
    """送信の実行ループ"""
    print("print")
    logger.info("info")
    logger.debug("debug")
    logger.warning("warning")
    logger.error("error")
    logger.critical("critical")

    logger.debug("creating REDIS client ...")
    REDIS = redis.Redis(
        host=REDIS_HOST,
        port=REDIS_PORT,
        password=REDIS_PASSWORD,
        retry_on_timeout=True,
        encoding="utf-8",
        decode_responses=True,
        ssl=REDIS_SSL_SUPPORT,
    )
    logger.debug("creating REDIS client ... DONE")

    logger.debug("REDIS.set() ...")
    REDIS.set("test-key", "test-value")
    logger.debug("REDIS.set() ... DONE")

    logger.debug("REDIS.get() ...")
    REDIS.get("test-key")
    logger.debug("REDIS.get() ... DONE")


if __name__ == "__main__":
    print("logger_output_check()")
    logger_output_check()

```

Dockerfile:
```
# pull official base image
FROM python:3.9-alpine

# set work directory
WORKDIR /usr/src/app

ARG GITHASH

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONWARNINGS ignore
ENV APP_VERSION $GITHASH
RUN echo $(env | grep APP)

# install dependencies
RUN apk update \
    && apk add --no-cache gcc python3-dev musl-dev build-base git make libffi-dev libevent-dev

# install python env dependencies
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install pip -U && pip install wheel
RUN pip install pipenv

# copy project
COPY . /usr/src/app/

# install app
RUN cd /usr/src/app/ && pipenv sync

WORKDIR /usr/src/app

RUN echo APP_VERSION=${APP_VERSION} > .env

ENTRYPOINT ["pipenv", "run", "python", "-m", "rtm.runners"]
```

Task Definition Attributes

Requires attributes
- com.amazonaws.ecs.capability.logging-driver.awslogs
- ecs.capability.execution-role-awslogs
- com.amazonaws.ecs.capability.ecr-auth
- com.amazonaws.ecs.capability.docker-remote-api.1.19
- com.amazonaws.ecs.capability.docker-remote-api.1.17
- com.amazonaws.ecs.capability.task-iam-role
- ecs.capability.execution-role-ecr-pull
- com.amazonaws.ecs.capability.docker-remote-api.1.18
- ecs.capability.task-eni
com.amazonaws.ecs.capability.docker-remote-api.1.29

**Comment by monkut** [comment]
Seems like the issue was a combination of retry_on_timeout and bad `ssl` support configuration.
Where `ssl` was set to `False` but needed to be `True`, resulting in the connection not being made to redis.

Perhaps eventually a timeout log would output but I didn't notice one.

**Comment by starrabb1t** [comment]
I use default initialization and have the same issue. There are empty docker logs after redis call :(
