### ISSUE TITLE
[Question] Remove Redis Cluster logs 

### ISSUE THREAD

**Issue by Ankhas** [redis/redis-py#2227]
**Version**: 
4.2.2

**Platform**:
Python 3.8.10 on Ubuntu 20.04

**Description**:
There is so much logs in `cluster` module that I would not want it to show up in my application logs. Is there a reason to leave these logs in this module? Instead, couldn't we just raise exception and let the user handle them as he wishes?

**Comment by chayim** [comment]
Agreed. Those shouldn't have made it through the PR. However, I'd argue that this is a breaking (but worthwhile!) change, in case someone is relying on this behaviour.  
We made a similar change in the latest Jedis.

@dvora-h candidate for >=4.4.0

**Comment by nialdaly** [comment]
In theory, are we saying here that we would like to remove all of the `log.` statements from *redis-py/redis/cluster.py*?

**Comment by utkarshgupta137** [comment]
I think that would be best. Log statements probably get ignored & add significant overhead even if it is not within debugging level (the LogRecord objects themselves take a lot of time to create & then are instantly thrown away).
This is the approach I've followed for the async version too.

**Comment by nialdaly** [comment]
Hi @utkarshgupta137 @chayim @Ankhas I made some changes to `redis-py/redis/cluster.py` in this [PR](https://github.com/redis/redis-py/pull/2238). Hopefully it looks okay!
