### ISSUE TITLE
implementing "command key specifications" for cluster mode

### ISSUE THREAD

**Issue by arebrik** [redis/redis-py#2229]
**Version**: 
redis-py 4.3.3
redis 7.0.2

**Platform**: 
Python 3.10 / Any plaftorm

**Description**: 
For now, redis-py lib execute `COMMAND GETKEYS` for any command with **movablekeys** flag every time this command called(implemented in  `commands.parser.CommandsParser`).
According to [this](https://redis.io/commands/command/#movablekeys) topic:

"As of Redis 7.0, clients can use the [key specifications](https://redis.io/commands/command/#key-specifications) to identify the positions of key names. The only commands that require using [COMMAND GETKEYS](https://redis.io/commands/command-getkeys) are [SORT](https://redis.io/commands/sort) and [MIGRATE](https://redis.io/commands/migrate) for clients that parse keys' specifications."

Why this implementation important: one of command with **movablekeys** flag is `SET`, which seams one of the most "popular" command in pair with `GET`.  So, for now, call `SET ` always means to do additional call `COMMAND GETKEYS SET` which defenetly increase summary latency.

**Comment by utkarshgupta137** [comment]
While it would help, the `SET` command does not have the `movablekeys` flag, at least in Redis 4/6.

Here are the commands which do have the flag:
- EVAL
- EVALSHA
- GEORADIUS
- GEORADIUS_RO
- GEORADIUSBYMEMBER
- GEORADIUSBYMEMBER_RO
- MEMORY
- SORT
- STRALGO
- XREAD
- XREADGROUP
- ZINTERSTORE
- ZUNIONSTORE

Out of this EVAL/EVALSHA don't rely on `COMMAND GETKEYS`.

**Comment by artesby** [comment]
SET having MOVABLEKEYS flag was reported as bug in this issue https://github.com/redis/redis/issues/10833
and was fixed in redis 7.0.2 according to this https://github.com/redis/redis/releases/tag/7.0.2
