### ISSUE TITLE
Add support for JSON commands in Async Cluster

### ISSUE THREAD

**Issue by motybz** [redis/redis-py#2234]
It seems that the .json() ability [is supported in the Cluster client](https://github.com/redis/redis-py/pull/2032
) but not in Async Cluster client.

```python
from redis.asyncio.cluster import RedisCluster
client = RedisCluster()
await client.json().get("test")
```

`AttributeError: 'RedisCluster' object has no attribute 'json'`

**Comment by chayim** [comment]
Supported in 4.4.0.

**Comment by baltika10** [comment]
This doesn't seem to work still 
AttributeError: 'RedisCluster' object has no attribute 'json'
when using redis.asyncio.cluster.RedisCluster (version 4.5.1)

**Comment by chayim** [comment]
@dvora-h can you double check this?

**Comment by bharatbots** [comment]
This still doesn't work with redis.asyncio. I'm using the latest version(4.5.5)

**Comment by the-wondersmith** [comment]
@chayim I can confirm @bharatbots's findings, FWIW

**Comment by the-wondersmith** [comment]
@chayim @bharatbots 

Did some more digging / testing. Long story short, the comments in [PR #2423](https://github.com/redis/redis-py/pull/2423) are correct - `redis.commands.redismodules.AsyncRedisModuleCommands` needs to be added to the inherited classes for `redis.asyncio.cluster.RedisCluster` and `redis.asyncio.cluster.ClusterPipeline`.

**ALSO**, an implementation of `set_response_callback` needs to be added to the cluster pipeline class that propagates the supplied callback to the bound client's associated `Node`'s.

From my testing, this seems to work just fine:

```python
def set_response_callback(self, command: str, callback: Callable[..., Any]) -> None:
    """Set a custom response callback."""
    self._client.set_response_callback(command, callback)

    for node in self._client.nodes_manager.nodes_cache.values():
        node.response_callbacks[command] = callback
```
