### ISSUE TITLE
What is the function of health_check_interval 

### ISSUE THREAD

**Issue by szn409** [redis/redis-py#2239]

**Comment by dvora-h** [comment]
The check_health() function check the health of the connection with a PING/PONG if the connection was idle more than health_check_interval seconds

**Comment by OlegZv** [comment]
I think it's important to note that `check_health()` will only get executed when issuing a command (and if the connection was idle for more than `health_check_interval`.
I **mistakenly** thought that `redis-py` would automatically send the PING command every `health_check_interval` as a background thread.

**Comment by rishabhpoddar** [comment]
So what is the benefit of setting health_check_interval if the check_health() function is only called when issuing a command? Cause then if check_health fails, the request will fail anyway.

**Comment by djmaze** [comment]
From the changelog:

> Passing the "health_check_interval=N" option to the Redis client class or to a ConnectionPool ensures that a round trip PING/PONG is successful before any command if the underlying connection has been idle for more than N seconds. ConnectionErrors and TimeoutErrors are automatically retried once for health checks.
