### ISSUE TITLE
Cannot find reference 'asyncio' in `__init__.pyi`

### ISSUE THREAD

**Issue by andrew000** [redis/redis-py#2249]
**Version**: 4.3.3

**Platform**: Windows 10 x64

**Description**:
PyCharm can't find reference 'asyncio' in `__init__.pyi` because it doesn't exists in generated `pyi`

I think problem is in name of folder ('asyncio').

Cache invalidation, redis reinstalling, pycharm reinstalling didn't help.

![image](https://user-images.githubusercontent.com/11490628/175526541-7e4a461e-a6c2-4617-93d5-429ccb269759.png)
![image](https://user-images.githubusercontent.com/11490628/175526790-91583291-0466-44f8-b147-c09dfa36029d.png)

**Comment by chayim** [comment]
This is a bug in typeshed and their redis stub generators, not redis-py. Once redis-py fully supports type hints, this would be ours.  Please feel free to help contribute type hints!

**Comment by Olegt0rr** [comment]
# Workaround
#### 0. Close your PyCharm.
#### 1. Find `typeshed` folder in your PyCharm sources.
For my macOS it was located here: 
`cd /Applications/PyCharm.app/Contents/plugins/python/helpers`

#### 2. Delete `typeshed`
`rm -r typeshed`

#### 3. Clone updated `typeshed`
`git clone https://github.com/python/typeshed.git`

#### 4. Profit! :D

**Comment by sh-cho** [comment]
FYI, I installed PyCharm via JetBrains Toolbox and PyCharm is installed on `~/Library/Application\ Support/JetBrains/PyCharm2022.1/`

**Comment by evgfilim1** [comment]
Better workaround that worked for me
- Find your PyCharm installation directory (see above)
- Go to `plugins/python/helpers/typeshed`
- Remove `redis` directory, PyCharm will use redis-py sources as source for type hinting

**Comment by JordanZimmitti** [comment]
I know this is closed but when will this typing issue be fixed for real? Like I feel like this should remain open until its actually fixed

**Comment by evgfilim1** [comment]
> I know this is closed but when will this typing issue be fixed for real? Like I feel like this should remain open until its actually fixed

@JordanZimmitti 
1) It is not the problem of redis-py
2) It is fixed upstream

**Comment by JordanZimmitti** [comment]
@evgfilim1 Thanks for the reply! So is it a problem Pycharm then, as in they need to fix something?

**Comment by tshipenchko** [comment]
If someone needs config for NixOS for this workaround https://github.com/redis/redis-py/issues/2249#issuecomment-1269864121
 
```nix
{ pkgs, lib, ... }:
let
  myOverlay = self: super: {
    pycharm-professional-with-patch = super.jetbrains.pycharm-professional.overrideAttrs (oldAttrs: {
      postInstall = (oldAttrs.postInstall or "") + ''
        rm -rf $out/pycharm-professional/plugins/python/helpers/typeshed/stubs/redis/
      '';
    });
  };
in
{
  nixpkgs.overlays = [ myOverlay ];
  environment.systemPackages = with pkgs; [
    pycharm-professional-with-patch
  ];
}

**Comment by nikumar1206** [comment]
Hi, this issue is happening to me on VS Code as well.
