### ISSUE TITLE
ft.dropindex() crashes server

### ISSUE THREAD

**Issue by svaraborut** [redis/redis-py#2265]
Hello, I'm using version `4.3.4` and found out that `dropindex()` crashes the server when the index is not present. [Related to](https://github.com/RediSearch/RediSearch/issues/2152)

What is more interesting is why is the library using an undocumented `FT.DROP`  command [see](https://github.com/redis/redis-py/blob/ae83d40384665e2533d2f181981f991a45f58555/redis/commands/search/commands.py#L22) rather than using `FT.DROPINDEX` which does not crash the server?

**Comment by chayim** [comment]
In the past FT.DROP was the drop command (here's a historic link): https://d128ysc22mu7qe.cloudfront.net/Commands/#ftdrop. Perhaps there's some cruft there.

@dvora-h want to change the behaviour to run FT.DROPINDEX? We might need to denote this in the release notes?

**Comment by chayim** [comment]
Grrr apparently I can't label today? @dvora-h can you mark "bug" and "breakingchange"
