### ISSUE TITLE
"client" is not a known member of `redis.asyncio`

### ISSUE THREAD

**Issue by ptrxyz** [redis/redis-py#2288]
**Version**: What redis-py and what redis version is the issue happening on?

redis: 4.3.4
types-redis: 4.3.4

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

Python 3.10 on Arch Linux

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

consider this minimal example:
```python
from redis import asyncio as redis
print(type(redis.client.PubSub))
```

While it perfectly wokrs, Pylance thorws an error that "client" is not a known member of module. Mypy however seems to be good with it.
Something seems to be off with the member definition?

**Comment by ptrxyz** [comment]
Hm, I find that it is indeed present in `redis` (as opposed to `redis.asyncio`).
To maybe it's enough to just adjust the documentation here: https://redis-py.readthedocs.io/en/stable/examples/asyncio_examples.html#Pub/Sub-Mode

**Comment by dvora-h** [comment]
Closing as it is a pylance error
