### ISSUE TITLE
Add pubsub support in asyncio Redis Cluster client

### ISSUE THREAD

**Issue by coandco** [redis/redis-py#2289]
**Version**: 4.3.4

**Platform**: Python 3.9 on Debian Bullseye

**Description**: redis.asyncio.RedisCluster appears to be very feature-poor compared to the blocking version -- it lacks support for the pubsub(), which makes it much less useful.

**Comment by uglide** [comment]
Hi @coandco  
The `lock()` support was added in https://github.com/redis/redis-py/pull/2446
I've updated your ticket to reflect the current state.

**Comment by uglide** [comment]
Duplicate of https://github.com/redis/redis-py/issues/2219
