### ISSUE TITLE
redis sentinel throw "Timeout connecting to server" error

### ISSUE THREAD

**Issue by hitrust** [redis/redis-py#2290]
Version:
    redis-py version 4.3.4
    redis server version 6.2.7
    redis sentinel version 6.2.7

redis server Platform:
    Operating System: Debian GNU/Linux 10 (buster)
    Kernel: Linux 4.19.0-21-cloud-amd64
    Architecture: x86-64

   docker: Docker version 20.10.17, build 100c701
   
  redis image: docker official image

redis client Platform:
 Python 3.9.13 on Windows 10 virtual environment

Description: 
1 master, 1 replica, 3 sentinel all in one host.
discover_master and discover_slaves can get right result, but master.set throw error "timed out"

> CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS                                                 NAMES
> 6d04dbb25a24   sentinel_redis-sentinel   "/docker-entrypoint.…"   29 minutes ago   Up 29 minutes   0.0.0.0:26381->26379/tcp, :::26381->26379/tcp         sentinel-redis-sentinel-2
> 9280b646008b   sentinel_redis-sentinel   "/docker-entrypoint.…"   29 minutes ago   Up 29 minutes   0.0.0.0:26380->26379/tcp, :::26380->26379/tcp         sentinel-redis-sentinel-3
> 1d0df59ff350   sentinel_redis-sentinel   "/docker-entrypoint.…"   29 minutes ago   Up 29 minutes   0.0.0.0:26379->26379/tcp, :::26379->26379/tcp         sentinel-redis-sentinel-1
> 886361c99913   sentinel_redis-slave      "/docker-entrypoint.…"   29 minutes ago   Up 29 minutes   6379/tcp, 0.0.0.0:6381->6381/tcp, :::6381->6381/tcp   sentinel-redis-slave-1
> d6827153fdd6   sentinel_redis-master     "/docker-entrypoint.…"   29 minutes ago   Up 29 minutes   6379/tcp, 0.0.0.0:6380->6380/tcp, :::6380->6380/tcp   sentinel-redis-master-1

# redis-cli -p 26379
127.0.0.1:26379> SENTINEL master mymaster
 1) "name"
 2) "mymaster"
 3) "ip"
 4) "172.25.0.2"
 5) "port"
 6) "6380"
 7) "runid"
 8) "78823b9e95971e48fc161987bc9db927db95f4a7"
 9) "flags"
10) "master"
11) "link-pending-commands"
12) "0"
13) "link-refcount"
14) "1"
15) "last-ping-sent"
16) "0"
17) "last-ok-ping-reply"
18) "96"
19) "last-ping-reply"
20) "96"
21) "down-after-milliseconds"
22) "5000"
23) "info-refresh"
24) "8505"
25) "role-reported"
26) "master"
27) "role-reported-time"
28) "2267051"
29) "config-epoch"
30) "0"
31) "num-slaves"
32) "1"
33) "num-other-sentinels"
34) "2"
35) "quorum"
36) "2"
37) "failover-timeout"
38) "60000"
39) "parallel-syncs"
40) "1"

127.0.0.1:26379> SENTINEL replicas mymaster
1)  1) "name"
    2) "172.25.0.3:6381"
    3) "ip"
    4) "172.25.0.3"
    5) "port"
    6) "6381"
    7) "runid"
    8) "d1fb8b420957cd5c5172b2559d2b3c81310bed50"
    9) "flags"
   10) "slave"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "97"
   19) "last-ping-reply"
   20) "97"
   21) "down-after-milliseconds"
   22) "5000"
   23) "info-refresh"
   24) "3327"
   25) "role-reported"
   26) "slave"
   27) "role-reported-time"
   28) "2352117"
   29) "master-link-down-time"
   30) "0"
   31) "master-link-status"
   32) "ok"
   33) "master-host"
   34) "redis-master"
   35) "master-port"
   36) "6380"
   37) "slave-priority"
   38) "100"
   39) "slave-repl-offset"
   40) "469845"
   41) "replica-announced"
   42) "1"

127.0.0.1:26379> SENTINEL sentinels mymaster
1)  1) "name"
    2) "a41ea1840b91accbb79f848bbedba9a53dfe2a9c"
    3) "ip"
    4) "172.25.0.5"
    5) "port"
    6) "26379"
    7) "runid"
    8) "a41ea1840b91accbb79f848bbedba9a53dfe2a9c"
    9) "flags"
   10) "sentinel"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "1011"
   19) "last-ping-reply"
   20) "1011"
   21) "down-after-milliseconds"
   22) "5000"
   23) "last-hello-message"
   24) "876"
   25) "voted-leader"
   26) "?"
   27) "voted-leader-epoch"
   28) "0"
2)  1) "name"
    2) "88c6d217e0c959d7b67ff4af3b784d2a28cabb39"
    3) "ip"
    4) "172.25.0.4"
    5) "port"
    6) "26379"
    7) "runid"
    8) "88c6d217e0c959d7b67ff4af3b784d2a28cabb39"
    9) "flags"
   10) "sentinel"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "1011"
   19) "last-ping-reply"
   20) "1011"
   21) "down-after-milliseconds"
   22) "5000"
   23) "last-hello-message"
   24) "790"
   25) "voted-leader"
   26) "?"
   27) "voted-leader-epoch"
   28) "0"

```
from redis.sentinel import Sentinel
sentinel = Sentinel([('host ip', 26379), ('host ip', 26380), ('host ip', 26381)], socket_timeout=0.1)
# sentinel = Sentinel([('localhost', 26379)], socket_timeout=0.1)

master_result = sentinel.discover_master('mymaster')
slaves_result = sentinel.discover_slaves('mymaster')
print(master_result)
print(slaves_result)

('172.25.0.2', 6380)
[('172.25.0.3', 6381)]
```

```
master = sentinel.master_for('mymaster', socket_timeout=0.1)
slave = sentinel.slave_for('mymaster', socket_timeout=0.1)
master.set('foo', 'bar')
result = slave.get('foo')
print(result)
```

> Traceback (most recent call last):
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\connection.py", line 609, in connect
>     sock = self.retry.call_with_retry(
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\retry.py", line 51, in call_with_retry       
>     raise error
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\retry.py", line 46, in call_with_retry       
>     return do()
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\connection.py", line 610, in <lambda>        
>     lambda: self._connect(), lambda error: self.disconnect(error)
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\connection.py", line 675, in _connect        
>     raise err
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\connection.py", line 663, in _connect        
>     sock.connect(socket_address)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "F:\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "F:\Python\Python39\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "F:\projects\mystuff\demo\demo\prodramatiq\redis_op.py", line 36, in <module>
>     master.set('foo', 'bar')
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\commands\core.py", line 2214, in set
>     return self.execute_command("SET", *pieces, **options)
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\client.py", line 1232, in execute_command    
>     conn = self.connection or pool.get_connection(command_name, **options)
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\connection.py", line 1383, in get_connection 
>     connection.connect()
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\sentinel.py", line 54, in connect
>     return self.retry.call_with_retry(self._connect_retry, lambda error: None)
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\retry.py", line 51, in call_with_retry       
>     raise error
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\retry.py", line 46, in call_with_retry       
>     return do()
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\sentinel.py", line 44, in _connect_retry     
>     self.connect_to(self.connection_pool.get_master_address())
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\sentinel.py", line 34, in connect_to
>     super().connect()
>   File "F:\projects\mystuff\demo\lib\site-packages\redis\connection.py", line 613, in connect
>     raise TimeoutError("Timeout connecting to server")
> redis.exceptions.TimeoutError: Timeout connecting to server

**Comment by machineCYC** [comment]
seems i have the same issue!

**Comment by murliwatz** [comment]
I get the same error

**Comment by ant1fact** [comment]
Same issue here, has anybody found a workaround?

**Comment by bygzyz** [comment]
Got same issue, need help

**Comment by bygzyz** [comment]
> seems i have the same issue!



> Same issue here, has anybody found a workaround?

hi bro, did you got a solution?

**Comment by nerg4l** [comment]
Have you tried to increase the value of `socket_timeout`? For example, using `sentinel.master_for('mymaster')` instead of `sentinel.master_for('mymaster', socket_timeout=0.1)`.

**Comment by hitrust** [comment]
Thanks @nerg4l
 the same issue with or without 'timeout' setting

**Comment by richardARPANET** [comment]
I'm also experiencing this problem. Has anyone found a solution?

**Comment by zidokobik** [comment]
> I'm also experiencing this problem. Has anyone found a solution?
> 
> edit:
> 
> Sending a giant timeout works for me:
> 
> ```python
> from django.conf import settings
> from redis import Sentinel
> 
> 
> def get_redis_client():
>     sentinel = Sentinel(settings.REDIS_SENTINELS, socket_timeout=1000)
>     client = sentinel.master_for(settings.REDIS_MASTER_NAME, socket_timeout=1000)
>     return client
> ```
> 
> edit:
> 
> turns out this param units are milliseconds, not seconds

I'm pretty sure it's in seconds. We need better documentation for the `socket_timeout`, `socket_connect_timeout`, `socket_keepalive` and `socket_keepalive_options` arguments.

**Comment by huibian** [comment]
Because sentinel is used to obtain the internal IP of the docker container, the python client actually uses the container IP to connect. You need to convert the docker network to host (ps: host mode only uses Linux system)

**Comment by hitrust** [comment]
An articles about this.

[https://redis.io/docs/latest/operate/oss_and_stack/management/sentinel/#sentinel-docker-nat-and-possible-issues](url)
