### ISSUE TITLE
Question: Determine idle/used connections.

### ISSUE THREAD

**Issue by dbgoytia** [redis/redis-py#2294]
Hey everyone, this might be a small question, but how do you actually determine if a connection from a Connection Pool is either idle or used?

**Comment by dvora-h** [comment]
ConnectionPool object has `_available_connections` and `_in_use_connections` list properties, so you can check which list is own this connection

**Comment by dbgoytia** [comment]
Hi @dvora-h tjanks a lot for the answer. What's the differentiation between both of these attributes?
