### ISSUE TITLE
MovedError not caught in cluster.py::_execute_command

### ISSUE THREAD

**Issue by dschartner** [redis/redis-py#2298]
**Version**: What redis-py and what redis version is the issue happening on?
redis: 4.3.4

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

Python 3.8.12 on Alpine

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

I see there is exception handling for `MovedError` in `cluster.py::_execute_command` but it seems to be handled as a `ResponseError` instead. Maybe there's some other context I'm missing?
```
MovedError: 106 hostname:6379
  File "redis/cluster.py", line 1074, in _execute_command
    response = redis_node.parse_response(connection, command, **kwargs)
  File "redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "redis/connection.py", line 839, in read_response
    raise response
```

**Comment by hungrybirder** [comment]
test

**Comment by dvora-h** [comment]
@dschartnerWhat caused you this error?  MovedError is caught on line 1105 https://github.com/redis/redis-py/blob/e6cd4fdf3b159d7f118f154e28e884069da89d7e/redis/cluster.py#L1105

**Comment by dschartner** [comment]
It looks like the error is being caught correctly.
