### ISSUE TITLE
Support SSL in async Redis cluster client

### ISSUE THREAD

**Issue by karwinliu** [redis/redis-py#2303]
**Version**: v4.3.4

**Platform**: Python 3.9 on linux/macOS

**Description**: As described in the title, the async Redis cluster client needs to support SSL. 
The `CONNECTION_ALLOWED_KEYS` in asyncio/cluster.py needs to extend with things like `ssl_ca_certs`, `ssl_certfile`, `ssl_keyfile`, etc. Otherwise even if the client uses them in the `connection_args`, they will get purged

**Comment by utkarshgupta137** [comment]
Fixed by #2217
