### ISSUE TITLE
Redis Graph documentation is insufficient

### ISSUE THREAD

**Issue by skoot** [redis/redis-py#2318]
**Version**: 4.3.4

**Platform**: N/A

**Description**:

https://redis.io/docs/stack/graph/clients/ lists https://github.com/RedisGraph/redisgraph-py as one of the official clients, and the documentation on https://developer.redis.com/howtos/redisgraph/using-python also points to redisgraph-py.

However, on the redisgraph-py page, it is marked as archived and deprecated, and points to redis-py as the replacement.

But, the libraries are not compatible (the order of the arguments have changed, the pretty_print function doesn't exist), and there's barely any documentation about it. For example, there is no explanation or example on how to use a `QueryResult`. Which means that I can't use the documentation I find about redisgraph-py with redis-py, and redis-y doesn't have enough documentation to get me started.

What would you recommend using as of today? The deprecated but well documented library, or the new one that's barely documented, which to me begs the question: is it even actually supported?

**Comment by skoot** [comment]
ignore the question at the end because I actually don't have a choice. redisgraph-py depends on redis-py 3.5.3, and I don't want to downgrade redis-py.

**Comment by Garito** [comment]
The title of this issue should be:
Redis modules documentation is almost nonexistent

**Comment by nermiller** [comment]
@Garito and @skoot I'll take this on. cc @gkorland @chayim

**Comment by Garito** [comment]
Thanks
Please: EXAMPLES!!!!  lots, covering all use cases

**Comment by chayim** [comment]
@sav-norem. Wanna?

**Comment by IvanRTO** [comment]
Is there any good resource to check while we are not getting an official documentation?
