### ISSUE TITLE
Feature request - support of union operation between graph objects

### ISSUE THREAD

**Issue by jeffrey82221** [redis/redis-py#2328]
Version: What redis-py and what redis version is the issue happening on?
all

Platform: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
all

Description: Description of your issue, stack traces from errors and code that reproduces the issue

In py2neo, the graph objects support union([`__or__`](https://github.com/py2neo-org/py2neo/blob/2e46bbf4d622f53282e796ffc521fc4bc6d0b60d/py2neo/data.py#L148)) operation, which allows nodes, edges, or paths to be merged into [`Subgraph`](https://github.com/py2neo-org/py2neo/blob/2e46bbf4d622f53282e796ffc521fc4bc6d0b60d/py2neo/data.py#L54). This allows [ipycytograph](https://github.com/cytoscape/ipycytoscape/blob/591458ca0817968fe01162720e6654913f63bfdc/ipycytoscape/cytoscape.py#L644), a graph visualization package, to support the visualization of graph objects in neo4j.  

Is it possible to make the redis-py to support union operation on graph objects and add subgraph object? So that I can add support of redisgraph into ipycytoscape.

**Comment by chayim** [comment]
@uglide WDYT?
