### ISSUE TITLE
Redis' object has no attribute 'getex'

### ISSUE THREAD

**Issue by tejasmkansara** [redis/redis-py#2330]
I am using Python with VS code to connect to a AWS Redis Elasticache Cluster (6.2 which has GETEX). I am able to connect to the cluster fine and make a get call. In another method I am able to make a setex call. However when I make a getex call with the code below :

```
def redis_getex(text):
    try:
        logging.basicConfig(level=logging.DEBUG)              
        if(redis.ping()):
            return_id = redis.getex(text, 100)
            if return_id is None:
                return None
            else:
                return return_id
        else:
            print("Redis Connection Failed")       
    except Exception as e:
        print(e)
        return None
```
I get a error message, ever though the I can find the reference to the getex call

`*'Redis' object has no attribute 'getex'*`
Any help would be great. TIA.

**Comment by chayim** [comment]
Can I ask what version of redis py you're using, and python?

Here's a working example on my local, validated with a few versions of python, but only the latest redis-py:

```
Python 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> r = redis.Redis()
>>> r.getex("text", 100)
>>> 
```

**Comment by tejasmkansara** [comment]
> Can I ask what version of redis py you're using, and python?
> 
> Here's a working example on my local, validated with a few versions of python, but only the latest redis-py:
> 
> ```
> Python 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import redis
> >>> r = redis.Redis()
> >>> r.getex("text", 100)
> >>> 
> ```

Python 3.10.4
redis-4.3.4
