### ISSUE TITLE
Commands folder not imported during installation

### ISSUE THREAD

**Issue by splurring** [redis/redis-py#2334]
I did `pip install redis`

However, the commands folder was never downloaded when I check the package. How do I add this?

**Comment by chayim** [comment]
@splurring can you share a bit more detail? What version of python were you using and what version of redis was installed via pip?

To get your python version:
``` bash
lapthetop: python -V
Python 3.10.5
```

To check your redis version:
```python
>>> import redis
>>> redis.VERSION
(4, 4, '0rc1')
```

Alternatively, you can check your redis version with:
```bash
pip freeze|grep redis
```

**Comment by chayim** [comment]
I think this refers to the old, yanked releases. Closing.
