### ISSUE TITLE
Please add the ability to chain multiple filters in a single redis search query

### ISSUE THREAD

**Issue by erniavr** [redis/redis-py#2336]
For example, let's say i want to search if a date is between of start/end date, i would like to have the ability in a single query.

**Comment by sav-norem** [comment]
Hey! RediSearch has this - for a date with Unix timestamps between would be `@date:[start end]` you can check out some more of the query syntax [here](https://redis.io/docs/stack/search/reference/query_syntax/) - you can also see at the bottom a table of how to do things like num less than 10 or greater than 20 - @num:[-inf (10] | @num:[(20 +inf]

We also have a Redis University course all about search if you're interested in trying out some more queries.
