### ISSUE TITLE
Search jsons

### ISSUE THREAD

**Issue by Garito** [redis/redis-py#2339]
Hi
I'm very frustrated right now cause I'm trying to use redisearch to search and aggregate data from visits

I'm logging the visits as a json like
``` json
{
  "id": "831da6fe-e4f9-41fc-a40c-cb0504748a32",
  "chain": 4,
  "contract": "0x2fee7637921dc489aeff49bc2cdfbe4a7bf9a1a2",
  "campaign": "campaign-1",
  "timestamp": 1659975071.253159,
  "account": "0x5c5b8df6a9e1b064b39c2e049a928224619c4682"
}
```
Now I want to get how many visits are for chain , contract  and campaign by month but there are no tutorials/help for python
It is possible to find info as commands but no for python

Should I drop redis because of the lack of documentation?
Sorry, but I am really frustrated

**Comment by chayim** [comment]
Hi @Garito, sorry to hear that you're frustrated - we definitely need to get better examples in place!

First - here's a direct link to the [JSON examples in our documentation](https://redis.readthedocs.io/en/stable/examples/search_json_examples.html).

Secondly, here's a link to another project we build, on top of redis-py called [redis-om-python](https://github.com/redis/redis-om-python). It exists, to help with some of these things.  Now note - redis-om-python currently doesn't have aggregations (we're working on it!), but it may meet your use case.

If you can help highlight what your specific frustrations have been along the way, it would really help me, help you and the community at large.

**Comment by Garito** [comment]
Forget it
I've moved to mongo
