### ISSUE TITLE
Cannot find reference `asyncio` in `__init__.pyi`

### ISSUE THREAD

**Issue by BabakAmini** [redis/redis-py#2347]
I'm using PyCharm and I added `aioredis` functionalities as suggested [here](https://github.com/aio-libs/aioredis-py#-aioredis-is-now-in-redis-py-420rc1-). Below is the error I get in the ide:

![image](https://user-images.githubusercontent.com/85762931/185748987-86780f5e-1bd3-4436-8ed7-5109a0bf59aa.png)

However, everything works fine, and there are no errors related to this issue.

**Comment by andrew000** [comment]
Just check the #2249 issue

**Comment by BabakAmini** [comment]
> Just check [#2249](https://github.com/redis/redis-py/issues/2249#issuecomment-1172943002)

I didn't see that issue. Thanks, it worked for me.
