### ISSUE TITLE
Breaking Change due to kombu dependent package

### ISSUE THREAD

**Issue by nsquaretologn** [redis/redis-py#2353]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: redis-4.4.0rc1

**Platform**: Ubuntu

**Description**: 
I am using django backend and celery. Redis is the queuing mechanism which we are using to connect both. When Django backend is of version redis-4.3.4 and celery worker code is of version redis-4.4.0rc1 or vice versa, there is a problem in UUID serialization. When uuid is sent from django backend to redis, it is received as dictionary due to this change. Existing production code may break due to this change if they have redis=* in pip file or when there is a version mismatch between django and celery resulting in 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2336, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/local/lib/python3.8/uuid.py", line 166, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'dict' object has no attribute 'replace'
```

This change versions 
[kombu](https://github.com/celery/kombu/pull/1575/files#diff-aa40c8921e5d5b60b3138527901dc51756c786e45d89c2c5700748c41863faccR48)
is not backward compatible. We need to de-serialize a UUID as UUID and not a dictionary

**Comment by sileht** [comment]
This should be reported on kombu, this is unrelated to redis-py.

**Comment by nsquaretologn** [comment]
Hi @dvora-h  I raised this issue in redis as there is a dependency in kombu. Please have the latest stable version of kombu as a dependency instead of pre-release version of it. Because of this redis pre-release package fails
