### ISSUE TITLE
"Failed parsing labels" on TimeSeries MGET

### ISSUE THREAD

**Issue by srbssv** [redis/redis-py#2376]
Hi! When launching MGET command:
`
redis.ts().mget('url=http://google.com')
`
It returns "redis.exceptions.ResponseError: TSDB: failed parsing labels". Maybe I should have used a correct syntax for filter, but I haven't found any example neither in docs nor in the source code. However, according to source code the filter parameter should be the same string as in TS.MGET FILTER key=value.

I'm using Docker container with Python 3.9.14 and redis-py 4.3.4. Redis server version is 6.2.6.
I input the same filter parameter using **TS.MGET FILTER url=http://google.com** through redis-cli, it parsed correctly and returned matching results.

**Comment by dvora-h** [comment]
@srbssv It's look like you pass the label and value in the same string, you need to split them
`redis.ts().mget('url'='http://google.com')`

**Comment by srbssv** [comment]
> @srbssv It's look like you pass the label and value in the same string, you need to split them `redis.ts().mget('url'='http://google.com')`

@dvora-h but this is syntactically incorrect. I tried using your example, Python returned: 
`
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
`
I tried using 
`
redis.ts().mget(url='http://google.com')
`
even though it is not implemented [in the source code](https://redis.readthedocs.io/en/stable/_modules/redis/commands/timeseries/commands.html#TimeSeriesCommands.mget). Furthermore, it just adds a **filter** string to a **params** list, so it's definitely shouldn't be splitted string, args/kwargs or anything else.

**Comment by srbssv** [comment]
> @srbssv It's look like you pass the label and value in the same string, you need to split them `redis.ts().mget('url'='http://google.com')`

@dvora-h but this is syntactically incorrect. I tried using your example, Python returned: 
`
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
`
I tried using 
`
redis.ts().mget(url='http://google.com')
`
even though it is not implemented [in the source code](https://redis.readthedocs.io/en/stable/_modules/redis/commands/timeseries/commands.html#TimeSeriesCommands.mget). Furthermore, it just adds a **filter** string to a **params** list, so it's definitely shouldn't be splitted string, args/kwargs or anything else.

**Comment by srbssv** [comment]
Solved the issue by putting query string into list:
`
redis.ts().mget(['url=http://google.com'])
`
Please, add this feature [into docs](https://redis.readthedocs.io/en/stable/redismodules.html#redis.commands.timeseries.commands.TimeSeriesCommands.mget), bc it is not clear what type of filter - str, dict or list - we should use.
