### ISSUE TITLE
pycharm is not detecting asyncio from redis

### ISSUE THREAD

**Issue by drlove2002** [redis/redis-py#2382]
**Version**: What redis-py and what redis version is the issue happening on?
> 4.3.4

**Platform**: What platform / version?
> Python 3.10 on Windows 10

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
Notice the screenshots I've uploaded. I'm trying to import the asyncio version of Redis But it's not working. I'm using virtual environment  and poetry as package manager. I installed redis-py using `poetry add redis[hiredis]`.
```py
import redis.asyncio as aioredis
```
![image](https://user-images.githubusercontent.com/39167433/190169907-0a93a9a8-3c3a-4c88-adf5-62b38aa6c7b5.png)
![image](https://user-images.githubusercontent.com/39167433/190170067-4ed5b731-1533-4a0e-b8f4-16d820d76eef.png)

**Comment by sav-norem** [comment]
Hi - just responded on Discord - I'm not sure if you're trying to use this unofficial Redis asyncio library - https://github.com/jonathanslenders/asyncio-redis or the aioredis library https://aioredis.readthedocs.io/en/latest/ ?  - But it's not being detected because there isn't a redis.asyncio from Redis

**Comment by drlove2002** [comment]
@sav-norem 
[Docs](https://redis.readthedocs.io/en/stable/examples/asyncio_examples.html) says that this library supports Asyncio for asynchronous functions.
Also [aioredis](https://github.com/aio-libs/aioredis-py) library GitHub page says it's been merged with redis-py library

**Comment by sav-norem** [comment]
Interesting - the more you know! Just tested and while VS code underlines it in yellow, it provides the autocomplete and runs everything just fine - sorry is this just that pycharm isn't recognizing it or is your code actually failing?
<img width="672" alt="Screen Shot 2022-09-16 at 1 48 40 AM" src="https://user-images.githubusercontent.com/22307550/190565735-4810e342-9f01-42c8-affa-d51646549ea5.png">

**Comment by nilueps** [comment]
Facing the same issue

![image](https://user-images.githubusercontent.com/55964909/198697133-863daeb3-dc24-426c-80d2-d73c381ada1b.png)

The package is there, but i guess it isn't being properly exported?
![image](https://user-images.githubusercontent.com/55964909/198696716-edae913c-3bfa-47fc-84ea-632e6b19c3e5.png)
