### ISSUE TITLE
Establishing a connection to Redis shouldn't depend on setting the client_name

### ISSUE THREAD

**Issue by KTAtkinson** [redis/redis-py#2384]
REPRODUCTION STEPS
1. Create a connection to Redis through Envoy proxy.
2. Issue command `SET key value`

RESULT
An error because [this line](
https://github.com/redis/redis-py/blob/bd0e8f26d8af5722a8b040bed6a75831bade81df/redis/connection.py#L736-L739) is setting the client name, if it's provided, but the call fails because the proxy doesn't understand the command. 

This is the error:
```
unsupported command 'CLIENT'
```
Notes
Thought the Redis proxy should understand this command and this is the root cause of the issue, establishing a connection shouldn't depend on the `CLIENT SETNAME` command succeeding. A warning is probably sufficient because client_name is merely something that is for the convenience of the administrator of Redis, not something that is necessary for Redis to work.

**Comment by sav-norem** [comment]
@KTAtkinson since your fix has been merged are you cool with the issue being closed?
