### ISSUE TITLE
`pipeline.execute()` - ResponseError with only the first failure is thrown, all failed commands should be returned

### ISSUE THREAD

**Issue by spicy-sauce** [redis/redis-py#2391]
While in `jedis` you get an array with the status of all the commands sent in the pipeline, in `redis-py` only the first failure is reflected in the `ResponseError` exception.
In case all the commands succeeded, we get an array of the length of the commands with True values in.
But when there's one or more errors, we don't get the array, but the `ResponseError`, for example:
```
redis.exceptions.ResponseError: Command # 1 (HSET bar 18.5 xxx) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value
```

This implementation prevents us from knowing what commands failed in this pipeline.

In the code itself, it seems that all the errors are accumulated, so this is available, but only the first is sent:
```
 # find any errors in the response and raise if necessary
  if raise_on_error:
      self.raise_first_error(commands, response)
```

I think that Redis clients should behave the same as much as possible.

**Comment by dvora-h** [comment]
@spicy-sauce We already supports this. You can set the `raise_an_error` flag in the pipeline execute to False and then it won't raise the error but include it in the response array.

Here is an example from the tests:
https://github.com/redis/redis-py/blob/master/tests/test_pipeline.py#L89
