### ISSUE TITLE
Confusing async RedisCluster Pipeline Behaviour 

### ISSUE THREAD

**Issue by NickG123** [redis/redis-py#2398]
**Version**: redis-py 4.4.0rc1, Redis 6.2.6 (AWS Elasticache) 

**Platform**: Python 3.10.7 on Alpine Linux v3.16

**Description**: 
The async RedisCluster Pipeline has potentially confusing behavior.  Observe the following code snippet:
```
async def foo(client):
    pipe = client.pipeline()
    await pipe.set("x", 1)
    print(await pipe.execute())
```
When run, this function will print `[]`, indicating that the pipeline execute call did not do anything (and the database is unchanged).  However no errors are raised.
Compare that to a "correctly" written function (the only difference being that `pipe.set` is not awaited)
```
async def foo(client):
    pipe = client.pipeline()
    pipe.set("x", 1)
    print(await pipe.execute())
```
Now when run, `[True]` is printed and the database is updated as expected

This is in contrast to the non RedisCluster version of the async Pipeline, which works correctly in both sample functions.

 As far as I can tell, this is a result of the fact that `pipe.set` and other pipeline actions return the pipeline for chaining, and [awaiting the ClusterPipeline calls initialize](https://github.com/redis/redis-py/blob/master/redis/asyncio/cluster.py#L1268), which resets the command stack.  

However, I feel this behavior is quite confusing, and either the first sample function should work correctly, or an error should be raised when `await pipe.set(...)` is called.

**Comment by utkarshgupta137** [comment]
I'm not sure how this can be fixed without breaking the chaining functionality or breaking the initialize functionality. IMO, it is up to the user to use the library correctly.

**Comment by NickG123** [comment]
I think my main concern with that statement is that the behaviour is _different_ for Cluster vs Non-Cluster.  

I'm certainly not familiar with the internals of the library - but it seems to me `await pipe` [in asyncio.cluster.ClusterPipeline](https://github.com/redis/redis-py/blob/master/redis/asyncio/cluster.py#L1345) calls initialize, while [in asyncio.client.Pipeline](https://github.com/redis/redis-py/blob/f492f85af723b277fa1ec99f01e6612e5d567b3f/redis/asyncio/client.py#L1080) it does not.

At the very least, seems like a warning if `initialize` is called when `self._command_stack` is not empty would be ideal.

**Comment by utkarshgupta137** [comment]
> 

The cluster version needs to initialize the cluster topology. The non-cluster version doesn't. By doing `await pipe` in cluster mode, you're ensuring that the topology is initialized before it is used.
You can create a PR for adding the warning.
