### ISSUE TITLE
why the default timeout here is a object() rather than a certain value?

### ISSUE THREAD

**Issue by xianglun918** [redis/redis-py#2405]
https://github.com/redis/redis-py/blob/b0883b791f95a595fae70bcedf3ad0f73c00e258/redis/connection.py#L178

**Comment by akx** [comment]
Because `SENTINEL` is always a known value that means "no value" and is not in the value range usually usable for timeouts.

`sock.settimeout()` supports `None` for "make it blocking", and any number for a timeout of that value.

**Comment by xianglun918** [comment]
Thanks for replying. I'm thinking if there is a way to set this timeout value without changing the source code.

**Comment by akx** [comment]
The default timeout is set with `Connection.socket_timeout`.

**Comment by xianglun918** [comment]
In line 224 and line 241 of connection.py, both `read` and `readline` function don't pass a socket timeout for the function   `self._read_from_socket`. Only the `can_read` function pass a socket timeout for the function. Won't this be a problem if the socket is readable at the time of getting a connection but stuck at `read` or `readline`?

**Comment by achimnol** [comment]
FYI) In this case, we could use `Enum` instead of `object` for strong typing of such "sentinel" constant patterns.

```python
import enum

class Sentinel(enum.Enum):
    TOKEN = 0

SENTINEL = Sentinel.TOKEN

def some_func(value: int | Sentinel) -> Any: ...

some_func(SENTINEL)
some_func(1234)
```

This allows type narrowing in `match-case` or `if isinstance()` checks to validate all possible code paths are exhaustively taken or not.
