### ISSUE TITLE
Error in documentation regarding initialisation of RedisBloom and TopK

### ISSUE THREAD

**Issue by radioactive11** [redis/redis-py#2415]
[Link to documentation](https://redis-py.readthedocs.io/en/stable/redismodules.html)

**Version**: redis-py version: 4.3.4 & redis-stack running on Docker (v6.2.7)

**Platform**: Python 3.10.6 on macOS
**Description**: Creating a bloom filter or TopK client according to the documentation throws an AttributeError

Sample:
```python
>>> import redis
>>> filter = redis.bf().create("bloom", 0.01, 1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'redis' has no attribute 'bf'
```

Solution:

```python
>>> from redis import Redis
>>> r = Redis()
>>> bf = r.bf()
>>> bf.create("bloom", 0.01, 1000)
True
```

I am facing similar issue with TopK filters as well.

I can raise a PR to solve this issue as well.

**Comment by sav-norem** [comment]
Hey - thanks for using the library! What a find - 

So I get the same error when I do
`python3
 import redis
 filter = redis.bf().create("bloom", 0.01, 1000)`

However when I use that syntax in a script it runs just as expected. Could you confirm for me if this syntax works for you in a script?

**Comment by radioactive11** [comment]
Hello @sav-norem 

Can you share me the exact script you are running in the terminal?

**Comment by sav-norem** [comment]
@radioactive11 woops! I forgot a key part of my code that works in a script - you sort of got it in the piece that works, but you need to set the `r = Redis()` (with any other connection parameters you want) and then can do `r.bf().create()` so for instance I have 
```
r = redis.Redis(
    host='localhost', 
    port=6379, 
    db=0, 
    decode_responses=True
)

r.bf().create('bloom', 0.01, 10000, noScale=True)
```

**Comment by radioactive11** [comment]
@sav-norem Exactly

But in the documentation, the sample that is provided doesn't instantiate a `Redis` object and directly tries to create an object of type `bf` which causes the error.

**Comment by sav-norem** [comment]
@radioactive11 yup! I've opened an issue with the docs team and we'll leave this open until that change in the docs gets out to the readthedocs page
