### ISSUE TITLE
asyncio pubsub check_health does not seem to raise error or trigger re-connection

### ISSUE THREAD

**Issue by repoww** [redis/redis-py#2417]
**Version**: 4.3.4

**Platform**: Ubuntu 20.04

**Description**: 
I am using Azure redis.
If I disconnect the network of the client machine in the middle of receiving messages, 
there is no error output, just always **None** message afterwards.
After I reconnect the network, re-connection and re-subscription are not triggered, no new message are received
```
import traceback
import asyncio
import redis.asyncio as aioredis

async def consumer(pubsub):
    await pubsub.subscribe('test')
    while True:
        try:
            message = await pubsub.get_message(
                ignore_subscribe_messages=True,
                timeout=1.0,
            )
            if message:
                print(f'Receive: {message}')
        except Exception:
            traceback.print_exc()
            await asyncio.sleep(1.0)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    redis = aioredis.from_url("rediss://",
                                            decode_responses=True,
                                            health_check_interval=2)
    loop.run_until_complete(consumer(redis.pubsub()))
```

**Comment by repoww** [comment]
it looks like pubsub health check do not have something like as below as in connection health check

https://github.com/redis/redis-py/blob/master/redis/asyncio/connection.py#L797
```
        if str_if_bytes(await self.read_response()) != "PONG":
            raise ConnectionError("Bad response from PING health check")
```

**Comment by repoww** [comment]
should we have something like a health_check_timeout to raise error or reconnect if we do not receive pong message for some time?

**Comment by gditu** [comment]
I have the same issue.
