### ISSUE TITLE
Asyncio examples

### ISSUE THREAD

**Issue by Dreamsorcerer** [redis/redis-py#2419]
Just some questions on the asyncio examples, which look a little odd to me.
Happy to make a PR if these are just mistakes.

https://redis-py.readthedocs.io/en/stable/examples/asyncio_examples.html?highlight=asyncio#Pub/Sub-Mode
> await asyncio.sleep(0.01)

Is there a reason to sleep for 10ms here?
If we just need to yield back to the event loop, then `asyncio.sleep(0)` is better.
But, why would we even need to yield here? Surely it has a chance to yield at `await channel.get_message(ignore_subscribe_messages=True)`.

> async with async_timeout.timeout(1):

What's the point of this timeout? The code just retries immediately, so doesn't it make more sense to just wait for the message to arrive without a timeout?

The examples also don't appear to `.unsubscribe()` and `.quit()`. Shouldn't they use `async with` to ensure they are shutdown correctly?

**Comment by repoww** [comment]
I think it is because we need to set `time_out` to make `get_message` a non blocking call, otherwise it keeps returning none.

**Comment by Dreamsorcerer** [comment]
Surely setting timeout would result in it keep returning `None`. The desired behaviour is surely to wait until a message is received and then return. I assume that this is what the library already does, so the timeout context manager should not be needed.

**Comment by repoww** [comment]
it looks like in the latest version, only if the `time_out` is set to None, `get_message(time_out=None)` is blocking call.
https://github.com/redis/redis-py/blob/master/redis/asyncio/client.py#L872

You are right, the example may not be up to date, we may only need following line if `time_out` is None
> async with async_timeout.timeout(1):
