### ISSUE TITLE
Could not connect to Redis at 127.0.0.1:6379: Connection refused

### ISSUE THREAD

**Issue by natanzi** [redis/redis-py#2434]
I have connected my simple python application to redis in local, while im going to run this code in Docker, I have the below error:

Could not connect to Redis at 127.0.0.1:6379: Connection refused

**Version**: pip install redis

**Platform**: UBNTU 20.04

my simple python code which put in docker:

try:
        # The decode_repsonses flag here directs the client to convert the responses from Redis into Python strings
        # using the default encoding utf-8.  This is client specific.
        r = redis.StrictRedis(host=redis_host, port=redis_port, password=redis_password, decode_responses=True)
        for key in r.scan_iter():
        
         print(key,r.get(key))

I should mention redis CLI is working in docker.

**Comment by dvora-h** [comment]
@natanzi Are there any more details you can provide?
I tried the exact same code and it worked for me.

**Comment by chayim** [comment]
Closing. This is the standard test case, and unresponsive
