### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable on search query

### ISSUE THREAD

**Issue by vampolo** [redis/redis-py#2436]
**Version**  
python redis 4.1.2 and redis server 6.2.6 with redissearch 2.4.11 and redisJSON 2.2.0 

**Platform** 
redislab.com running on GCP

**Description**: 

I think I found a race condition in the library. The use case is not common and that's probably why does not happen often.
I have a Redis search + Redis JSON cluster that keeps adding/removing documents to the index. So it might be that documents get removed while the query is being performed.
This is the stack trace I receive which shows a query that should have returned 2 documents, but the documents are none, this is probably because the documents where removed while the query was being performed

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/294496/198405673-22fa727c-0221-49cb-8b27-3bc8b9ee0ce4.png">

this seems to be a problem with redis-py that is not doing a null check in that map, but can also be a Redis Enterprise bug that is returning 2 total results. I have notified them about this problem as well. But I think that redis-py should account for this case regardless.

**Comment by dvora-h** [comment]
@vampolo Thanks for reporting this!
We have already encountered this problem and fixed it here https://github.com/redis/redis-py/pull/2270
The fix is included in version 4.4.0-rc1 which we will hopefully release soon as a stable (4.4.0) version.
