### ISSUE TITLE
Unable to install with hiredis option

### ISSUE THREAD

**Issue by m2b** [redis/redis-py#2445]
pip install redis[hiredis] return "no matches found: redis[hiredis]"

python version 3.8

pip install redis and pip install hiredis work

**Comment by chayim** [comment]
@m2b Can you help provide details on your platform? What OS (and arch)? Is there any output?

**Comment by timming-au** [comment]
@m2b Did you run the command in zsh? If so, try escaping the square brackets, like `pip install redis\[hiredis]\`, or use bash instead.

**Comment by wj4832** [comment]
@m2b I had the same problem and solved it. You can try this：
pipenv install "redis[hiredis]"
