### ISSUE TITLE
RedisCluster doesn't support dbs other than 0? 

### ISSUE THREAD

**Issue by jarrington-supernatural** [redis/redis-py#2450]
**Version**: What redis-py and what redis version is the issue happening on?
4.3.4 and 4.4.0rc3

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python 3.9, WSL2 Ubuntu

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
We are migrating from a single redis host to a redis cluster in elasticache. We are already using several dbs in the target instance and want to continue to do so. According to the RedisCluster class, we should be able to use a db other than 0 to connect. See https://github.com/redis/redis-py/blob/v4.4.0rc3/redis/cluster.py#L405-L413

However, actually using any db other than 0 results in an exception. See https://github.com/redis/redis-py/blob/v4.4.0rc3/redis/cluster.py#L512-L516

Is this intentional or am I missing something?

**Comment by Ernest0x** [comment]
From https://redis.io/docs/reference/cluster-spec/:

> Redis Cluster does not support multiple databases like the standalone version of Redis. We only support database 0; the [SELECT](https://redis.io/commands/select) command is not allowed.

**Comment by jarrington-supernatural** [comment]
In that case, we should update the documentation (especially [here](https://github.com/redis/redis-py/blob/v4.4.0rc3/redis/cluster.py#L405-L413)) to ensure this doesn't happen again.

**Comment by chayim** [comment]
@shacharPash Another one... this is in the documentation side.
