### ISSUE TITLE
Tag Filter not working correctly

### ISSUE THREAD

**Issue by waseem-sarwar** [redis/redis-py#2460]
**Version**: What redis-py and what redis version is the issue happening on?
redis-4.3.4

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python 3.8.10, Ubuntu 20.04, Windows Subsystem for Linux 2

I used the dataset https://github.com/redis-developer/redis-datasets/blob/master/user-database

My code was supposed to find users in Russia, China or Canada, within a certain latitude range, and female users.
```    
def query4(self):
        """
        Return the top 7 people based on their first_name for the female in China or Russia with the latitude between 40 and 55
        """
        search4 = self.redis.ft("queryredis4")
        index = IndexDefinition(prefix=['user:'])
        #SCHEMA = (TextField("first_name"), TextField("gender"), TagField("country"), NumericField("longitude"), NumericField("latitude"))
        #search4.create_index(SCHEMA, definition=index)            
        query4stmt = r"@country:{Russia|China}@latitude:[40 55]@gender:female" ##needs fixing
        #{China|Russia}@latitude:[40 55] @gender:female"
        result = search4.search(query4stmt)
        for doc in result.docs:
            print(doc)
        return result.docs #returns a list of document objects
```

This is declared inside a redis-client wrapper class. I have tested the query and the index on the CLI without changing the "query4stmt" and I get
``` 1) (integer) 181
 2) "user:5043"
 3)  1) "first_name"
     2) "Abbe"
     3) "last_name"
     4) "Follit"
     5) "email"
     6) "afollit1a@berkeley.edu"
     7) "gender"
     8) "female"
     9) "ip_address"
    10) "183.89.253.62"
    11) "country"
    12) "China"
    13) "country_code"
    14) "CN"
    15) "city"
    16) "Qianjin"
    17) "longitude"
    18) "130.375062"
    19) "latitude"
    20) "46.814102"
    21) "last_login"
    22) "1571449262"
 4) "user:2770"
 5)  1) "first_name"
     2) "Addi"
     3) "last_name"
     4) "Jaffra"
     5) "email"
     6) "ajaffrald@cnn.com"
     7) "gender"
     8) "female"
     9) "ip_address"
    10) "3.57.228.75"
    11) "country"
    12) "Russia"
    13) "country_code"
    14) "RU"
    15) "city"
    16) "Grazhdanskoye"
    17) "longitude"
    18) "135.0631263"
    19) "latitude"
    20) "48.4935627"
    21) "last_login"
    22) "1580591496"

``` 

Here I can see both countries. When I try to do the same with redis-py like above, I get:

`Document {'id': 'user:2851', 'payload': None, 'first_name': 'Mellicent', 'last_name': 'Windybank', 'email': 'mwindybanknm@oaic.gov.au', 'gender': 'female', 'ip_address': '135.29.167.193', 'country': 'Russia', 'country_code': 'RU', 'city': 'Sochi', 'longitude': '39.7451425', 'latitude': '43.5648626', 'last_login': '1587156956'}
Document {'id': 'user:5558', 'payload': None, 'first_name': 'Zsazsa', 'last_name': 'Gethen', 'email': 'zgethenfl@noaa.gov', 'gender': 'female', 'ip_address': '220.191.0.250', 'country': 'Russia', 'country_code': 'RU', 'city': 'Krasnoshchekovo', 'longitude': '82.756927', 'latitude': '51.6661372', 'last_login': '1591211339'}
Document {'id': 'user:5253', 'payload': None, 'first_name': 'Norma', 'last_name': 'Slopier', 'email': 'nslopier74@google.co.jp', 'gender': 'female', 'ip_address': '231.18.232.14', 'country': 'Russia', 'country_code': 'RU', 'city': 'Belyye Berega', 'longitude': '34.6649001', 'latitude': '53.2058', 'last_login': '1570052924'}`

I don't know why I am only getting entries for Russia. Please help. I have tried all tutorials I found about tag filters. 
Also, please excuse any shortcomings. It is my first time posting an issue on Github.

**Comment by waseem-sarwar** [comment]
It never seems to return more than 10 results. I've tried setting (0, 50) in the paging method of the Query object but it doesn't work. How do I set the limit for the search?

**Comment by chayim** [comment]
@oshadmi Can you help @waseem-sarwar with his query?

@waseem-sarwar there is a limit function, available on the aggregations, so that you can set a limit. Are you using this with redis-stack?

**Comment by oshadmi** [comment]
@waseem-sarwar The default limit for RediSearch is 10
From https://redis.io/commands/ft.search/

> LIMIT first num
limits the results to the offset and number of results given. Note that the offset is zero-indexed. The default is 0 10, which returns 10 items starting from the first result. You can use LIMIT 0 0 to count the number of documents in the result set without actually returning them.

Another place [here](https://github.com/redis/redis-py/blob/master/tests/test_search.py#LL138C7-L138C7)

Try changing the offset and the result count using `paging(<offset>, <count>)`
Such as [here](https://github.com/redis/redis-py/blob/f06f3db647c81bc24fa9bdad33822ca6175c32eb/tests/test_search.py#L340)

@nermiller Is it documented?
