### ISSUE TITLE
mypy: error: Module 'redis' has no attribute 'RedisCluster'

### ISSUE THREAD

**Issue by srmrz** [redis/redis-py#2461]
When I run `mypy`, I see the following:

```
error: Module 'redis' has no attribute 'RedisCluster'
```

What does my import look like?

```
from redis import Redis, StrictRedis, RedisCluster
```

**Version**: What redis-py and what redis version is the issue happening on?
4.3.4

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python 3.8, macOS

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
run mypy on a project with the import above.

**Comment by uglide** [comment]
Hello @srmrz 
Thanks for the bug report.  It's `mypy` bug. More info here  https://github.com/python/mypy/issues/3115
