### ISSUE TITLE
Scheme validation introduced in #2343 is a breaking change for unix: scheme

### ISSUE THREAD

**Issue by kalekseev** [redis/redis-py#2489]
Unix scheme with single scheme was working as expected with single slash

```
ipdb> url = 'unix:/redis/redis.sock?db=4'
ipdb> urlparse(url)
ParseResult(scheme='unix', netloc='', path='/redis/redis.sock', params='', query='db=4', fragment='')
```

Error message that says `unix://` is confusing and may lead to errors like that (first directory become netloc):
```
ipdb> url = 'unix://redis/redis.sock?db=4'
ipdb> urlparse(url)
ParseResult(scheme='unix', netloc='redis', path='/redis.sock', params='', query='db=4', fragment='')
```

This looks like a breaking change and shouldn't be introduced in minor version 4.4.0.

**Comment by chayim** [comment]
I definitely see that this has broken the single slash case. However, all of the documentation, tests, examples, and code point to "unix://".  I'm unaware of a valid protocol that is single slashed - so I'm reticent to call this a bug.

**Comment by kalekseev** [comment]
Unfortunately there are libraries built on a single slash assumption, eg https://github.com/epicserve/django-cache-url/blob/6742a0db5cb37551aba3f41552bc55ad19ef0985/django_cache_url/__init__.py#L102

My project was exposed to this through `environs[django]` dependency, see how django-cache-url replaces 3 slashes with a single one:

```
In [1]: from django_cache_url import parse

In [2]: import os

In [3]: parse(os.environ['CACHE_URL'])
Out[3]:
{'BACKEND': 'django.core.cache.backends.redis.RedisCache',
 'LOCATION': 'unix:/redis/redis.sock?db=0'}

In [4]: os.environ['CACHE_URL']
Out[4]: 'redis:///redis/redis.sock/0'
```

That's definitely django-cache-url bug but it was unveiled by redis-py update so I consider it a breaking change.

**Comment by kalekseev** [comment]
PR with django-cache-url fix https://github.com/epicserve/django-cache-url/pull/24

**Comment by chayim** [comment]
I understand that it worked - but definitely wasn't intended, but it's been documented as such (i.e double slashes) forever. I don't think I'd categorize this as a bug, though it's definitely breaking behaviour. Checking back, I see that this has been documented this way for at least 4 years.

I'm willing to live with this one. But, I am sorry it broke things for some projects.
