### ISSUE TITLE
EVAL_RO, EVALSHA_RO doesn't get routed to replicas

### ISSUE THREAD

**Issue by zakaf** [redis/redis-py#2490]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
redis-py 4.4.0, redis 7.0

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
python 3.11.0 on Mac

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
Commands like `EVAL_RO` and `EVALSHA_RO` are always directed to the master, even though they can be routed to replicas as they are read-only commands

I suspect the cause to be READ_COMMANDS missing few read only commands
 https://github.com/redis/redis-py/blob/6219574b042a6596b150ca8248441198f01f8c87/redis/commands/cluster.py#L49-L93

Can i make a PR to add those commands or is there any other rationale that prevents adding EVAL_RO and EVALSHA_RO into READ_COMMANDS?

**Comment by chayim** [comment]
@zakaf The reason these aren't in the READ_COMMANDS list is purely historic - they came after the list, in the redis 7 release. We'd love a PR - especially if you're working on and validating the behaviour :D Since you offered.. I even assigned it to you!

**Comment by bluecrabs007** [comment]
Since the fix for this is merged, is this statement `The following commands are not supported: - EVAL_RO - EVALSHA_RO` in https://github.com/redis/redis-py/blob/master/docs/lua_scripting.rst#cluster-mode still valid?
