### ISSUE TITLE
Can not get all keys in redis cluster

### ISSUE THREAD

**Issue by nmtruong93** [redis/redis-py#2498]
**Version**: 4.4.0

**Platform**: Python 3.8.10 on Mac M1 Montery 12.6

**Description**: 
I tried 2 Redis client packages: **redis 4.4.0** and **redis-py-cluster 2.1.3**

- The code for redis 4.4.0
```
def connect_to_redis_cluster():
    """
    Connect to redis cluster

    :return: object, redis cluster connection
    """
    connection = RedisCluster(
        startup_nodes=[ClusterNode(RedisConfig.server.get('host'), RedisConfig.server.get('port'))],
        decode_responses=True, require_full_coverage=False)

    if connection.ping():
        logger.info("Redis connected")

    return connection
```

- The code for redis-py-cluster 2.1.3:
```
def connect_to_redis_cluster():
    """
    Connect to redis cluster

    :return: object, redis cluster connection
    """
    connection = RedisCluster(
        startup_nodes=[{"host": RedisConfig.server.get('host'), "port": RedisConfig.server.get('port')}],
        decode_responses=True, skip_full_coverage_check=True)

    if connection.ping():
        logger.info("Redis connected")

    return connection
```
However, when I try to get pattern of keys, **the results in redis 4.4.0 are less than redis-py-cluster. It means redis 4.4.0 can not get all keys from the cluster.**
```
len(connection.keys('pfs:aiml:*:status'))
# redis 4.4.0 output: 18
# redis-py-cluster output: 71
```
I tried many ways, including using Redis, StrictRedis classes, add more startup nodes to params startup_nodes, but the results of redis 4.4.0 are always less than redis-py-cluster. 

Please help me solve this problem. Thank you.

**Comment by dvora-h** [comment]
@nmtruong93 Are all the 71 keys you get with redis-py-cluster in the same node?
If not - this is the expected behavior of the `keys` command, to return the keys from the node you sent the command to.if you want to get the keys from all the nodes you can specify the target_nodes to `primaries` or `all`:
`connection.keys('pfs:aiml:*:status', target_nodes="primaries")`

**Comment by nmtruong93** [comment]
@dvora-h thanks, you solved my problem!
