### ISSUE TITLE
Asyncio get_event_loop without current loop deprecated

### ISSUE THREAD

**Issue by pintert3** [redis/redis-py#2525]
**Version**: 4.4.0

**Platform**: 3.10, Arch Linux

**Description**:

Asyncio gives a DeprecationWarning because of line *535* of connection.py:
```python
loop = asyncio.get_event_loop()
```

It says there's no current event loop. From my little research it's expected that this line will throw an error in python 3.11 when called without a running loop in the current thread, according to [this](https://stackoverflow.com/a/73367187/8745311) stackoverflow answer.

**Comment by dvora-h** [comment]
@pintert3 Thanks for reporting this. I fixed it in #2530
