### ISSUE TITLE
Add support for Host port remapping with Clustering

### ISSUE THREAD

**Issue by GerhardPowell** [redis/redis-py#2564]
We have a redis cluster loaded on Azure and we want to connect to it using port forwarding.
All the pods are according to redis-py on localhost with different ports.
But according to redis the pods are on different IPs.
So, there is a mismatch which prevents us from using redis-py with port forwarding.

It is supported on redis-py-cluster:
https://redis-py-cluster.readthedocs.io/en/stable/client.html#host-port-remapping
but not redis-py (4.4.2).

Redis-py-cluster is not updated anymore because it has been integrated into redis-py.
I would really appreciate it if you could add this missing feature to redis-py.

Thank you!

**Comment by daveisfera** [comment]
`address_remap` was [added in 4.5.5](https://github.com/redis/redis-py/releases/tag/v4.5.5)

**Comment by dvora-h** [comment]
Done in #2726
