### ISSUE TITLE
Unable to delete key with []-," even if escaped

### ISSUE THREAD

**Issue by goldyfruit** [redis/redis-py#2594]
**Version**: 
redis==4.5.1
redis_version:6.2.6

**Platform**: Docker container on Fedora 37

**Description**:

I'm not able to delete a key using the Python library but it works fine using the CLI.

The key name is ` ["", "10000000cb76c87c", "10000000cb76c87c-mq"]` (https://docs.vernemq.com/configuring-vernemq/db-auth#redis) which become `"[\"\", \"10000000ac8aef64\", \"10000000ac8aef64-mq\"]"` when escaped.

Using the CLI it works without any trouble:
```shell
127.0.0.1:6379> DEL "\[\"\"\, \"10000000ac8aef64\"\, \"10000000ac8aef64\-mq\"\]"
(integer) 1
```

But when using the Python library, nothing is deleted (and I got no error).
```python
key = "[\"\", \"10000000ac8aef64\", \"10000000ac8aef64-mq\"]"
client.delete(key)
```

The `client.get()` is working though, I'm able to retrieve the key using the same format as above.
```python
key = "[\"\", \"10000000ac8aef64\", \"10000000ac8aef64-mq\"]"
client.get(key)
b'{"passhash": "xxxx", "subscribe_acl": [{"pattern": "status"}, {"pattern": "configuration"}], "publish_acl": [{"pattern": "configuration"}, {"pattern": "/status"}]}'
```

Any idea how I could remove this key?

Thanks

**Comment by XChikuX** [comment]
Strange. Delete Works for me

```
    async def delete_user(self, pk: str) -> str:
        """This function deletes a user"""
        success = await RedisUser.delete(pk)
        if not success:
            raise RuntimeError("User does not exist")
        return pk
```

I use this function all the time. Double check please!

**Comment by goldyfruit** [comment]
I double checked few times before opening this issue :+1: 

`client.delete()` works with other keys but not with this specific one I posted.

**Comment by goldyfruit** [comment]
The key was deleted but automatically recreated by something in my code... Adding an `id` to the key made me realised this...

Sorry for the noise :+1:
