### ISSUE TITLE
TS.ADD overwrites the older timestamp instead of appending the new ones.

### ISSUE THREAD

**Issue by grestonian** [redis/redis-py#2595]
**Version**: redis-py: 4.5.1 and redis/redis-stack-server:6.2.6-v4,

**Platform**: windows 10: docker container

**Description**: I'm using timeseries module in redis.
when I run TS.ADD(), the new timestamps are not being **appended** to the key, but overwriting the previously added timestamp and value pair.
Am I missing something here? Isn't timestamps supposed to be appended, else it doesn't make sense to call it time **series**.
How can I get a list rather that single timestamp value pair for a key?
Thanks

```
127.0.0.1:6379> TS.ADD demokey * 23
(integer) 1677123167504
127.0.0.1:6379> TS.ADD demokey * 27
(integer) 1677123180472
127.0.0.1:6379> TS.GET demokey
1) (integer) 1677123180472
2) 27
```

as you can see above, I added two values in demokey, however, TS.GET returns only the latest one.

**Comment by chayim** [comment]
@grestonian [TS.GET](https://redis.io/commands/ts.get/) retrieves only the last sample. Perhaps your use case needs one of the range based commands such as [TS.RANGE](](https://redis.io/commands/ts.mget/)).

[Try this link](](https://redis.io/commands/ts.get/)) to a redis-py example, using RedisTimeSeries. It think it's what you're looking for.
