### ISSUE TITLE
Add support for JSON commands in Async Cluster

### ISSUE THREAD

**Issue by baltika10** [redis/redis-py#2600]
**Version**:  4.5.1
**Platform**:  Python 3.11 on Windows 11

```python
from redis.asyncio.cluster import RedisCluster
client = RedisCluster()
await client.json().get("test")
```
raises `AttributeError: 'RedisCluster' object has no attribute 'json'`

Actually, it's a duplicate of #2234  which was closed without real solution

**Comment by kuza55** [comment]
Hi,

This issue does not seem fully resolved, this code still crashes:

```
import asyncio
from redis.asyncio.cluster import RedisCluster  # type: ignore
import redis.asyncio as redis  # type: ignore

async def main():
    r = RedisCluster.from_url("redis://localhost:16379/0")
    p = r.pipeline()
    p.json().set("blah", ".", 1)
    await p.execute()
    print("done")

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
asyncio.get_event_loop().run_until_complete(main())
```

I hacked up some changes that seem to make this pass, but it's obviously not what it should look like and I don't know if there are other situations that could be problematic: https://github.com/redis/redis-py/commit/cf3bcdc4e4693ff1daf2334a61fb3f8938e61fb3
