### ISSUE TITLE
Expose `redis.parsers` to be importable

### ISSUE THREAD

**Issue by cunla** [redis/redis-py#2658]
Expose `redis.parsers` to be importable

**Version**: 
5.0.0b1

**Platform**: 
python3.11/mac

**Description**: 
`BaseParser` was moved from `redis.connection` to `redis.parsers.base` which is not exposed.
Sometimes it is required.

**Comment by dvora-h** [comment]
We now (in 5.0.0rc2) expose it in `redis._parsers` but you need to be carefull when using it because as you can see (with the _) we now consider _parsers as private code - that means we can break it anytime.
