### ISSUE TITLE
ElastiCache IAM connection example in docs reference non-existent function

### ISSUE THREAD

**Issue by nint8835** [redis/redis-py#2676]
**Version**: N/A

**Platform**: N/A

**Description**: The "Connecting to a redis instance with ElastiCache IAM credential provider." example in the [connection examples](https://redis.readthedocs.io/en/stable/examples/connection_examples.html) in the documentation references a function, `generate_iam_auth_token`, on the ElastiCache boto3 client. However, as far as I can tell, this function does not exist.

- It does not appear in the list of supported methods on the ElastiCache client in the [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elasticache.html)
- Performing a [GitHub code search for this function](https://github.com/search?q=.generate_iam_auth_token+(language%3A%22Jupyter+Notebook%22+OR+language%3A%22Python%22)&type=code) only returns the example from the docs in this repo and a few of it's forks
- Attempting to access the function on the latest version of boto3 (`1.26.101`) raises an AttributeError:
  ```python
   >>> import boto3
   >>> ec_client = boto3.client("elasticache", region_name="ca-central-1", aws_access_key_id="test", aws_secret_access_key="test")
   >>> ec_client.generate_iam_auth_token
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/Users/riley/.pyenv/versions/redis-testing/lib/python3.10/site-packages/botocore/client.py", line 876, in __getattr__
       raise AttributeError(
   AttributeError: 'ElastiCache' object has no attribute 'generate_iam_auth_token'
   ```

**Comment by dvora-h** [comment]
Fixed in #2702
