### ISSUE TITLE
Can I create a redis database by string name than number? It seems like the official redis document support creating a redis database by name.

### ISSUE THREAD

**Issue by yingshaoxo** [redis/redis-py#2678]
Official Link:
https://docs.redis.com/latest/ri/using-redisinsight/add-instance/#:~:text=A%20name%20for%20your%20Redis%20database

What I want:
```python
redis.Redis(host=redis_host_URL, port=6379, name="a_database_name")
```

___

If it supports string name, then I think you guys should change the readme example, because it is stupid. Who would use numbers as name, if it does not have meanings for human?

**Comment by dvora-h** [comment]
No, in redis-py you cann't create a database by name
