### ISSUE TITLE
Support ACL LOG: Added entry ID, timestamp created, and timestamp last updated.

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#2686]
Documented [here](https://redis.io/commands/ACL-LOG).

**Comment by SoulPancake** [comment]
@chayim I think the current code should be able to handle the addition of 'entry-id', 'timestamp-created', and 'timestamp-last-updated'

The function pairs_to_dict() will transform the list of key-value pairs into a dictionary without any constraints on specific keys. This means it will process any key-value pair in the log, regardless of what the key is.
