### ISSUE TITLE
Support XINFO STREAM: Added the `active-time` field, and changed the meaning of `seen-time`.

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#2688]
Documented [here](https://redis.io/commands/XINFO-STREAM).

**Comment by SoulPancake** [comment]
This too should already be supported with the existing code, Is there something else specific needed to be done here? @chayim

**Comment by chayim** [comment]
Correct. I unleashed a *tonne* of auto generated across multiple repositories. Apologies on the false positives.
