### ISSUE TITLE
Redis is not usable with Python 3.11.3, which was recently released

### ISSUE THREAD

**Issue by mdnorman** [redis/redis-py#2700]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?

`redis==4.5.4`

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

Python 3.11 on Linux

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

I attempted to upgrade my system to Python 3.11.3 since the Docker image was updated yesterday. However, `async-timeout` silently failed to install due to a requirement in the Redis [setup.py](https://github.com/redis/redis-py/blob/master/setup.py#L37) that made its way into my Pipfile.lock.

**Comment by sileht** [comment]
Maybe related to https://github.com/redis/redis-py/pull/2699

**Comment by mdnorman** [comment]
I should have mentioned that the redis code seems to still attempt to import the library, so loading the redis library fails without this library.
