### ISSUE TITLE
redis-py issue 

### ISSUE THREAD

**Issue by yhgon** [redis/redis-py#2712]
**Version**: What redis-py and what redis version is the issue happening on?
```
redis : 3.5.3 
redisearch : 2.1.1 
```
redis cli works well and work within python as below : 

```
$ redis-cli PING
PONG

$ python
Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> r = redis.Redis(host='localhost', port=6379, db=0)
>>> r.set('foo', 'bar')
True
>>> r.get('foo')
b'bar'
```

with configure 
```
REDIS_HOST=192.168.0.30
REDIS_PORT=6379
REDIS_PASSWORD=
WIPE_REDIS_ON_START=True
MEMORY_INDEX=auto-gpt
```

it have error 
```
Continue (y/n): y
Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
Using memory of type:  LocalCache
Using Browser:  chrome
```

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

```
python 3.10.10
Ubuntu 20.04 on WSL2 
conda : 23.3.1 
```

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

**Comment by chayim** [comment]
Can you please be more descriptive? What's the issue you're seeing? What Redis are you running?

If you're trying to use redisearch, I highly recommend the [redis-stack-server docker](https://hub.docker.com/r/redis/redis-stack-server). Note - you should be running at least Python 3.7, and redis-py 4.4.  

Python 3.5 is no longer supported (by Python.org), nor here.

**Comment by agronholm** [comment]
Are you seeing some error because you don't have redis-py installed? Why are you reporting that as a bug here?

**Comment by woutdenolf** [comment]
Seems like the error message comes from [auto-gpt](https://github.com/Significant-Gravitas/Auto-GPT/issues/2759)? I assume you are trying to use auto-gpt [without docker](https://docs.agpt.co/setup/#run-without-docker)? The docs don't seem to mention how to actually install all dependencies. Try `pip install -r requirements.txt`.

In any case, this is not a `redis-py` issue. Use the [auto-gpt issue tracker](https://github.com/Significant-Gravitas/Auto-GPT/issues) if you have more questions.
