### ISSUE TITLE
Is there any well defined range/upper bound on vector dimension(DIM) value while creating a vector index.

### ISSUE THREAD

**Issue by bhavishpahwa** [redis/redis-py#2776]
Hey does there exist a range or an upper bound on the value the DIM parameter can take, while intialising/creating a vector index/ field using redis vector database. 
References:- https://redis-py.readthedocs.io/en/stable/examples/search_vector_similarity_examples.html#Index-Creation, https://redis.io/docs/stack/search/reference/vectors/#create-a-vector-field

**Comment by dvora-h** [comment]
It's better to ask this question in the RediSearch repo https://github.com/RediSearch/RediSearch
