### ISSUE TITLE
[Message Duplication] Subscribe channel A after psubscribing pattern P (A belongs to P)

### ISSUE THREAD

**Issue by AllenSun1024** [redis/redis-py#2784]
**Version**: redis 4.5.5

**Platform**: Ubuntu 20.04

**Description**: Will subscribing channel A after psubscribing pattern P (A belongs to P) lead to message duplication?

**Comment by dvora-h** [comment]
@AllenSun1024 Yes, You will receive 2 messages, 1 for the channel subscription (with the message type "message") and 1 for the pattern subscription (with the message type "pmessage")
