### ISSUE TITLE
I am getting error while running command `invoke devenv `

### ISSUE THREAD

**Issue by codal-smit** [redis/redis-py#2791]
**Version**: Latest GitHub branch

**Platform**: Ubuntu 20.04.5 LTS

**Docker Version**:  24.0.2

**Description**:  Unable to setup devenv 
`Error response from daemon: No such container: master`
`.`
`.`
`usage: tox devenv [-h] [--colored {yes,no}] [--exit-and-dump-after seconds] [-c file] [--workdir dir] [--root dir]`
` [--runner {virtualenv}] [-v | -q] [-e ENV] [--skip-env re] [--result-json path] [--hashseed SEED]`
 `[--discover path [path ...]] [--no-recreate-pkg] [--version] [--no-provision [REQ_JSON]] `
`[--no-recreate-provision] [-r] [-x OVERRIDE] [--docker-dont-stop CONTAINER][path]`
`tox devenv: error: argument -e: expected one argument`

**Comment by dvora-h** [comment]
You need to call devenv with invoke `invoke devenv`
