### ISSUE TITLE
Add support for triggered functions

### ISSUE THREAD

**Issue by uglide** [redis/redis-py#2808]
Add support for [triggered functions](https://github.com/RedisGears/RedisGears/blob/master/docs/commands.md)

- [ ] RG.FUNCTION LOAD
   API for this command should support loading the function content from the file.
- [ ] RG.FUNCTION DEL
- [ ] RG.FUNCTION LIST
- [ ] RG.FCALL
- [ ] RG.FCALLASYNC

**Comment by dvora-h** [comment]
done in #2861
