### ISSUE TITLE
Non blocking redis asyncio pubsub?

### ISSUE THREAD

**Issue by l3keboy** [redis/redis-py#2820]
**Version**: Latest stable

**Platform**: Windows 11 - Python 3.10.2

**Description**: I am trying to configure redis for pubsub across two python scripts. This needs to be done asynchronously for other code to run. When i use the redis.asyncio and user pubsub.listen() this still blocks the rest of my code.

Right now i have the following:
```
        async for message in pubsub.listen():
            if message["type"] == "message":
                print(message)
```

I also tried the example [here](https://redis-py.readthedocs.io/en/stable/examples/asyncio_examples.html#Pub/Sub-Mode) with the same result (blocking the rest of the code)

Can someone help me? Is this even possible? Am I doing something wrong? Do i need another library for this?

Thanks in advance!

**Comment by nsteinmetz** [comment]
Reading https://redis-py.readthedocs.io/en/stable/advanced_features.html#publish-subscribe :

> Older versions of redis-py only read messages with pubsub.listen(). **listen() is a generator that blocks until a message is available.** If your application doesn’t need to do anything else but receive and act on messages received from redis, listen() is an easy way to get up an running.

So you should move away from `listen()` to something else I think.

**Comment by l3keboy** [comment]
Yes, that is what I figured. My question was more, how to do this and what I do need to use.

**Comment by l3keboy** [comment]
I have found the solution by creating a asyncio task and using pubsub.run(). I will close this issue!
