### ISSUE TITLE
address_remap stuck in loop with Amazon MemoryDB for Redis

### ISSUE THREAD

**Issue by daveisfera** [redis/redis-py#2834]
**Version**: 4.6.0 and 6.2

**Platform**: Python 3.9.16 on Debian Bullseye

**Description**: I'm trying to use `RedisCluster` to access `Amazon MemoryDB for Redis` using SSH port forwarding and it connects, but the `MOVED` causes it to use a non-forwarded port. I tried using `address_remap` so it would use the forwarded port but it is called over and over and never finishes the connection.

**Comment by arthosdevelops** [comment]
@daveisfera Were you able to find a fix for this? We are facing a similar issue of address_remap being called over and over again and eventually not working

**Comment by daveisfera** [comment]
Unfortunately, no

**Comment by paulchaum** [comment]
I've managed to get the connection to a MemoryDB + SSH tunnel working on my local machine.

Here's the command to open the SSH tunnel:
```shell
ssh -i "</path/to/keypair_private.pem>" -N -L 6379:{memory_db_host}:6379 ec2-user@<ec2_host>
```
_(Note : adapt `ec2-user`, depending on your the OS on your EC2)_

And here is the python code to connect to it:
```python
# pip install redis
import os
from typing import Tuple

from redis import RedisCluster

if os.environ.get("ENVIRONMENT", "LOCAL") == "LOCAL":
    REDIS_HOST = "127.0.0.1"
else:
    REDIS_HOST = "{memory_db_host}"  # change here


def address_remap(*args, **kwargs):
    """
    Function to force the host & port to 127.0.0.1:6379 (= ssh tunnel)
    Otherwise, redis.RedisCluster will forward the host at the MemoryDB host instead of the local ssh tunnel
    Warning : Doesn't work with "localhost" instead of "127.0.0.1"
    """
    return REDIS_HOST, 6379


redis_client = RedisCluster(
    host=REDIS_HOST,
    port=6379,
    username="{username}",  # change here
    password="{password}",  # change here
    decode_responses=True,
    ssl=True,
    address_remap=address_remap,
)

# Ping
print(redis_client.ping())

# Insert key
r = redis_client.hset("foo", mapping={"bar": "baz"})
print("Set response : %s" % r)

# Get key
r = redis_client.hgetall("foo")
print("Get response : %s" % r)
```

**Comment by daveisfera** [comment]
I just tested this with 5.0.4 and `address_remap` is 16k times but it does appear to return now and does technically work

**Comment by daveisfera** [comment]
Tested again with 5.0.8 and I'm able to connect to `Amazon MemoryDB for Redis` using SSH port forwarding through a bastion host
