### ISSUE TITLE
ZRANK withscore keyword argument causes wrong number of arguments exception

### ISSUE THREAD

**Issue by cnorlander** [redis/redis-py#2845]
**Version**: 
redis-py: 4.6.0
redis: 7.2-rc-3 (7.1.242) also 7.0.11

**Platform**: 
Ubuntu 22.04.2 LTS running in WSL2
Also Tested in Docker Container: python:slim

**Description**: 
This one is quite odd to me: passing the keyword argument "withscore" when calling zrank on the Redis object causes wrong number of arguments exception. This should be possible [according to the docs](https://redis-py.readthedocs.io/en/stable/commands.html#redis.commands.core.CoreCommands.zrank)

I have created the following example script which can reproduce the problem:

```
import redis

r = redis.Redis(host='localhost', port=6379, decode_responses=True)
r.zadd("myzset", {"tim": 12312312})
r.zadd("myzset", {"jim": 12342344})
r.zadd("myzset", {"james": 11232311})

print(r.zrange("myzset", 0, 9, True, withscores=True))
print(r.zrank(name="myzset", value="tim"))
print(r.zrank(name="myzset", value="tim", withscore=True))
```

will throw:
```redis.exceptions.ResponseError: wrong number of arguments for 'zrank' command```

Pycharm seems to indicate the "withscore" keyword is an unexpected argument as well so as a sanity check I went to the definition of the command in core.py using the go to declaration tool as well as printed it out with inspect.getsource() and both show the method has having a withscore keyword argument with a default of False.

```
def zrank(
        self,
        name: KeyT,
        value: EncodableT,
        withscore: bool = False,
    ) -> ResponseT:
        """
        Returns a 0-based value indicating the rank of ``value`` in sorted set
        ``name``.
        The optional WITHSCORE argument supplements the command's
        reply with the score of the element returned.

        For more information see https://redis.io/commands/zrank
        """
        if withscore:
            return self.execute_command("ZRANK", name, value, "WITHSCORE")
        return self.execute_command("ZRANK", name, value)
```

EDIT: running ```r.execute_command("ZRANK", "myzset", "tim", "WITHSCORE")``` and a follow up running the same command in redis-cli seems to indicate the issue is actually redis its self not supporting the command. Question is why is this available now in redis-py, in the redis-py and redis commands documentation despite it not being supported even in the newest release candidate for redis 7.2?

**Comment by dvora-h** [comment]
Now that redis 7.2 released it's supported, but you are right, we need to add a note next time not to use this kind of changes before the release
