### ISSUE TITLE
mget commands should be blocked/raise Exception when executed on RedisCluster 

### ISSUE THREAD

**Issue by mpmX** [redis/redis-py#2862]
**Version**: 4.6.0

**Platform**: Linux

**Description**: Apparently, commands with multiple keys as input are not supported in redis cluster. Thus, RedisCluster should not accept such commands.

It looks like the following command only returns values for keys found in the first keys' node. 

`RedisCluster(...).mget(["key1", "key2", "key3"])`

**Comment by daveisfera** [comment]
It works as long as all keys are on the same key slot, and there's `mget_nonatomic` that works even if that's not the case (it breaks up the commands and combines the results after receiving the responses
