### ISSUE TITLE
Bulk load missing in merged Redisgraph functionalities

### ISSUE THREAD

**Issue by LGTiscar** [redis/redis-py#2881]
**Description**: Due to the end of RedisGraph we need to migrate a RedisGraph microservice we have to this library, redis-py. I have checked that you guys have merged some functionalities inside commands.graph but not the Bulk load from RedisGraph (https://github.com/redis/redis-py/blob/a532f89adcd5b790e2811588a2d7c34a79b095d5/redis/commands/graph/commands.py#L124-L129) which we used to build the database based on CSVs...

**Question**: Is there any workaround that we can use to maintain this functionality?

Thanks in advance.

**Comment by chayim** [comment]
Hi @LGTiscar there's actually a separate project for this. https://github.com/RedisGraph/redisgraph-bulk-loader

**Comment by LGTiscar** [comment]
Ah then, that project will remain maintained even though RedisGraph project is ended, @chayim?

**Comment by chayim** [comment]
Great question - @uglide WDYT?

**Comment by uglide** [comment]
Hi @LGTiscar 

We will review reported issues and add security fixes in RedisGraph repo till December 31, 2024. There is no plan to maintain or add new features to [redisgraph-bulk-loader](https://github.com/RedisGraph/redisgraph-bulk-loader). Still, it's an open-source project anyone can fork and continue development. That's the beauty of Open Source: no matter what happens, you can impact the future of the project you rely on.

**Comment by LGTiscar** [comment]
Thank you both, then! @uglide @chayim
