### ISSUE TITLE
Resolving ImportError: Module "redis.connection" does not define a "HiredisParser" attribute/class

### ISSUE THREAD

**Issue by jacklinke** [redis/redis-py#2895]
[Multiple](https://github.com/redis/redis-py/issues/2892#issuecomment-1678962282) [people](https://github.com/redis/redis-py/issues/2892#issuecomment-1680254583) have commented on #2892 regarding the error `ImportError: Module "redis.connection" does not define a "HiredisParser" attribute/class`, but this does not seem to be a Python 3.7 issue. As shown in that issue, it is present for at least 3.7 and 3.9. I experienced it with 3.11.

For anyone dealing with the issue: well, it looks like that error message is spot-on.

*In order to support async, redit-py renamed the class to `_HiredisParser` (and added an associated `_AsyncHiredisParser`)*

If you have anything in your code calling `redis.connection.HiredisParser`, you will need to (at the very least) **update the reference to `redis.connection._HiredisParser`**. 

One example of this is in [django-redis](https://pypi.org/project/django-redis/), when you define the `PARSER_CLASS` in CACHES >> OPTIONS dict. That resolved my problem immediately.

This change should probably be documented in the docs - or at the very least in the CHANGELOG. Or if `_HiredisParser` is not intended to be imported directly, maybe an example could be added to docs to show how to appropriately use hiredis with redis-py.

**Comment by syphar** [comment]
Looking at the redis-py source, 

in both 4.6.0, and 5.0.0, using the `HiredisParser` was already the default when `hiredis` is found. 

So while this is definitely an undocumented breaking change, IMO the better way forward is just to now explicitly define the parser class.

**Comment by jacklinke** [comment]
@syphar as of 5.0.0, redis-py no longer defines a `HiredisParser` class, but the docs mention that hiredis can be used. I'm just suggesting updating the docs to reflect *how* to do the thing the docs mention to better inform downstream packages/users.

As for django-redis, the parser can be manually specified in its configs, and the docs for that package are now updated.

**Comment by dvora-h** [comment]
@jacklinke The way to use redis-py with hiredis have not changed in 5.0.0, you just need to have hiredis installed on your environment, and AFAIK this is what the docs shows (if not, please LMK where and I'll fix it).

I don't know the django-redis code so I can't understand why you need to call the parser class directly but this is not recommended.
