### ISSUE TITLE
How to re-xreadgroup after redis restart?

### ISSUE THREAD

**Issue by axiangcoding** [redis/redis-py#2937]
**Version**: 4.5.5

**Platform**: Python 3.11

**Description**: A question

i'm using `rds.xreadgroup` in a daemon thread, init at FastAPI start handler.
```
def create_start_app_handler(app: FastAPI) -> Callable:
    def start_app() -> None:
        threading.Thread(target=consumer, args=(rds,), daemon=True).start()
    return start_app
```
```
def consumer(rds: redis.Redis):
    logger.info("start consumer...")
    
    while True:
        consumer_name = uuid.uuid4().hex
        resp = rds.xreadgroup(groupname=group_key, consumername=consumer_name, count=1, block=20,
                              streams={"key": '>'}, noack=True)
        if resp is None or len(resp) == 0:
            logger.trace("no data, continue listening...")
            continue
        else:
            fs_data = resp[0][1][0]
            msg_id, value = fs_data
            do_something()
            rds.xdel(internal_task_stream_key, msg_id)
```

But i am facing a problem, if redis failed for some reason, or restart, consumer will throw a exception and stop read group data. And i want consumer working again after redis reconnected.

What are the best practices for doing such thing?

**Comment by evgenybf** [comment]
What exception does it throw?

I believe, if you want to process the pending messages again, you will have to use XPENDING+XCLAIM or just XAUTOCLAIM - https://redis.io/docs/data-types/streams/

**Comment by axiangcoding** [comment]
hi @evgenybf , I solved this problem by setting up an `while true` loop operation. When redis fails, the infinite loop will be used to reconnect to redis, then re-consuming data.
Thanks for your suggestion, you provided another solution
