### ISSUE TITLE
Redis.json().objlen returns type list instead of int

### ISSUE THREAD

**Issue by trkwyk** [redis/redis-py#2960]
**Version**: redis-stack-server:7.2.0-v2 via docker; redis-py 5.0.0

**Platform**: macOS

**Description**: Redis.json().objlen returns type list instead of int. The typing hint suggests it should return int instead of list. In redis-cli, it does return int though.

**Comment by sjpotter** [comment]
per the documentation, it returns an array. 

https://redis.io/commands/json.objlen/#examples

> JSON.OBJLEN returns an array of integer replies for each path specified as the number of keys in the object or nil, if the matching JSON value is not an object.

the type hint should probably be fixed.
