### ISSUE TITLE
from_url() typed incorrectly

### ISSUE THREAD

**Issue by fennb** [redis/redis-py#2971]
**Version**: 5.0.1

**Platform**: All

**Description**: A recent commit that (very helpfully) introduced type hints to the library has an incorrect return type defined for `Redis.from_url()`. Notably, it declares a return type of `None` rather than `Redis` as it should be.

This was introduced in this commit: https://github.com/redis/redis-py/pull/2952/files#diff-3161b005adfa1f5266a9736bffb5ede9d14e2ab40937cb241bc16ca5647df79dR97

**Comment by mrtolkien** [comment]
Same issue here, this is pretty critical imo because it breaks any CI running linting with redis.

**Comment by dvora-h** [comment]
Fixed in #2963
