### ISSUE TITLE
How to set log level?

### ISSUE THREAD

**Issue by hanjiangxue20** [redis/redis-py#3017]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
4.3.4
**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Ubuntu / Python3.9.5
**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
The Redis cluster has printed a lot of debug logs, and I would like to turn them off. How can I adjust the log level？thanks
`    #eg:  redis.cluster.RedisCluster 
      log.debug(f"Target for {args}: slot {slot}")`

**Comment by chayim** [comment]
As of the later versions of redis-py we don't actually have logging integrations in the code base, other than for resp3 push handlers.

But if you need to set up your own custom logging - here are some resources:

[Python Logging HOWTO](https://docs.python.org/3/howto/logging.html)
[Logging in python, general purpose](https://realpython.com/python-logging/)

If you're looking to add support for logging within the library - I want to say that it's been discussed int he past, and currently isn't in the backlog - but emphasis on currently.
