### ISSUE TITLE
Does hiredis has any drawbacks over pure redis-py?

### ISSUE THREAD

**Issue by aosh-ab7e** [redis/redis-py#3028]
(I'm a newbie here and not sure if here is the correct place to ask question, so feel free to point me the better place to ask (if any))

The README says:
> For faster performance, install redis with hiredis support

This makes me believe that hiredis should be installed by default.
However, in reality, hiredis is not installed by default.

Are there any drawbacks to using hiredis?
I googled for a while and couldn't find any drawback.

**Comment by chayim** [comment]
Not really to be honest with you - it's actually significantly faster. There are some edge cases with parsing that might fail, but it's very much the recommended deployment model.

**Comment by equal-l2** [comment]
Thank you for the reply!

> There are some edge cases with parsing that might fail

Would you give me examples? I'm about to use redis-py with hiredis on production.

**Comment by aosh-ab7e** [comment]
@chayim Thank you for the reply!

> There are some edge cases with parsing that might fail

Would you give me examples? We are planning to use redis-py with hiredis, on production.
