### ISSUE TITLE
Argument name might be wrong

### ISSUE THREAD

**Issue by manojkumarragupathi** [redis/redis-py#3041]
**Version**: redis==5.0.1

**Platform**: Python 3.11.6 in Ubuntu 22.04 LTS. (Invariant of platform)

**Description**: In [core.py](https://github.com/redis/redis-py/blob/master/redis/commands/core.py)  in hdel method, argument name is given as *keys instead keys. This causes error when writing code with parameter hints.

![image](https://github.com/redis/redis-py/assets/96905384/c12f477e-56a2-4083-ab17-6a164b7e4fd1)

![image](https://github.com/redis/redis-py/assets/96905384/76b078c5-80b8-4bc3-9a42-8b3cbc82e886)

**Comment by dvora-h** [comment]
@manojkumarragupathi I'm not sure I understand what is the problem. Why do you think the argument name is wrong?

**Comment by laerson-hammes** [comment]
You need l;eran about *args and **kwargs in Python. When a function accept *args, you can pass it many values, then, the function create a tuple, you dont can pass named args, because named args are used by **kwargs, where the function convert named args to a dict.

**Comment by manojkumarragupathi** [comment]
Yep, my mistake. I understand that we can ignore the parameter hinting for the non-key-args.
