### ISSUE TITLE
Lua scripts created with register_script always return first return item, ignoring others

### ISSUE THREAD

**Issue by M1ha-Shvn** [redis/redis-py#3067]
**Version**:
redis==5.0.0

**Platform**:
Docker container based on [python:3.11.5-slim](https://hub.docker.com/layers/library/python/3.11.5-slim/images/sha256-a28fdf3bde6c0c97b656841669f6b4cc8164d0f34067c6ce6b5532effe94f8a7?context=explore)

**Description**:
Script registered with `register_script` always return single value, ignoring multiple values returned.

***MRE***
```python
client = Redis(...)
script = "return 1, 2, 3"
f = client.register_script(script)
print(f())
# prints: 1
# expected: tuple(1, 2, 3)
```

**Comment by dvora-h** [comment]
@M1ha-Shvn I think this is not a redis-py issue but a lua syntax issue (FYI, this is how it works for me `script = "return {1, 2, 3}"`)
