### ISSUE TITLE
ZDIFF command with unexpected result

### ISSUE THREAD

**Issue by mzlotnik** [redis/redis-py#3079]
**Version**: Redis-py version: 5.0.1 | Redis server version: 7.2.3

**Platform**: ('3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]', 'Darwin', '23.2.0', 'arm64')

**Description**: I am having an unexpected result while using ZDIFF via the redis-py async API. I executed the exact same command manually and got the correct result. I am not an old time user so I might be missing something. Here is a simple code to reproduce:

```
import asyncio
import redis.asyncio as redis
import redis as rredis

async def test_zdiff():
    # Connect to Redis
    r = redis.Redis(host='localhost', port=6379, decode_responses=True)

    # Print redis-py version
    print(f"Redis-py version: {rredis.__version__}")
    # Print the Redis server version
    server_info = await r.info('server')
    server_version = server_info['redis_version']
    print(f'Redis server version: {server_version}')

    # Create two sorted sets
    await r.zadd('set1', {'a': 1, 'b': 2, 'c': 3})
    try:
        await r.zadd('set2', {'b': 2, 'c': 3, 'd': 4})

        # Perform zdiff manually
        diff_manual = await r.execute_command('ZDIFF 2', 'set1', 'set2')
        print(f"Diff (manual): {diff_manual}")

        # Perform zdiff using Redis-py API
        diff_api = await r.zdiff('set1', 'set2')
        print(f"Diff (API): {diff_api}")

        # Assert that both results are the same 
        assert diff_manual == diff_api, "Results of manual zdiff and API zdiff are different"

        # Close the Redis connection
        await r.close()
    except AssertionError as e:
        print(f"AssertionError: {e}")

# Run the test
asyncio.run(test_zdiff())
``` 

The result:
Redis-py version: 5.0.1
Redis server version: 7.2.3
Diff (manual): ['a']
Diff (API): []
AssertionError: Results of manual zdiff and API zdiff are different

Thanks for considering this issue. I'm open to any feedback or suggestions.

**Comment by dvora-h** [comment]
Hi @mzlotnik the issue is that you need to send the keys to `r.zdiff` in a list.
change `await r.zdiff('set1', 'set2')` to `await r.zdiff(['set1', 'set2'])` should solve the problem
