### ISSUE TITLE
StrictRedis.from_url returns function signature returns None but it should be StrictRedis

### ISSUE THREAD

**Issue by Nicu-Ducal** [redis/redis-py#3082]
**Version**: 5.0.1
**Description**: Hello, I have a question: is there any particular reason why the function signature for `from_url` method in StrictRedis class returns a None value, when in practice it returns a StrictRedis object? Because of this, suggestions are not shown by the linter.

```
(method) def from_url(
    url: str,
    **kwargs: Any
) -> None
```

**Comment by dvora-h** [comment]
@Nicu-Ducal Thanks for reporting.

Already fixed here https://github.com/redis/redis-py/pull/2963
