### ISSUE TITLE
5.0.0 introduces CLIENT SETINFO which is not compatible with Redis < 7.2

### ISSUE THREAD

**Issue by earthgecko** [redis/redis-py#3085]
**Version**: 
redis-stack-server: redis-stack-server-6.2.6-v7.rhel8.x86_64.tar.gz
redis_version:6.2.12
redis-py: 5.0.1

**Platform**: Python 3.8.17 on CentOS Stream 8

**Description**:

With the introduction of `CLIENT SETINFO` in connection.py in 5.0.0 (Add support for CLIENT SETINFO (#2857)), the `INFO commandstats` now reports `cmdstats_client` which now increments `failed_calls` on every connection.
```
cmdstat_client:calls=114604,usec=552723,usec_per_call=4.82,rejected_calls=0,failed_calls=114604
```
`SETINFO` was only added in Redis 7.2 therefore 5.0.0 will consider any connection on a Redis < 7.2 as a failed_call.

It seems to have no impact on Redis or the functionality whatsoever, other than incrementing the `failed_calls` counter and it happens on every connect.  Although it does have an impact on telemetry and monitoring.

A very big thanks to Steve L (admin on Redis discord) for the very helpful assistance in identifying the cause of the issue here.

**Comment by dvora-h** [comment]
@earthgecko If you want to skip `CLIENT SETINFO` you can set the library name and version to None ([here](https://github.com/redis/redis-py/pull/2857/files#diff-45b6ba995a827b484d3ef97cb806d336bf058ff9678b04cf371200ea53e584d0R370), it sends the command only if the information exist, and yes, by default it exist)
```
r = redis.Redis(lib_name=None, lib_version=None)
```

**Comment by earthgecko** [comment]
Thanks for the info @dvora-h :+1: I shall implement those additional parameters
