### ISSUE TITLE
Some functions have wrong return types

### ISSUE THREAD

**Issue by ykun91** [redis/redis-py#3091]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
redis-py: 5.0.1
redis: 7.2.3

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python 3.11 on Ubuntu

**Description**: 
Some functions have wrong return types.
like hget in [here](https://github.com/redis/redis-py/blob/master/redis/commands/core.py#L4945-L4947), it was typed as `Union[Awaitable[Optional[str]], Optional[str]]`
but I don't think it is `Awaitable` as it isn't a async function, and it return `bytes` actually, not `str`. 
Same issue may found in other functions.

**Comment by aryaniyaps** [comment]
any updates on this issue?

**Comment by ykun91** [comment]
FYI

Install `types-redis` (https://pypi.org/project/types-redis/) can be a workaround, as types in it is more accurate.

**Comment by ykun91** [comment]
#2399

**Comment by ykun91** [comment]
#2399

**Comment by MaffooBristol** [comment]
I've noticed that since upgrading py-redis from v4 to v5, it now enforces that we pass a string into a hash rather than bytes or anything else. However `types-redis` with v5 seems to undo this somewhat, saying the output of `hget()` is `Unknown | None`. I can't work out which option is the better of two evils...
