### ISSUE TITLE
json set_path without full file path

### ISSUE THREAD

**Issue by markmarkmarkthebest** [redis/redis-py#3094]
Hi, 
Seems like when I use set_path, the key names are the full file path without the file extension for each object.
I think that in some cases the full path might not matter or not wanted at all. 
I would like to open a PR to add that feature (:

**Comment by dvora-h** [comment]
Isn't it exactly what `set_file` do?

**Comment by markmarkmarkthebest** [comment]
The thing is I could use set_file and use a for loop the get all paths and then the keys would be named with the file name, but I think it would be a good addition to set_path, because all set_path does is iterate through the files in the given path and use set_file inside, but the keys are the full path which is not great for all use cases.

**Comment by dvora-h** [comment]
To be honest - I don't think this change is necessary, you can add the iteration loop through the files in your code and use `set_file`
