### ISSUE TITLE
Invalid type hint returns for async functions

### ISSUE THREAD

**Issue by zulrang** [redis/redis-py#3107]
**Version**: What redis-py and what redis version is the issue happening on?
redis==5.0.1
Redis 7.2.4

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python 3.11.6
Ubuntu 22.04.3 (WSL2 / Windows 11)

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
`mypy` reports a ton of errors to the effect of:
```
error: Incompatible types in "await" (actual type "Awaitable[set[Any]] | set[Any]", expected type "Awaitable[Any]")  [misc]
```

And looking through the code, I see that the asyncio version of the classes has a ton of Union types as return types for async functions, which do not function correctly under any use case when using `await` - and I find it hard to believe anyone is using this library as intended while also using type checkers.

Digging deeper, it seems to be just a result of laziness when defining the async versions of the commands, which are just aliases to the sync versions, when the problem is easily solved by copying the classes instead of aliasing them and using the proper return types.

What is even the purpose of ever defining `ResponseT = Union[Awaitable, Any]`?  If you're using type hints, this is meaningless, and if you're using type checkers, it's unworkable.

Creating this issue so I can come back and try to clean up this mess.

**Comment by glassmonkey** [comment]
duplicate?
https://github.com/redis/redis-py/issues/3091
