### ISSUE TITLE
PubSub not awaiting new messages

### ISSUE THREAD

**Issue by ChronoDK** [redis/redis-py#3108]
This is like not an issue, and more of a question on correct use.

If have this loop, and it uses a lot of cpu.

```
while true:
      raw_message = await pubsub.get_message(ignore_subscribe_messages=True)
      if raw_message is not None:
           await send_text(websocket, raw_message["data"])
      await asyncio.sleep(0.001)
```

I would expect the get_message to not return until there is something to return, but it keeps returning None and reaching the sleep function. I would really like it to not do that, and just wait until there is an actual message. How can I do that?

**Comment by nextmat** [comment]
It appears that `get_message` will never yield the event loop by itself, so without the `asyncio.sleep` the loop will run indefinitely and the event loop is blocked.

I'm also confused as to why it works this way, why does `get_message` only return when there is a message actually present?

**Comment by ChronoDK** [comment]
I found the solution to this. It turns out get_message has a timeout parameter. Just set that and it will wait for as long as you like. 

To wait one second:

`raw_message = await pubsub.get_message(ignore_subscribe_messages=True, timeout=1)`
