### ISSUE TITLE
Wrong typing Redis.from_url

### ISSUE THREAD

**Issue by Like6po** [redis/redis-py#3140]
**Version**: 5.0.1
**Platform**: Python 3.11.4

When i create sync client from url: 
<img width="520" alt="image" src="https://github.com/redis/redis-py/assets/42671486/8e80145c-f3bf-44bd-8667-a2f293ea2c5f">
if u check typing, u can see -> None
<img width="674" alt="image" src="https://github.com/redis/redis-py/assets/42671486/b2cdea81-0d9a-4a78-846c-0281439d38eb">
but its return client...
<img width="409" alt="image" src="https://github.com/redis/redis-py/assets/42671486/606ed799-efa1-4757-8302-c83c4d6ab252">

**Comment by dvora-h** [comment]
Hi @Like6po thanks for reporting this, it was fixed already in #2963
