### ISSUE TITLE
Wrong type annotation on the method return type for from_url

### ISSUE THREAD

**Issue by Leggendario12** [redis/redis-py#3143]
There is an error in the type annotation in the Redis client.py file of the Redis class. The from_url method has a type annotation of None for its return, but it is clearly returning an instance of the Redis client.

**Version**:   "^5.2.0"

**Platform**: Ubuntu 22.04

**Description**: Linter warning error of return None.

**Comment by dvora-h** [comment]
Hi @Leggendario12 thanks for reporting this, it was fixed already in #2963

**Comment by andy2mrqz** [comment]
@dvora-h There has not been a release for this project tagged since September, 2023 - is there a plan to release a version with this fix incoporated?

**Comment by wkeil1** [comment]
I'm running into the same issue and am also wondering when the release will come out with the fix.
