### ISSUE TITLE
Redundant async-timeout dependency in Redis 5.0.2

### ISSUE THREAD

**Issue by Zaczero** [redis/redis-py#3174]
The `async-timeout` dependency was originally removed in https://github.com/redis/redis-py/pull/2602 due to its redundancy in modern Python.

It was re-added in Redis 5.0.2 (https://github.com/redis/redis-py/pull/3109) and [appears](https://github.com/search?q=repo%3Aredis%2Fredis-py+async_timeout+NOT+path%3A%2F%5Etests%5C%2Ftest_asyncio%5C%2F%2F&type=code) to still be redundant for Python versions  >= 3.11.3 (or 3.11).

The #3109 PR is the result of issue https://github.com/redis/redis-py/issues/3105.

The error message in #3105 *(ModuleNotFoundError: No module named 'async-timeout')* contains module name with a dash, instead of typical underscore. Hinting, that the error was thrown during the package installation and not runtime _(otherwise it would be async_timeout)_.

It would be helpful if the original reporter of issue #3105 could provide more context from the error stack trace, instead of just the error message itself.

**Comment by Zaczero** [comment]
Attaching log from updating redis `5.0.1` to `5.0.2` on `Python 3.12.2`.

```txt
Updating dependencies
Resolving dependencies... (11.4s)

Package operations: 1 install, 4 updates, 0 removals

  • Updating python-dateutil (2.8.2 -> 2.9.0.post0)
  • Installing async-timeout (4.0.3)
  • Updating pydantic (2.6.2 -> 2.6.3)
  • Updating email-validator (2.1.0.post1 -> 2.1.1)
  • Updating redis (5.0.1 -> 5.0.2)

Writing lock file
```

**Comment by dvora-h** [comment]
@Zaczero Thanks for reporting this. I think you are right but I got a bit confused.
How do you think it need to be now? Do you want to open a PR to fix it?

**Comment by dvora-h** [comment]
Yes, totally make sense, thank you!

Do you want to fix it or want me to do it?

**Comment by Zaczero** [comment]
I usually avoid doing such small PRs but suree https://github.com/redis/redis-py/pull/3177. Heads up, I did not complete the checklist.

**Comment by Zaczero** [comment]
Resolved

```txt
Package operations: 0 installs, 3 updates, 1 removal

  • Removing async-timeout (4.0.3)
  • Updating packaging (23.2 -> 24.0)
  • Updating redis (5.0.2 -> 5.0.3)
  • Updating uvicorn (0.27.1 -> 0.28.0)

Writing lock file
```

**Comment by 9128305** [comment]
with redis 5.0.3  I get new errors running mypy
```
.venv/lib/python3.11/site-packages/redis/_parsers/base.py:9: error: Cannot find implementation or library stub for module named "async_timeout"  [import-not-found]
        from async_timeout import timeout as async_timeout
    ^
.venv/lib/python3.11/site-packages/redis/_parsers/hiredis.py:9: error: Cannot find implementation or library stub for module named "async_timeout"  [import-not-found]
        from async_timeout import timeout as async_timeout
    ^
.venv/lib/python3.11/site-packages/redis/asyncio/connection.py:33: error: Cannot find implementation or library stub for module named "async_timeout"  [import-not-found]
        from async_timeout import timeout as async_timeout
    ^
.venv/lib/python3.11/site-packages/redis/asyncio/connection.py:33: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

```
