### ISSUE TITLE
hiredis 3.0.0 broke CI

### ISSUE THREAD

**Issue by kurtmckee** [redis/redis-py#3327]
hiredis 3.0.0 was released about 4 hours ago at the time of writing.

CI jobs are now failing ([recent example](https://github.com/redis/redis-py/actions/runs/10010951590/job/27673315260)) under the following circumstances:

* RESP3
* hiredis

**Comment by kurtmckee** [comment]
It appears #3324 may address this.

**Comment by kurtmckee** [comment]
#3324 has merged, and this can be closed.

**Comment by akx** [comment]
AIUI, currently released versions of `redis-py` are still broken when used with Hiredis 3.0+, since #3324 hasn't shipped in a release. 😅
