### ISSUE TITLE
`Script` class defined twice

### ISSUE THREAD

**Issue by kurtmckee** [redis/redis-py#3332]
The `Script` class is defined _twice_ in `redis/commands/core.py`, at lines 5462 and 6286:

https://github.com/redis/redis-py/blob/2ffcac32347d5e2ceac3d60e3332367e16774e30/redis/commands/core.py#L5462

https://github.com/redis/redis-py/blob/2ffcac32347d5e2ceac3d60e3332367e16774e30/redis/commands/core.py#L6286

`git blame` shows that both definitions were created on 2022-02-22, by different authors, within 1.5 hours of each other. I intend to submit a PR to delete the first definition, as the first definition is overwritten by the second definition as the file is parsed.

**Comment by akx** [comment]
This would be caught by a linter such as Ruff: https://github.com/redis/redis-py/pull/3147

https://docs.astral.sh/ruff/rules/redefined-while-unused/

**Comment by kurtmckee** [comment]
But then you would be using ruff.

**Comment by akx** [comment]
> But then you would be using ruff.

This is true. Is that a problem?

**Comment by kurtmckee** [comment]
I apologize, my comment just created disharmony and didn't contribute anything useful. Please disregard.
