### ISSUE TITLE
json().get() returns None with RedisCluster after upgrading to version 5.1.0

### ISSUE THREAD

**Issue by vineethvkumar** [redis/redis-py#3394]
**Version**: 5.1.0

**Platform**: Amazon Linux

**Description**: json().get(key) returns `None` after upgrading to version 5.1.0 when working with RedisCluster. The redis CLI command works fine (JSON.GET) for the same key, the issue is only with json().get() with the latest version (5.1.0). This is working as expected with version 5.0.8.

```
from redis import RedisCluster

redis_client = RedisCluster.from_url(url)
json = redis_client.json().get(key)
```

**Comment by dmaier-redislabs** [comment]
@vineethvkumar Thank you very much for your report. We will try to reproduce and analyze the issue.

@vladvildanov Can you please take a look.

**Comment by vladvildanov** [comment]
Hi

Seems to be a side-effect of 5.1 release, will take a look on this
