### ISSUE TITLE
support microsoft entra id for authentication with azure cache for redis (tokens can expire)

### ISSUE THREAD

**Issue by dimbleby** [redis/redis-py#3405]
Azure cache for redis supports authentication using microsoft entra tokens, it would be great if I could make use of that with this client.

https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-azure-active-directory-for-authentication#microsoft-entra-client-workflow describes what needs doing, providing the appropriate values for username and password should be easy per the existing `CredentialProvider` interface.

However so far as I can see there is no mechanism for detecting that the token is about to expire and refreshing it and issuing a fresh `AUTH`.

Thanks!

**Comment by vladvildanov** [comment]
@dimbleby Hey, thanks for reaching us out! We're currently working on a new functionality that will allow to use EntraID as an IdentityProvider. Check for the updates!

**Comment by vladvildanov** [comment]
Closed by #3445, part of 5.3.0 release, already available as beta version 5.3.0b4
