### ISSUE TITLE
get_credential() in CredentialProvider is not async for async client

### ISSUE THREAD

**Issue by yulin-li** [redis/redis-py#3422]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

The async version of Redis client takes `credential_provider` as argument while the `get_credential()` method is not an async method.

I think a better version should be 

```python
class CredentialProvider:
    """
    Credentials Provider.
    """

    async def get_credentials(self) -> Union[Tuple[str], Tuple[str, str]]:
        raise NotImplementedError("get_credentials must be implemented")
```

**Comment by vladvildanov** [comment]
Closed by #3445
