### ISSUE TITLE
How to get string type in response rather than bytestring type?

### ISSUE THREAD

**Issue by Iflier** [redis/redis-py#910]
When use get(), megt(), keys() etc, redis-py always return bytestring. Of cursor, sometimes apply a .decode() method to element of list may get string type. But, if I want always get string type from response, what should i do ?

**Comment by laixintao** [comment]
hi, set `decode_responses=True` when create a redis client

```
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import redis

In [2]: r = redis.StrictRedis(decode_responses=True)

In [3]: r.set('foo', 'bar')
Out[3]: True

In [4]: r.get('foo')
Out[4]: 'bar'

In [5]: type(r.get('foo'))
Out[5]: str
```

And recommend you read the docs before open a issue. 

https://redis-py.readthedocs.io/en/latest/

**Comment by Iflier** [comment]
Hi, @laixintao, thanks for your reply. I have try to set decode_responses to True, and every thing goes well. Thank you again.

**Comment by ramwin** [comment]
Than you for you answer. It helps me a lot.

**Comment by zulrang** [comment]
Nowhere in the documentation does it explain what that kwarg does, only what the default is.  Sure, some people may be able to assume the meaning but "Explicit is better than implicit"

**Comment by zulrang** [comment]
The docs also don't mention that when using a connection pool, the decode_responses argument of StrictRedis is ignored and must be set on the ConnectionPool instead.

**Comment by msmahalakshmi** [comment]
How can the decode_responses or similar be specified on Node.js ? After looking online I could not find such an option. Is there a workaround.

**Comment by andymccurdy** [comment]
@msmahalakshmi This repository has nothing to do with the javascript client. You'll need to talk to the maintainer of that library.

All: I agree, `decode_responses` should be documented. I'll take care of that.

**Comment by chuanwu** [comment]
LOL, `decode_responses` should be the default settings, i think.

**Comment by OverlordQ** [comment]
And it's still not documented.

**Comment by HuuLane** [comment]
> hi @Iflier , set `decode_responses=True` when create a redis client
> 
> ```
> Python 3.6.1 (default, Apr  4 2017, 09:40:21)
> Type 'copyright', 'credits' or 'license' for more information
> IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import redis
> 
> In [2]: r = redis.StrictRedis(decode_responses=True)
> 
> In [3]: r.set('foo', 'bar')
> Out[3]: True
> 
> In [4]: r.get('foo')
> Out[4]: 'bar'
> 
> In [5]: type(r.get('foo'))
> Out[5]: str
> ```
> 
> And recommend you read the docs before open a issue.
> 
> https://redis-py.readthedocs.io/en/latest/

Hi! redis-py 3.0 drops support for the legacy "Redis" client class. "StrictRedis" has been renamed to "Redis" and an alias named "StrictRedis" is provided so that users previously using "StrictRedis" can continue to run unchanged.
```
conn = redis.StrictRedis(decode_responses=True)
```

**Comment by black-snow** [comment]
This just bit me in the arse almost seven years later.

Why isn't this the default? I'd expect that `get('key')` returns *exactly*  what `set('key', 'val')` inserted.
Slapping a [RTFM](https://redis-py.readthedocs.io/en/latest/examples/connection_examples.html#By-default-Redis-return-binary-responses,-to-decode-them-use-decode_responses=True) isn't really helpful when it's hidden *way* down in the documentation. 

If there's good reason for why this isn't the default shouldn't there be a hint beneath the docs of `get()` and `set()`? Like "hey dude, don't expect to receive what you inserted UNLESS YOU CONFIGURE X"?
